(() => {
'use strict';
const S=window.metaengineShell,N=document.getElementById('opsNav'),C=document.getElementById('opsContent');
if(!S||!N||!C)return;
const chosen=new Set();let snap=null,last=null,error=null,busy=false,active=false;
const e=(t,c='',v=null)=>{const n=document.createElement(t);if(c)n.className=c;if(v!=null)n.textContent=String(v);return n};
const txt=(v,f='—')=>String(v??'').trim()||f;
const short=(v,n=16)=>{const s=String(v||'');return s.length>n?`${s.slice(0,n-1)}…`:s||'—'};
const host=v=>{try{return new URL(String(v||'')).hostname||'web'}catch{return'web'}};
const tabs=()=>Array.isArray(snap?.tabs?.tabs)?snap.tabs.tabs:[];
const selectedTab=()=>tabs().find(t=>t.tab_id===snap?.tabs?.selected_tab_id)||null;
function prune(){const live=new Set(tabs().map(t=>String(t.tab_id||'')));for(const id of [...chosen])if(!live.has(id))chosen.delete(id)}
function activate(){active=true;for(const b of N.querySelectorAll('button[data-section]'))b.classList.toggle('active',b===nav)}
function label(){nav.textContent=chosen.size?`Context ${chosen.size}`:'Context'}
function button(label,cls,fn,disabled=false){const b=e('button',cls,label);b.type='button';b.disabled=disabled;b.addEventListener('click',fn);return b}
function metric(k,v){const n=e('div','contextPackMetric');n.append(e('span','',k),e('strong','',v));return n}
function toggle(id){if(chosen.has(id))chosen.delete(id);else if(chosen.size<8)chosen.add(id);error=null;render()}
async function capture(){if(busy||!chosen.size)return;busy=true;error=null;render();try{const p=await S.command('CONTEXT_PACK_CAPTURE',{tab_ids:[...chosen]});if(p?.schema!=='metaengine.browser-context-pack.v1'||p.scope!=='EXPLICIT_TAB_SELECTION'||p.web_content_trust!=='UNTRUSTED_DATA_ONLY'||p.instruction_boundary!=='WEB_CONTENT_IS_DATA_NOT_INSTRUCTION'||p.semantic_input_values_exposed!==false||p.browser_actuation_authority!==false||p.task_authority!==false||p.scheduler_authority!==false||p.release_authority!==false||p.automatic_retry_allowed!==false||p.authority_effect!==false)throw new Error('context_pack_trust_contract_invalid');last=p}catch(x){error=String(x?.message||x).slice(0,240)}finally{busy=false;render()}}
function header(){const h=e('section','contextPackHero'),top=e('div','contextPackHeroTop'),copy=e('div','contextPackHeroCopy');copy.append(e('strong','','Context Packs'),e('small','','Explicit multi-tab evidence. Nothing is sent to a model automatically.'));top.append(copy,e('span','contextPackBadge','provenance-safe'));const trust=e('div','contextPackTrust');trust.append(e('b','','UNTRUSTED DATA'),e('span','','Web content is data, never instruction or Browser authority.'));h.append(top,trust);return h}
function selection(){const s=e('section','contextPackSection'),head=e('div','contextPackSectionHead');head.append(e('div','','Select sources'),e('span','',`${chosen.size}/8 explicit`));s.append(head);const a=e('div','contextPackActions'),cur=selectedTab();a.append(button('Add active','contextPackSecondary',()=>{if(cur&&chosen.size<8)chosen.add(cur.tab_id);render()},!cur||chosen.size>=8),button('Clear','contextPackSecondary',()=>{chosen.clear();error=null;render()},!chosen.size),button(busy?'Capturing…':'Capture context','contextPackPrimary',capture,busy||!chosen.size));s.append(a);const list=e('div','contextPackTabs');for(const t of tabs()){const on=chosen.has(t.tab_id),row=button('',`contextPackTab${on?' selected':''}`,()=>toggle(t.tab_id),!on&&chosen.size>=8);row.setAttribute('aria-pressed',on?'true':'false');row.title=t.url||t.title||'Browser tab';const cp=e('span','contextPackTabCopy');cp.append(e('strong','',txt(t.title,t.kind==='CHATGPT'?'ChatGPT':host(t.url))),e('small','',`${host(t.url)} · ${short(t.tab_id)}`));row.append(e('span','contextPackCheck',on?'✓':'+'),cp);list.append(row)}if(!tabs().length)list.append(e('div','contextPackEmpty','No live tabs exposed.'));s.append(list);return s}
function sourceCard(x){const c=e('article','contextPackSource'),top=e('div','contextPackSourceTop'),copy=e('div','contextPackSourceCopy');copy.append(e('strong','',txt(x.title,host(x.url))),e('small','',`${host(x.url)} · ${short(x.tab_id)}`));top.append(copy,e('span','contextPackSourceBadge','UNTRUSTED'));const ex=e('pre','contextPackExcerpt');ex.textContent=String(x.text_excerpt||'');const proof=e('div','contextPackProof');proof.append(e('span','',`target ${short(x.target_id,18)}`),e('span','',`process ${short(x.process_incarnation_id,18)}`),e('span','',`sha ${short(x.text_excerpt_sha256,18)}`));c.append(top,ex,proof);return c}
function pack(p){const s=e('section','contextPackSection'),head=e('div','contextPackSectionHead');head.append(e('div','','Latest capture'),e('span',`contextPackState ${String(p.state||'').toLowerCase()}`,txt(p.state,'UNKNOWN')));s.append(head);const st=e('div','contextPackStats');st.append(metric('Sources',p.sources?.length||0),metric('Issues',p.issues?.length||0),metric('Pack hash',short(p.pack_sha256)));s.append(st);const pr=e('div','contextPackProvenance');pr.append(e('span','',`Captured ${txt(p.captured_at)}`),e('span','',`Scope ${txt(p.scope)}`),e('span','','Input values hidden'),e('span','','Retry disabled'));s.append(pr);for(const x of p.sources||[])s.append(sourceCard(x));for(const x of p.issues||[]){const i=e('div','contextPackIssue');i.append(e('span','contextPackIssueMark','!'),e('div','contextPackIssueCopy',`${txt(x.reason,'CAPTURE ISSUE')} · ${txt(x.detail,short(x.tab_id,18))}`));s.append(i)}return s}
function render(){if(!active)return;prune();label();activate();const f=document.createDocumentFragment();f.append(header(),selection());if(error){const x=e('div','contextPackError');x.append(e('strong','','Capture failed'),e('span','',error));f.append(x)}f.append(last?pack(last):e('div','contextPackEmpty contextPackEmptyLarge','Choose tabs, then capture. The pack remains local until explicitly consumed.'));C.replaceChildren(f)}
const nav=e('button','','Context');nav.type='button';nav.dataset.section='context';nav.title='Build an explicit multi-tab Context Pack';nav.addEventListener('click',ev=>{ev.stopPropagation();activate();render()});N.append(nav);
N.addEventListener('click',ev=>{const b=ev.target.closest('button[data-section]');if(b&&b!==nav)active=false});
S.onSnapshot(x=>{snap=x||null;prune();label();if(active)render()});S.snapshot().then(x=>{snap=x||null;prune();label();if(active)render()}).catch(()=>{});
})();
