begin;
create extension if not exists pgtap with schema extensions;
set local search_path=pg_catalog,public,destruktion_meta,extensions;
select plan(18);
select ok(to_regclass('destruktion_meta.compute_fabric_a2_macroblock_h205f22') is not null,'macroblock ledger exists');
select ok(to_regclass('destruktion_meta.compute_fabric_a2_macroblock_node_h205f22') is not null,'macroblock node ledger exists');
select is(has_table_privilege('service_role','destruktion_meta.compute_fabric_a2_macroblock_h205f22','select'),false,'service role has no direct macroblock table read');
select is(has_table_privilege('service_role','destruktion_meta.compute_fabric_a2_macroblock_node_h205f22','select'),false,'service role has no direct node table read');
select ok(to_regprocedure('public.h205f22_a2_macroblock_open_v1(uuid,text,text,text,jsonb)') is not null,'open RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_ack_v1(uuid,text,text)') is not null,'pair ACK RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_start_v1(uuid)') is not null,'start RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_bind_node_v1(uuid,text,jsonb,jsonb,boolean)') is not null,'node bind RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_node_result_v1(uuid,text,text,jsonb,jsonb)') is not null,'node result RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_gate_ack_v1(uuid,text,text)') is not null,'hard gate ACK RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_gate_resume_v1(uuid)') is not null,'hard gate resume RPC exists');
select ok(to_regprocedure('public.h205f22_a2_macroblock_read_v1(uuid)') is not null,'readback RPC exists');
select ok((select pg_get_functiondef('public.h205f22_a2_macroblock_ack_v1(uuid,text,text)'::regprocedure) like '%a2_macroblock_plan_sha_mismatch%'),'plan ACK is hash-fenced');
select ok((select pg_get_functiondef('public.h205f22_a2_macroblock_start_v1(uuid)'::regprocedure) like '%a2_macroblock_not_sealed%'),'execution cannot start before pair seal');
select ok((select pg_get_functiondef('public.h205f22_a2_macroblock_bind_node_v1(uuid,text,jsonb,jsonb,boolean)'::regprocedure) like '%a2_macroblock_dependency_unsatisfied%'),'dependency bypass fails closed');
select ok((select pg_get_functiondef('public.h205f22_a2_macroblock_gate_resume_v1(uuid)'::regprocedure) like '%a2_macroblock_gate_not_pair_acked%'),'hard gate resume requires pair ACK');
select is(has_function_privilege('anon','public.h205f22_a2_macroblock_start_v1(uuid)','execute'),false,'anon cannot start macroblocks');
select is(has_function_privilege('authenticated','public.h205f22_a2_macroblock_node_result_v1(uuid,text,text,jsonb,jsonb)','execute'),false,'authenticated clients cannot forge node results');
select * from finish();
rollback;
