import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const CLIENT_MARKER="metaengine-supervisor-v1";
const BROKER="https://xpeibufgzjknrhbhpffp.supabase.co/functions/v1/metaengine-live-peer-broker-h205f22";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
function out(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:H});}
function auth(req:Request){return req.headers.get("x-metaengine-client")===CLIENT_MARKER||(req.headers.get("authorization")||"")===`Bearer ${CLIENT_MARKER}`;}
function normText(v:string){return v.normalize("NFKC").trim().replace(/\s+/g," ").toLowerCase();}
function normNumber(v:string){const s=v.normalize("NFKC").trim().replace(/,/g,"");if(!/^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?String(Object.is(n,-0)?0:n):null;}
function sameAnswer(a:string,b:string){if(normText(a)===normText(b))return true;const x=normNumber(a),y=normNumber(b);return x!==null&&y!==null&&x===y;}
async function broker(body:unknown,path=""){const r=await fetch(`${BROKER}${path}`,{method:"POST",headers:{"content-type":"application/json","x-metaengine-client":CLIENT_MARKER},body:JSON.stringify(body),signal:AbortSignal.timeout(120_000)});const text=await r.text();let payload:any;try{payload=JSON.parse(text);}catch{throw new Error(`broker_non_json:${r.status}`);}return{status:r.status,payload};}
async function independentTiebreak(prompt:string){const {status,payload}=await broker({model:"llama32",messages:[{role:"user",content:`Solve the following task independently. Do not discuss other models. Return exactly one JSON object with one key named answer whose value is only your final answer, with no explanation.\n\nTASK:\n${prompt}`}],response_format:{type:"json_object"},max_tokens:256},"/v1/chat/completions");if(status!==200)throw new Error(`tiebreak_http_${status}:${JSON.stringify(payload).slice(0,400)}`);const content=String(payload?.choices?.[0]?.message?.content||"");const parsed=JSON.parse(content);if(parsed===null||typeof parsed!=="object"||Array.isArray(parsed)||!("answer" in parsed))throw new Error("tiebreak_answer_missing");return{peer_id:payload?.metaengine?.peer_id||null,served_model:payload?.metaengine?.upstream_served_model||payload?.model||null,answer:String(parsed.answer),normalization:payload?.metaengine?.normalization||null,latency_ms:payload?.metaengine?.latency_ms??null};}
function baseDecision(payload:any){const availability=payload?.availability_quorum_met===true||payload?.ok===true,signal=String(payload?.agreement?.signal||"insufficient");let state="INSUFFICIENT";if(availability&&(signal==="exact_match"||signal==="numeric_match"))state="AGREED";else if(signal==="divergent")state="DIVERGENT";return{availability,state,candidate:state==="AGREED"?payload?.agreement?.candidate??null:null};}
Deno.serve(async req=>{if(!auth(req))return out(401,{ok:false,error:"unauthorized"});const body=req.method==="POST"?await req.json().catch(()=>({})):{};const prompt=String(body?.prompt||"").slice(0,8000);if(!prompt.trim())return out(400,{ok:false,error:"prompt_required"});let committee:any;try{committee=(await broker({action:"committee",prompt,max_tokens:body?.max_tokens})).payload;}catch(e){return out(502,{ok:false,error:String((e as Error)?.message||e)});}const d=baseDecision(committee);let state=d.state,candidate=d.candidate,tiebreak:any=null;const successful=Array.isArray(committee?.results)?committee.results.filter((x:any)=>x?.ok===true):[];const alreadyHasLlama32=successful.some((x:any)=>x?.model==="llama32");if(state==="DIVERGENT"&&!alreadyHasLlama32&&successful.length>=2){try{tiebreak=await independentTiebreak(prompt);const matches=successful.filter((x:any)=>typeof x?.text==="string"&&sameAnswer(x.text,tiebreak.answer)).map((x:any)=>x.model);if(matches.length){state="TIEBREAK_SUPPORT";candidate=tiebreak.answer;tiebreak.matched_models=matches;tiebreak.observed_support_count=matches.length+1;}else{state="THREE_WAY_DIVERGENCE";candidate=null;tiebreak.matched_models=[];tiebreak.observed_support_count=1;}}catch(e){tiebreak={ok:false,error:String((e as Error)?.message||e)};state="DIVERGENT";candidate=null;}}
return out(200,{ok:true,schema:"metaengine.peer-decision.v2",availability_quorum_met:d.availability,decision_state:state,answer_candidate:candidate,answer_agreement_observed:state==="AGREED",tiebreak_support_observed:state==="TIEBREAK_SUPPORT",truth_claimed:false,semantic_consensus:null,requires_supervisor_judgment:true,tiebreak,committee});});
