const params=new URLSearchParams(location.search);
const workspace=params.get("workspace_id")||"063e3923-ef85-4226-9843-861ad4ec5a21";
const state={events:[],byId:new Map(),filter:"ALL",frontier:0,semanticPoint:"—",mode:"—",peers:{GPT:{},GLM:{}},sync:{},authority:{},selected:null,started:{GPT:0,GLM:0},lastFocus:null};
const $=id=>document.getElementById(id);
$("workspaceLabel").textContent=workspace;
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[char]);
const text=(value,fallback="—")=>value===null||value===undefined||value===""?fallback:String(value);
const short=(value,length=12)=>{const output=text(value,"");return output.length>length?`${output.slice(0,length)}…`:output;};
const payload=event=>event?.payload&&typeof event.payload==="object"?event.payload:{};
const action=event=>payload(event).a2_action&&typeof payload(event).a2_action==="object"?payload(event).a2_action:{};
function summary(event){const p=payload(event);for(const key of ["claim","summary","reasoning_summary","message","result","question","hypothesis","plan","error"]){const value=p[key];if(Array.isArray(value)&&value.length)return value.map(String).join(" · ");if(typeof value==="string"&&value.trim())return value.trim();}return text(p.tool||p.state||event.event_type,"event");}
function category(event){const type=text(event.event_type);if(/TOOL|FILE|PATCH|TEST/.test(type))return"TOOLS";if(/AUTHORITY/.test(type))return"AUTHORITY";if(/MODEL|CATCH_UP|CHECKPOINT|BACKPRESSURE|ERROR|PEER_EVENT/.test(type))return"RUNTIME";return"COGNITION";}
function phaseColor(phase){return phase==="PROPOSE"?"":phase==="CHALLENGE"?"warn":phase==="DECIDE"?"good":"";}
function paint(id,label,kind=""){const element=$(id);element.textContent=label;element.classList.remove("good","warn","bad");if(kind)element.classList.add(kind);}
function ingest(event){if(!event||typeof event!=="object"||!event.event_id)return;const existing=state.byId.get(event.event_id);if(existing)Object.assign(existing,event);else{state.byId.set(event.event_id,event);state.events.push(event);}state.events.sort((a,b)=>Number(a.commit_seq||0)-Number(b.commit_seq||0));state.frontier=Math.max(state.frontier,Number(event.commit_seq||0));if(event.semantic_point)state.semanticPoint=event.semantic_point;const agent=event.agent||event.agent_id;if((agent==="GPT"||agent==="GLM")&&event.model_provenance?.requested_model)state.peers[agent].model=event.model_provenance.requested_model;if(agent==="GPT"||agent==="GLM"){if(event.event_type==="MODEL_STARTED")state.started[agent]=Date.parse(event.created_at||new Date().toISOString());if(["MODEL_COMPLETED","MODEL_INTERRUPTED","ERROR"].includes(event.event_type))state.started[agent]=0;}}
function acknowledgementMap(){const map=new Map();for(const event of state.events){for(const agent of Array.isArray(event.applied_by)?event.applied_by:[]){const set=map.get(event.event_hash)||new Set();set.add(agent);map.set(event.event_hash,set);}if(event.event_type!=="PEER_EVENT_APPLIED")continue;for(const hash of Array.isArray(payload(event).peer_event_hashes)?payload(event).peer_event_hashes:[]){const set=map.get(hash)||new Set();set.add(event.agent||event.agent_id);map.set(hash,set);}}return map;}
function renderRound(){const round=state.sync?.current_round||{};const status=text(round.status,"WAITING");$("roundNumber").textContent=text(round.round_seq,"—");$("roundPhase").textContent=text(round.deliberation_phase,"WAITING");$("roundPhase").className=phaseColor(round.deliberation_phase);$("roundStatus").textContent=status;$("roundBase").textContent=`#${text(round.base_commit_seq,"—")}`;$("gptSlot").textContent=round.gpt_session_id?"ready":"joining";$("glmSlot").textContent=round.glm_session_id?"ready":"joining";$("gptResult").textContent=round.gpt_event_hash?`result ${short(round.gpt_event_hash,10)}`:"result pending";$("glmResult").textContent=round.glm_event_hash?`result ${short(round.glm_event_hash,10)}`:"result pending";const copy={PROPOSE:"Both peers reason independently from the same immutable frontier.",CHALLENGE:"Each peer must bind its critique to the other model's committed event.",DECIDE:"Matching actions unlock autonomous execution; disagreement opens a formal duel."};$("roundSummary").textContent=copy[round.deliberation_phase]||"Waiting for both exact-model peers to claim one immutable frontier.";$("interactionState").textContent=round.deliberation_phase?`${round.deliberation_phase.toLowerCase()} · DB fenced`:"propose → challenge → decide";const remaining=round.expires_at?Math.max(0,Date.parse(round.expires_at)-Date.now()):null;$("roundDeadline").textContent=remaining===null?"awaiting peer":status==="OPEN"?`${(remaining/1000).toFixed(1)}s`:status.toLowerCase();}
function renderAgents(){for(const agent of ["GPT","GLM"]){const key=agent.toLowerCase(),peer=state.peers[agent]||{},received=Number(peer.received||0),applied=Number(peer.applied??peer.lastSeen??0),latest=[...state.events].reverse().find(event=>(event.agent||event.agent_id)===agent&&event.event_type!=="PEER_EVENT_APPLIED");$(key+"Model").textContent=text(peer.model,agent==="GPT"?"openai/gpt-5.6-sol":"zai/glm-5.3");$(key+"Received").textContent=received;$(key+"Applied").textContent=applied;$(key+"Lag").textContent=Math.max(0,state.frontier-applied);$(key+"Current").textContent=latest?`${latest.event_type} · ${short(summary(latest),74)}`:"waiting";const online=peer.status==="ACTIVE";paint(key+"Health",online?"active":"offline",online?"good":"");}}
function renderVisibility(){const acks=acknowledgementMap();const rows=state.events.filter(event=>event.event_type!=="PEER_EVENT_APPLIED").slice(-60).reverse();$("visibilityRows").innerHTML=rows.length?rows.map(event=>{const origin=event.agent||event.agent_id,trace=action(event).trace_id,seen=acks.get(event.event_hash)||new Set();const status=agent=>origin===agent?'<span class="cell-status origin">origin</span>':seen.has(agent)?'<span class="cell-status seen">applied</span>':'<span class="cell-status pending">pending</span>';return`<tr data-event-id="${esc(event.event_id)}"><td class="mono">#${esc(event.commit_seq)}</td><td><strong>${esc(event.event_type)}</strong><br><span class="mono">${esc(short(event.event_hash,10))}</span></td><td class="mono">${esc(short(trace,12))}</td><td>${status("GPT")}</td><td>${status("GLM")}</td></tr>`;}).join(""):'<tr><td colspan="5" class="empty">No committed actions yet.</td></tr>';}
function renderLedger(){const visible=state.events.filter(event=>state.filter==="ALL"||category(event)===state.filter).slice(-240).reverse();$("actionLedger").innerHTML=visible.length?visible.map(event=>`<article class="action-row" data-event-id="${esc(event.event_id)}" data-agent="${esc(event.agent||event.agent_id||"SYSTEM")}"><span class="seq mono">#${esc(event.commit_seq)}</span><span class="actor">${esc(event.agent||event.agent_id||"SYSTEM")}</span><span class="kind">${esc(event.event_type)}</span><span class="summary">${esc(summary(event))}</span><span class="trace mono">${esc(short(action(event).traceparent||event.event_hash,18))}</span></article>`).join(""):'<p class="empty">No events in this filter.</p>';}
function renderAuthority(){const value=state.authority||{};$("authorityCheckpoint").textContent=short(value.checkpoint_id,24);$("authorityRoot").textContent=short(value.payload_root_sha256,20);$("authorityNext").textContent=text(value.next_mainline);$("authorityIntegrity").textContent=value.fresh===true?"fresh / no drift":"stale or drifted";paint("authorityHealth",value.fresh===true?"AUTHORITY · fresh":"AUTHORITY · fenced",value.fresh===true?"good":"bad");}
function render(){$("frontierBadge").textContent=`commit ${state.frontier}`;$("semanticPoint").textContent=state.semanticPoint;$("mode").textContent=state.mode;$("duelState").textContent=state.mode==="DUEL"?"active":"idle";renderRound();renderAgents();renderVisibility();renderLedger();renderAuthority();document.querySelectorAll("[data-event-id]").forEach(element=>element.onclick=()=>openInspector(state.byId.get(element.dataset.eventId),element));}
async function loadSnapshot(silent=false){try{const response=await fetch(`/a2/api/snapshot?workspace_id=${encodeURIComponent(workspace)}`,{credentials:"same-origin",cache:"no-store"});if(!response.ok)throw new Error(`snapshot ${response.status}`);const body=await response.json();for(const event of Array.isArray(body.events)?body.events:[])ingest(event);state.frontier=Math.max(state.frontier,Number(body.frontier?.head_commit_seq||0));state.semanticPoint=body.semantic_point||state.semanticPoint;state.mode=body.mode||state.mode;state.peers={...state.peers,...(body.peers||{})};state.sync=body.sync||{};state.authority=body.authority||{};paint("causalHealth","CAUSAL · synchronized","good");render();}catch(error){paint("causalHealth","CAUSAL · unavailable","bad");if(!silent)toast(String(error));}}
function connect(){const source=new EventSource(`/a2/api/events?workspace_id=${encodeURIComponent(workspace)}&after=${state.frontier}`);source.onopen=()=>paint("liveHealth","LIVE · connected","good");source.onmessage=message=>{try{const event=JSON.parse(message.data);if(event.type!=="heartbeat"){ingest(event);render();}}catch{}};source.onerror=()=>paint("liveHealth","LIVE · reconnecting","warn");}
function toast(message){const element=$("toast");element.textContent=message;element.classList.add("show");setTimeout(()=>element.classList.remove("show"),2800);}
function openInspector(event,trigger){if(!event)return;state.selected=event;state.lastFocus=trigger||document.activeElement;$("inspector").classList.add("open");$("inspector").setAttribute("aria-hidden","false");$("scrim").hidden=false;$("inspectTitle").textContent=`${event.event_type} · #${event.commit_seq}`;renderInspector("reason");$("closeInspector").focus();}
function closeInspector(){$("inspector").classList.remove("open");$("inspector").setAttribute("aria-hidden","true");$("scrim").hidden=true;state.lastFocus?.focus?.();}
async function renderInspector(tab){const event=state.selected;if(!event)return;document.querySelectorAll(".inspect-tabs button").forEach(button=>button.classList.toggle("active",button.dataset.tab===tab));const p=payload(event),vp=event.visibility_proof||{},a=action(event),acks=[...(acknowledgementMap().get(event.event_hash)||new Set())];let html="";if(tab==="reason")html=`<section class="inspect-section"><h3>Public engineering rationale</h3><pre>${esc(summary(event))}</pre></section><section class="inspect-section"><h3>Evidence · assumptions · falsifier</h3><pre>${esc(JSON.stringify({evidence:p.evidence_used||p.evidence||[],assumptions:p.assumptions||[],counterexample:p.counterexample||null,falsifier:p.falsifier||null,tests:p.tests_required||[]},null,2))}</pre></section>`;else if(tab==="visibility")html=`<section class="inspect-section"><h3>Cross-peer acknowledgement</h3><div class="kv"><span>origin</span><span>${esc(event.agent||event.agent_id)}</span><span>applied by</span><span>${esc(acks.join(", ")||"pending")}</span><span>seen commit</span><span>${esc(text(vp.seen_commit_seq))}</span><span>input frontier</span><span class="mono">${esc(text(vp.input_frontier_hash))}</span></div></section><section class="inspect-section"><h3>Mandatory peer hashes</h3><pre>${esc(JSON.stringify(vp.mandatory_peer_event_hashes||[],null,2))}</pre></section>`;else if(tab==="action")html=`<section class="inspect-section"><h3>Action envelope</h3><pre>${esc(JSON.stringify(a,null,2))}</pre></section><section class="inspect-section"><h3>Tool / proposed action</h3><pre>${esc(JSON.stringify({proposed_action:p.proposed_action,resulting_action:p.resulting_action,tool:p.tool,arguments:p.arguments,result:p.result,error:p.error},null,2))}</pre></section>`;else html=`<section class="inspect-section"><h3>Hashes and causal parents</h3><div class="kv"><span>event</span><span class="mono">${esc(text(event.event_hash))}</span><span>payload</span><span class="mono">${esc(text(event.payload_sha256))}</span><span>parents</span><span class="mono">${esc((event.parent_hashes||[]).join("\n"))}</span></div></section><section class="inspect-section"><h3>Trusted ingress</h3><pre>${esc(JSON.stringify(event.ingress_receipt||{status:"not available"},null,2))}</pre></section>`;$("inspectBody").innerHTML=html;}
document.querySelectorAll(".filters button").forEach(button=>button.onclick=()=>{state.filter=button.dataset.filter;document.querySelectorAll(".filters button").forEach(candidate=>candidate.classList.toggle("active",candidate===button));render();});
document.querySelectorAll(".inspect-tabs button").forEach(button=>button.onclick=()=>renderInspector(button.dataset.tab));
$("closeInspector").onclick=closeInspector;$("scrim").onclick=closeInspector;document.addEventListener("keydown",event=>{if(event.key==="Escape"&&$("inspector").classList.contains("open"))closeInspector();});
setInterval(()=>{renderRound();const now=Date.now();for(const agent of ["GPT","GLM"]){const gap=state.started[agent]?Math.max(0,now-state.started[agent]):0;$(agent.toLowerCase()+"Gap").textContent=`opaque gap ${gap} ms`;$(agent.toLowerCase()+"Gap").style.color=gap>=15000?"var(--red)":gap>=5000?"var(--amber)":"";}},250);
setInterval(()=>void loadSnapshot(true),5000);
await loadSnapshot();connect();
