import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const CLIENT_MARKER="metaengine-supervisor-v1";const headers={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
type Peer={id:string;served_model:string;family:string;quality:string;availability:string;reservation_hint_seconds:number|null;base:string;api:string;transport:"gradio_sse"|"gradio3_iter";buildData:(prompt:string)=>unknown[]};
const PEERS:Record<string,Peer>={
 gemma2:{id:"gemma2",served_model:"google/gemma-2-2b-it",family:"google-gemma",quality:"fast",availability:"zerogpu",reservation_hint_seconds:60,base:"https://huggingface-projects-gemma-2-2b-it.hf.space",api:"generate",transport:"gradio_sse",buildData:p=>[p,[],96,0.2,0.9,50,1.1]},
 nemotron:{id:"nemotron",served_model:"nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",family:"nvidia-nemotron",quality:"strong",availability:"zerogpu",reservation_hint_seconds:null,base:"https://akhaliq-nvidia-nemotron-3-5-lightning-30b-a3b-bf16.hf.space",api:"respond",transport:"gradio_sse",buildData:p=>[p,[],160,0.2,0.95,false]},
 tinyllama:{id:"tinyllama",served_model:"PY007/TinyLlama-1.1B-Chat-v0.2-GGUF",family:"tinyllama",quality:"availability",availability:"always-on-cpu",reservation_hint_seconds:0,base:"https://kirp-tinyllama-chat.hf.space",api:"predict",transport:"gradio3_iter",buildData:p=>[p,0.1,1.0,50,64]},
 llama2:{id:"llama2",served_model:"meta-llama/Llama-2-13b-chat-hf",family:"meta-llama",quality:"medium",availability:"zerogpu-backup",reservation_hint_seconds:90,base:"https://huggingface-projects-llama-2-13b-chat.hf.space",api:"generate",transport:"gradio_sse",buildData:p=>[p,[],"You are a concise helpful assistant.",96,0.2,0.9,50,1.1]},
};
const PRIMARY=["gemma2","nemotron"];const BACKUPS=["tinyllama","llama2"];const cooldownUntil=new Map<string,number>();const lastFailure=new Map<string,{at:string;kind:string;message:string}>();
function out(s:number,b:unknown){return new Response(JSON.stringify(b),{status:s,headers});}function auth(r:Request){return r.headers.get("x-metaengine-client")===CLIENT_MARKER;}
function parseSse(t:string){const e:Array<{event:string;data:unknown}>=[];let c="message";for(const raw of t.split(/\r?\n/)){const l=raw.trimEnd();if(l.startsWith("event:")){c=l.slice(6).trim();continue;}if(l.startsWith("data:")){const p=l.slice(5).trim();let d:unknown=p;try{d=JSON.parse(p);}catch(_){}e.push({event:c,data:d});}}return{events:e,terminal:[...e].reverse().find(x=>x.event==="complete"||x.event==="error")??e.at(-1)??null};}
function normalize(raw:string){const v=raw.trim();const i=v.lastIndexOf("</think>");if(i>=0&&v.slice(i+8).trim())return{text:v.slice(i+8).trim(),normalization:"after_think_end"};const f=v.match(/<final>([\s\S]*?)<\/final>/i);if(f?.[1]?.trim())return{text:f[1].trim(),normalization:"final_tag"};return{text:v,normalization:"none"};}
function comparableText(v:string){return v.normalize("NFKC").trim().replace(/\s+/g," ").toLowerCase();}
function comparableNumber(v:string){const s=v.normalize("NFKC").trim().replace(/,/g,"");if(!/^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$/.test(s))return null;const n=Number(s);if(!Number.isFinite(n))return null;return Object.is(n,-0)?"0":String(n);}
function largestCluster(groups:Map<string,string[]>){return[...groups.entries()].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]))[0]??null;}
function analyzeAgreement(results:any[]){const ok=results.filter(x=>x?.ok===true&&typeof x.text==="string");const base={evaluated:ok.length>=2,successful_responses:ok.length,truth_claimed:false,semantic_consensus:null,requires_supervisor_judgment:true};if(ok.length<2)return{...base,signal:"insufficient",unanimous:false,divergence_detected:false,matched_models:[],candidate:null,agreement_ratio:ok.length?1:0};const exact=new Map<string,string[]>(),nums=new Map<string,string[]>();for(const r of ok){const ek=comparableText(r.text);exact.set(ek,[...(exact.get(ek)||[]),r.model]);const nk=comparableNumber(r.text);if(nk!==null)nums.set(nk,[...(nums.get(nk)||[]),r.model]);}const ex=largestCluster(exact),nu=largestCluster(nums);let signal="divergent",cluster:([string,string[]]|null)=null,candidate:string|null=null;if(ex&&ex[1].length>=2){signal="exact_match";cluster=ex;candidate=ok.find(x=>comparableText(x.text)===ex[0])?.text?.trim()??ex[0];}else if(nu&&nu[1].length>=2){signal="numeric_match";cluster=nu;candidate=nu[0];}const size=cluster?.[1].length??1;return{...base,signal,unanimous:size===ok.length&&signal!=="divergent",divergence_detected:size<ok.length,matched_models:cluster?.[1]??[],candidate,agreement_ratio:size/ok.length};}
function classify(m0:string){const m=m0.toLowerCase();if(m.includes("quota")||m.includes("try again in"))return{kind:"quota",ms:30*60_000};if(m.includes("paused"))return{kind:"paused",ms:10*60_000};if(m.includes("retired")||m.includes("model_not_found"))return{kind:"retired",ms:60*60_000};if(m.includes("401")||m.includes("sign in")||m.includes("unauthorized"))return{kind:"auth",ms:30*60_000};if(m.includes("402")||m.includes("credits"))return{kind:"credits",ms:60*60_000};if(m.includes("timeout")||m.includes("timed out"))return{kind:"timeout",ms:60_000};return{kind:"upstream",ms:30_000};}
function fail(id:string,e:unknown){const message=String((e as Error)?.message||e),c=classify(message);cooldownUntil.set(id,Date.now()+c.ms);lastFailure.set(id,{at:new Date().toISOString(),kind:c.kind,message:message.slice(0,500)});return{kind:c.kind,message};}function available(id:string){return(cooldownUntil.get(id)||0)<=Date.now();}
async function invokeSse(p:Peer,prompt:string){const submit=await fetch(`${p.base}/gradio_api/call/${encodeURIComponent(p.api)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data:p.buildData(prompt)}),signal:AbortSignal.timeout(20_000)});const st=await submit.text();if(!submit.ok)throw new Error(`submit_${submit.status}:${st.slice(0,240)}`);let id="";try{id=String(JSON.parse(st)?.event_id||"");}catch(_){}if(!id)throw new Error("missing_event_id");const r=await fetch(`${p.base}/gradio_api/call/${encodeURIComponent(p.api)}/${encodeURIComponent(id)}`,{headers:{accept:"text/event-stream"},signal:AbortSignal.timeout(95_000)});const s=await r.text();if(!r.ok)throw new Error(`result_${r.status}:${s.slice(0,240)}`);const x=parseSse(s);if(x.terminal?.event==="error")throw new Error(`gradio_error:${JSON.stringify(x.terminal.data).slice(0,500)}`);const d=x.terminal?.data;const raw=Array.isArray(d)?String(d[0]??""):String(d??"");if(!raw.trim())throw new Error("empty_model_response");return{raw,event_count:x.events.length};}
async function invokeLegacy(p:Peer,prompt:string){const session=`metaengine-${crypto.randomUUID()}`;let raw="";for(let i=0;i<96;i++){const r=await fetch(`${p.base}/api/predict`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data:p.buildData(prompt),fn_index:1,session_hash:session}),signal:AbortSignal.timeout(15_000)});const body=await r.text();if(!r.ok)throw new Error(`legacy_${r.status}:${body.slice(0,240)}`);const j=JSON.parse(body);raw=String(j?.data?.[0]??raw);if(j?.is_generating!==true)return{raw,event_count:i+1};}throw new Error("legacy_iteration_limit");}
async function invokePeer(p:Peer,prompt:string){if(!available(p.id))throw Object.assign(new Error(`cooldown_until_${new Date(cooldownUntil.get(p.id)||0).toISOString()}`),{kind:"cooldown"});const started=Date.now();try{const result=p.transport==="gradio3_iter"?await invokeLegacy(p,prompt):await invokeSse(p,prompt);const n=normalize(result.raw);cooldownUntil.delete(p.id);lastFailure.delete(p.id);return{ok:true,model:p.id,served_model:p.served_model,family:p.family,text:n.text,normalization:n.normalization,raw_chars:result.raw.length,latency_ms:Date.now()-started,event_count:result.event_count};}catch(e){const c=fail(p.id,e);throw Object.assign(new Error(c.message),{kind:c.kind});}}
async function committee(prompt:string){const start=Date.now(),ids=PRIMARY.filter(available),settled=await Promise.allSettled(ids.map(id=>invokePeer(PEERS[id],prompt))),results:any[]=[];settled.forEach((r,i)=>results.push(r.status==="fulfilled"?r.value:{ok:false,model:ids[i],error_kind:(r.reason as any)?.kind||"upstream",error:String(r.reason?.message||r.reason)}));let successes=results.filter(x=>x.ok).length;const used:string[]=[];for(const id of BACKUPS){if(successes>=2)break;if(!available(id))continue;used.push(id);try{results.push(await invokePeer(PEERS[id],prompt));successes++;}catch(e){results.push({ok:false,model:id,error_kind:(e as any)?.kind||"upstream",error:String((e as Error)?.message||e)});}}return{ok:successes>=2,quorum:`${successes}/2`,success_count:successes,attempted:results.length,primary:PRIMARY,backups_used:used,agreement:analyzeAgreement(results),results,latency_ms:Date.now()-start};}
async function input(req:Request){const u=new URL(req.url);let b:any={};if(req.method==="POST")b=await req.json().catch(()=>({}));const g=(k:string)=>b?.[k]??u.searchParams.get(k);return{action:String(g("action")||"models"),model:String(g("model")||""),prompt:String(g("prompt")||"").slice(0,8000)};}
Deno.serve(async req=>{if(!auth(req))return out(401,{ok:false,error:"unauthorized"});const{action,model,prompt}=await input(req);if(action==="models"||action==="status")return out(200,{ok:true,schema:"metaengine.live-peer-broker.v6",default_committee:{primary:PRIMARY,backups:BACKUPS},agreement_policy:{signals:["exact_match","numeric_match","divergent","insufficient"],truth_claimed:false,semantic_consensus:null,requires_supervisor_judgment:true},models:Object.values(PEERS).map(p=>({id:p.id,served_model:p.served_model,family:p.family,quality:p.quality,availability:p.availability,transport:p.transport,reservation_hint_seconds:p.reservation_hint_seconds,in_cooldown:!available(p.id),cooldown_until:cooldownUntil.get(p.id)?new Date(cooldownUntil.get(p.id)!).toISOString():null,last_failure:lastFailure.get(p.id)||null}))});if(!prompt.trim())return out(400,{ok:false,error:"prompt_required"});if(action==="chat"){if(model==="auto"||!model){for(const id of [...PRIMARY,...BACKUPS]){if(!available(id))continue;try{return out(200,{...(await invokePeer(PEERS[id],prompt)),auto_selected:true});}catch(_){}}return out(503,{ok:false,error:"no_peer_available"});}const p=PEERS[model];if(!p)return out(400,{ok:false,error:"unknown_model",available:Object.keys(PEERS)});try{return out(200,await invokePeer(p,prompt));}catch(e){return out(502,{ok:false,model,error_kind:(e as any)?.kind||"upstream",error:String((e as Error)?.message||e)});}}if(action==="committee"){const r=await committee(prompt);return out(r.ok?200:503,r);}return out(404,{ok:false,error:"unknown_action"});});
