import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const CLIENT_MARKER="metaengine-supervisor-v1";
const H={"content-type":"application/json; charset=utf-8","cache-control":"no-store"};
type Peer={id:string;served_model:string;family:string;quality:string;availability:string;structured_capable:boolean;quorum_eligible:boolean;reservation_hint_seconds:number|null;min_output_tokens:number;default_max_tokens:number;max_tokens_cap:number;base:string;api:string;transport:"gradio_sse"|"gradio3_iter";buildData:(prompt:string,maxTokens:number)=>unknown[]};
type PeerResult={ok:true;model:string;served_model:string;family:string;text:string;normalization:string;raw_chars:number;latency_ms:number;event_count:number;max_output_tokens:number;completion_qualified:boolean};
const PEERS:Record<string,Peer>={
 gemma2:{id:"gemma2",served_model:"google/gemma-2-2b-it",family:"google-gemma",quality:"fast",availability:"zerogpu",structured_capable:true,quorum_eligible:true,reservation_hint_seconds:60,min_output_tokens:16,default_max_tokens:96,max_tokens_cap:384,base:"https://huggingface-projects-gemma-2-2b-it.hf.space",api:"generate",transport:"gradio_sse",buildData:(p,m)=>[p,[],m,0.2,0.9,50,1.1]},
 llama32:{id:"llama32",served_model:"meta-llama/Llama-3.2-3B-Instruct",family:"meta-llama-3.2",quality:"structured",availability:"zerogpu",structured_capable:true,quorum_eligible:true,reservation_hint_seconds:90,min_output_tokens:16,default_max_tokens:256,max_tokens_cap:512,base:"https://huggingface-projects-llama-3-2-3b-instruct.hf.space",api:"generate",transport:"gradio_sse",buildData:(p,m)=>[p,m,0.2,0.9,50,1.1]},
 nemotron:{id:"nemotron",served_model:"nvidia/NVIDIA-Nemotron-3.5-Lightning-30B-A3B-BF16",family:"nvidia-nemotron",quality:"strong-advisory",availability:"zerogpu",structured_capable:false,quorum_eligible:true,reservation_hint_seconds:null,min_output_tokens:64,default_max_tokens:160,max_tokens_cap:384,base:"https://akhaliq-nvidia-nemotron-3-5-lightning-30b-a3b-bf16.hf.space",api:"respond",transport:"gradio_sse",buildData:(p,m)=>[p,[],m,0.2,0.95,false]},
 tinyllama:{id:"tinyllama",served_model:"PY007/TinyLlama-1.1B-Chat-v0.2-GGUF",family:"tinyllama",quality:"availability-only",availability:"always-on-cpu",structured_capable:false,quorum_eligible:false,reservation_hint_seconds:0,min_output_tokens:1,default_max_tokens:64,max_tokens_cap:256,base:"https://kirp-tinyllama-chat.hf.space",api:"predict",transport:"gradio3_iter",buildData:(p,m)=>[p,0.1,1.0,50,m]},
 llama2:{id:"llama2",served_model:"meta-llama/Llama-2-13b-chat-hf",family:"meta-llama",quality:"medium",availability:"zerogpu-backup",structured_capable:false,quorum_eligible:true,reservation_hint_seconds:90,min_output_tokens:16,default_max_tokens:96,max_tokens_cap:384,base:"https://huggingface-projects-llama-2-13b-chat.hf.space",api:"generate",transport:"gradio_sse",buildData:(p,m)=>[p,[],"You are a concise helpful assistant.",m,0.2,0.9,50,1.1]},
};
const ADVISORY_PRIMARY=["gemma2","nemotron"],ADVISORY_BACKUPS=["llama32","llama2"],AUTO_POOL=["gemma2","nemotron","llama32","tinyllama","llama2"],STRUCTURED_PRIMARY=["gemma2","llama32"];
const cooldownUntil=new Map<string,number>(),lastFailure=new Map<string,{at:string;kind:string;message:string}>();
function out(s:number,b:unknown){return new Response(JSON.stringify(b),{status:s,headers:H});}
function auth(r:Request){return r.headers.get("x-metaengine-client")===CLIENT_MARKER||(r.headers.get("authorization")||"")===`Bearer ${CLIENT_MARKER}`;}
function parseSse(t:string){const e:Array<{event:string;data:unknown}>=[];let current="message";for(const raw of t.split(/\r?\n/)){const line=raw.trimEnd();if(line.startsWith("event:")){current=line.slice(6).trim();continue;}if(line.startsWith("data:")){const p=line.slice(5).trim();let d:unknown=p;try{d=JSON.parse(p);}catch{}e.push({event:current,data:d});}}return{events:e,terminal:[...e].reverse().find(x=>x.event==="complete"||x.event==="error")??e.at(-1)??null};}
function normalize(raw:string){const v=raw.trim(),i=v.lastIndexOf("</think>");if(i>=0&&v.slice(i+8).trim())return{text:v.slice(i+8).trim(),normalization:"after_think_end"};const f=v.match(/<final>([\s\S]*?)<\/final>/i);if(f?.[1]?.trim())return{text:f[1].trim(),normalization:"final_tag"};return{text:v,normalization:"none"};}
function incompleteReasoning(p:Peer,raw:string,n:string){if(p.id!=="nemotron"||n!=="none")return false;const v=raw.trim(),end=v.lastIndexOf("</think>"),hasThinkFinal=end>=0&&Boolean(v.slice(end+8).trim()),hasFinalTag=/<final>[\s\S]+<\/final>/i.test(v);return !hasThinkFinal&&!hasFinalTag&&v.length>180&&(/^(?:here(?:'|’)s a thinking process:|<think>)/i.test(v)||/\*\*analy(?:ze|sis)|\*\*identify|\*\*apply the rules|\*\*perform calculation/i.test(v));}
function extractJsonEnvelope(text:string){const v=text.trim().replace(/^```(?:json|javascript|python)?\s*/i,"").replace(/\s*```$/i,"");try{const p=JSON.parse(v);if(p&&typeof p==="object"&&!Array.isArray(p))return{text:JSON.stringify(p),normalization:"json_exact"};}catch{}for(let s=0;s<v.length;s++){if(v[s]!=="{")continue;let d=0,str=false,esc=false;for(let i=s;i<v.length;i++){const c=v[i];if(str){if(esc){esc=false;continue;}if(c==="\\"){esc=true;continue;}if(c==='"')str=false;continue;}if(c==='"'){str=true;continue;}if(c==="{")d++;else if(c==="}"&&--d===0){const candidate=v.slice(s,i+1);try{const p=JSON.parse(candidate);if(p&&typeof p==="object"&&!Array.isArray(p))return{text:JSON.stringify(p),normalization:"json_embedded"};}catch{}break;}}}return null;}
function enforceJsonEnvelope(r:PeerResult){const x=extractJsonEnvelope(r.text);if(!x)throw Object.assign(new Error("structured_json_missing"),{kind:"structured"});return{...r,text:x.text,normalization:x.normalization};}
function comparableText(v:string){return v.normalize("NFKC").trim().replace(/\s+/g," ").toLowerCase();}
function comparableNumber(v:string){const s=v.normalize("NFKC").trim().replace(/,/g,"");if(!/^[+-]?(?:\d+(?:\.\d+)?|\.\d+)$/.test(s))return null;const n=Number(s);return Number.isFinite(n)?(Object.is(n,-0)?"0":String(n)):null;}
function largest(g:Map<string,string[]>){return[...g.entries()].sort((a,b)=>b[1].length-a[1].length||a[0].localeCompare(b[0]))[0]??null;}
function agreement(results:any[]){const ok=results.filter(x=>x?.ok===true&&PEERS[x.model]?.quorum_eligible&&typeof x.text==="string");const base={evaluated:ok.length>=2,successful_responses:ok.length,truth_claimed:false,semantic_consensus:null,requires_supervisor_judgment:true};if(ok.length<2)return{...base,signal:"insufficient",unanimous:false,divergence_detected:false,matched_models:[],candidate:null,agreement_ratio:ok.length?1:0};const ex=new Map<string,string[]>(),nu=new Map<string,string[]>();for(const r of ok){const e=comparableText(r.text);ex.set(e,[...(ex.get(e)||[]),r.model]);const n=comparableNumber(r.text);if(n!==null)nu.set(n,[...(nu.get(n)||[]),r.model]);}const a=largest(ex),b=largest(nu);let signal="divergent",cluster:([string,string[]]|null)=null,candidate:string|null=null;if(a&&a[1].length>=2){signal="exact_match";cluster=a;candidate=ok.find(x=>comparableText(x.text)===a[0])?.text?.trim()??a[0];}else if(b&&b[1].length>=2){signal="numeric_match";cluster=b;candidate=b[0];}const size=cluster?.[1].length??1;return{...base,signal,unanimous:size===ok.length&&signal!=="divergent",divergence_detected:size<ok.length,matched_models:cluster?.[1]??[],candidate,agreement_ratio:size/ok.length};}
function classify(m0:string){const m=m0.toLowerCase();if(m.includes("incomplete_generation"))return{kind:"incomplete",ms:15_000};if(m.includes("quota")||m.includes("try again in"))return{kind:"quota",ms:30*60_000};if(m.includes("paused"))return{kind:"paused",ms:10*60_000};if(m.includes("retired")||m.includes("model_not_found"))return{kind:"retired",ms:60*60_000};if(m.includes("401")||m.includes("sign in")||m.includes("unauthorized"))return{kind:"auth",ms:30*60_000};if(m.includes("402")||m.includes("credits"))return{kind:"credits",ms:60*60_000};if(m.includes("timeout")||m.includes("timed out"))return{kind:"timeout",ms:60_000};return{kind:"upstream",ms:30_000};}
function fail(id:string,e:unknown){const message=String((e as Error)?.message||e),c=classify(message);cooldownUntil.set(id,Date.now()+c.ms);lastFailure.set(id,{at:new Date().toISOString(),kind:c.kind,message:message.slice(0,500)});return{kind:c.kind,message};}
function available(id:string){return(cooldownUntil.get(id)||0)<=Date.now();}
function tokenBudget(p:Peer,x:unknown){const n=Number(x);return Number.isFinite(n)?Math.max(p.min_output_tokens,Math.min(p.max_tokens_cap,Math.trunc(n))):p.default_max_tokens;}
function resolvePeer(raw:string){const n=(raw||"auto").replace(/^metaengine\//,"");if(n==="auto"||n==="structured-auto")return null;return PEERS[n]||Object.values(PEERS).find(p=>p.served_model===raw);}
function contentText(c:unknown):string{if(typeof c==="string")return c;if(Array.isArray(c))return c.map(x=>x&&typeof x==="object"&&!Array.isArray(x)&&typeof (x as any).text==="string"?(x as any).text:"").filter(Boolean).join("\n");return String(c??"");}
function messagesToPrompt(m:unknown){if(!Array.isArray(m))throw Object.assign(new Error("messages_array_required"),{kind:"request"});const a:string[]=[];for(const x of m){if(!x||typeof x!=="object"||Array.isArray(x))continue;const t=contentText((x as any).content).trim();if(t)a.push(`${String((x as any).role||"user").toUpperCase()}:\n${t}`);}if(!a.length)throw Object.assign(new Error("messages_content_required"),{kind:"request"});return a.join("\n\n");}
function expectsJson(b:any,p:string){return b?.response_format?.type==="json_object"||/\bjson object\b/i.test(p)||/return exactly one json/i.test(p);}
async function invokeSse(p:Peer,prompt:string,max:number){const s=await fetch(`${p.base}/gradio_api/call/${encodeURIComponent(p.api)}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data:p.buildData(prompt,max)}),signal:AbortSignal.timeout(20_000)}),st=await s.text();if(!s.ok)throw new Error(`submit_${s.status}:${st.slice(0,240)}`);let id="";try{id=String(JSON.parse(st)?.event_id||"");}catch{}if(!id)throw new Error("missing_event_id");const r=await fetch(`${p.base}/gradio_api/call/${encodeURIComponent(p.api)}/${encodeURIComponent(id)}`,{headers:{accept:"text/event-stream"},signal:AbortSignal.timeout(95_000)}),text=await r.text();if(!r.ok)throw new Error(`result_${r.status}:${text.slice(0,240)}`);const x=parseSse(text);if(x.terminal?.event==="error")throw new Error(`gradio_error:${JSON.stringify(x.terminal.data).slice(0,500)}`);const d=x.terminal?.data,raw=Array.isArray(d)?String(d[0]??""):String(d??"");if(!raw.trim())throw new Error("empty_model_response");return{raw,event_count:x.events.length};}
async function invokeLegacy(p:Peer,prompt:string,max:number){const session=`metaengine-${crypto.randomUUID()}`;let raw="";for(let i=0;i<96;i++){const r=await fetch(`${p.base}/api/predict`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({data:p.buildData(prompt,max),fn_index:1,session_hash:session}),signal:AbortSignal.timeout(15_000)}),body=await r.text();if(!r.ok)throw new Error(`legacy_${r.status}:${body.slice(0,240)}`);const j=JSON.parse(body);raw=String(j?.data?.[0]??raw);if(j?.is_generating!==true)return{raw,event_count:i+1};}throw new Error("legacy_iteration_limit");}
async function invokePeer(p:Peer,prompt:string,requested?:unknown):Promise<PeerResult>{if(!p)throw Object.assign(new Error("unknown_model"),{kind:"request"});if(!available(p.id))throw Object.assign(new Error("peer_cooldown"),{kind:"cooldown"});const started=Date.now(),max=tokenBudget(p,requested);try{const x=p.transport==="gradio3_iter"?await invokeLegacy(p,prompt,max):await invokeSse(p,prompt,max),n=normalize(x.raw);if(incompleteReasoning(p,x.raw,n.normalization))throw new Error("incomplete_generation:reasoning_without_final");cooldownUntil.delete(p.id);lastFailure.delete(p.id);return{ok:true,model:p.id,served_model:p.served_model,family:p.family,text:n.text,normalization:n.normalization,raw_chars:x.raw.length,latency_ms:Date.now()-started,event_count:x.event_count,max_output_tokens:max,completion_qualified:true};}catch(e){const c=fail(p.id,e);throw Object.assign(new Error(c.message),{kind:c.kind});}}
async function invokeIndependentAnswer(p:Peer,prompt:string,requested?:unknown){const wrapped=`Solve the task independently. Return exactly one JSON object with one key named answer. The value must be only your final answer, with no explanation.\n\nTASK:\n${prompt}`;const r=enforceJsonEnvelope(await invokePeer(p,wrapped,Math.max(128,Number(requested)||0)));const parsed=JSON.parse(r.text);if(parsed===null||typeof parsed!=="object"||Array.isArray(parsed)||!("answer" in parsed))throw Object.assign(new Error("structured_answer_missing"),{kind:"structured"});return{...r,text:String(parsed.answer),normalization:"json_answer"};}
async function invokeAuto(pool:string[],prompt:string,t?:unknown){for(const id of pool){if(!available(id))continue;try{return await invokePeer(PEERS[id],prompt,t);}catch{}}throw Object.assign(new Error("no_peer_available"),{kind:"unavailable"});}
async function invokeStructuredAuto(prompt:string,t?:unknown){let last:unknown=null;for(const id of STRUCTURED_PRIMARY){if(!available(id))continue;try{return enforceJsonEnvelope(await invokePeer(PEERS[id],prompt,t));}catch(e){last=e;}}throw Object.assign(new Error(String((last as Error)?.message||last||"no_structured_peer_available")),{kind:(last as any)?.kind||"unavailable"});}
async function committee(prompt:string,t:unknown,structured:boolean){const primary=structured?STRUCTURED_PRIMARY:ADVISORY_PRIMARY,backups=structured?[]:ADVISORY_BACKUPS,start=Date.now(),ids=primary.filter(available),settled=await Promise.allSettled(ids.map(id=>invokePeer(PEERS[id],prompt,t))),results:any[]=[];settled.forEach((r,i)=>results.push(r.status==="fulfilled"?r.value:{ok:false,model:ids[i],error_kind:(r.reason as any)?.kind||"upstream",error:String(r.reason?.message||r.reason)}));let successes=results.filter(x=>x.ok&&PEERS[x.model]?.quorum_eligible).length;const used:string[]=[];for(const id of backups){if(successes>=2)break;if(!available(id))continue;used.push(id);try{const r=id==="llama32"&&!structured?await invokeIndependentAnswer(PEERS[id],prompt,t):await invokePeer(PEERS[id],prompt,t);results.push(r);if(PEERS[id].quorum_eligible)successes++;}catch(e){results.push({ok:false,model:id,error_kind:(e as any)?.kind||"upstream",error:String((e as Error)?.message||e)});}}const a=agreement(results),availability=successes>=2,decision=a.signal==="exact_match"||a.signal==="numeric_match"?"AGREED":a.signal==="divergent"?"DIVERGENT":"INSUFFICIENT";return{ok:availability,availability_quorum_met:availability,decision_state:decision,answer_candidate:decision==="AGREED"?a.candidate:null,mode:structured?"structured":"advisory",quorum:`${successes}/2`,eligible_success_count:successes,transport_success_count:results.filter(x=>x.ok).length,attempted:results.length,primary,backups_used:used,agreement:a,results,latency_ms:Date.now()-start};}
function openAiResponse(r:PeerResult,logical:string){return{id:`chatcmpl-metaengine-${crypto.randomUUID()}`,object:"chat.completion",created:Math.floor(Date.now()/1000),model:r.served_model,choices:[{index:0,message:{role:"assistant",content:r.text},finish_reason:"stop"}],metaengine:{peer_id:r.model,logical_model:logical,upstream_served_model:r.served_model,family:r.family,normalization:r.normalization,completion_qualified:r.completion_qualified,latency_ms:r.latency_ms,max_output_tokens:r.max_output_tokens,tariff_dependency:true,zero_spend_verified:null,data_policy:"PUBLIC_EXTERNAL_HUGGINGFACE_SPACE",confidential_data_supported:false,authority_effect:false}};}
async function handleOpenAi(b:any){const logical=String(b?.model||"metaengine/structured-auto"),prompt=messagesToPrompt(b?.messages),wantJson=logical==="metaengine/structured-auto"||expectsJson(b,prompt);if(logical==="metaengine/structured-auto"||(logical==="metaengine/auto"&&wantJson))return openAiResponse(await invokeStructuredAuto(prompt,b?.max_tokens),logical);if(logical==="metaengine/auto")return openAiResponse(await invokeAuto(AUTO_POOL,prompt,b?.max_tokens),logical);const p=resolvePeer(logical);if(!p)throw Object.assign(new Error("unknown_model"),{kind:"request"});if(wantJson&&!p.structured_capable)throw Object.assign(new Error("model_not_structured_capable"),{kind:"request"});let r=await invokePeer(p,prompt,b?.max_tokens);if(wantJson)r=enforceJsonEnvelope(r);return openAiResponse(r,logical);}
Deno.serve(async req=>{if(!auth(req))return out(401,{ok:false,error:"unauthorized"});const u=new URL(req.url),body=req.method==="POST"?await req.json().catch(()=>({})):{};if(u.pathname.endsWith("/v1/chat/completions")){try{return out(200,await handleOpenAi(body));}catch(e){const k=(e as any)?.kind;return out(k==="request"?400:k==="structured"?422:502,{error:{message:String((e as Error)?.message||e),type:"metaengine_peer_error",kind:k}});}}const g=(k:string)=>body?.[k]??u.searchParams.get(k),action=String(g("action")||"models"),model=String(g("model")||""),prompt=String(g("prompt")||"").slice(0,8000),maxTokens=g("max_tokens");if(action==="models"||action==="status")return out(200,{ok:true,schema:"metaengine.live-peer-broker.v12",openai_compatible:true,completion_policy:{nemotron_requires_nonempty_final_after_think:true},quorum_policy:{availability_quorum_separate_from_answer_agreement:true,availability_only_peers_excluded:true},advisory_committee:{primary:ADVISORY_PRIMARY,backups:ADVISORY_BACKUPS},structured_committee:{primary:STRUCTURED_PRIMARY,backups:[]},models:Object.values(PEERS).map(p=>({id:p.id,served_model:p.served_model,family:p.family,quality:p.quality,availability:p.availability,structured_capable:p.structured_capable,quorum_eligible:p.quorum_eligible,min_output_tokens:p.min_output_tokens,in_cooldown:!available(p.id),last_failure:lastFailure.get(p.id)||null}))});if(!prompt.trim())return out(400,{ok:false,error:"prompt_required"});if(action==="chat"){try{const r=model==="structured-auto"?await invokeStructuredAuto(prompt,maxTokens):model==="auto"||!model?await invokeAuto(AUTO_POOL,prompt,maxTokens):await invokePeer(resolvePeer(model)!,prompt,maxTokens);return out(200,r);}catch(e){return out(502,{ok:false,model,error_kind:(e as any)?.kind||"upstream",error:String((e as Error)?.message||e)});}}if(action==="committee"||action==="structured_committee"){const r=await committee(prompt,maxTokens,action==="structured_committee");return out(r.ok?200:503,r);}return out(404,{ok:false,error:"unknown_action"});});
