const SUPABASE_URL=(Deno.env.get('SUPABASE_URL')||'').replace(/\/+$/,'');
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const PAIRING_TABLE='compute_fabric_a2_chat_bridge_remote_pairing_h205f22';
const DEVICE_TABLE='compute_fabric_a2_browser_device_h205f22';
const ENROLL_RPC='h205f22_a2_browser_device_enroll_v1';
const NONCE_RPC='h205f22_a2_browser_device_consume_nonce_v2';
const PROFILE='A2_DEVICE_HTTP_SIGNATURE_V1';
const MAX_SKEW_MS=120000;
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const B64URL_RE=/^[A-Za-z0-9_-]+$/;
const HEX64_RE=/^[0-9a-f]{64}$/;
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-a2-chat-bridge-secret,x-a2-chat-bridge-client,x-a2-device-profile,x-a2-device-id,x-a2-device-timestamp,x-a2-device-nonce,x-a2-device-body-sha256,x-a2-device-signature','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'};
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json; charset=utf-8'}})}
async function sha256(v:unknown){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v??'')));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function restHeaders(extra:Record<string,string>={}){if(!SERVICE_ROLE)throw new Error('service_role_missing');return{apikey:SERVICE_ROLE,authorization:`Bearer ${SERVICE_ROLE}`,'content-type':'application/json',...extra}}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:restHeaders(init.headers as Record<string,string>||{})});const text=await r.text();if(!r.ok)throw new Error(`rest_${r.status}`);return text?JSON.parse(text):null}
async function rpc(name:string,args:unknown){return rest(`rpc/${encodeURIComponent(name)}`,{method:'POST',body:JSON.stringify(args)})}
function requestPath(req:Request){const p=new URL(req.url).pathname;const marker='/a2-browser-device-auth-v2-canary';const i=p.indexOf(marker);return i>=0?(p.slice(i+marker.length)||'/'):p}
async function pairingHash(req:Request){const token=String(req.headers.get('x-a2-chat-bridge-secret')||'');if(token.length<32)return null;const hash=await sha256(token);const rows=await rest(`${PAIRING_TABLE}?token_hash=eq.${hash}&active=eq.true&select=token_hash&limit=1`);return Array.isArray(rows)&&rows.length===1?hash:null}
function clientId(req:Request){const v=String(req.headers.get('x-a2-chat-bridge-client')||'').trim().slice(0,161);return v.length>=1&&v.length<=160?v:null}
function validateJwk(v:any){if(!v||typeof v!=='object'||Array.isArray(v)||v.kty!=='EC'||v.crv!=='P-256'||typeof v.x!=='string'||typeof v.y!=='string'||v.x.length!==43||v.y.length!==43||!B64URL_RE.test(v.x)||!B64URL_RE.test(v.y)||'d'in v)throw new Error('device_public_jwk_invalid');return{kty:'EC',crv:'P-256',x:v.x,y:v.y,key_ops:['verify'],ext:true}}
async function enroll(req:Request){const tokenHash=await pairingHash(req);if(!tokenHash)return json(401,{error:'bridge_pairing_required'});const client=clientId(req);if(!client)return json(400,{error:'device_client_invalid'});const body=await req.json().catch(()=>({}));if(body?.profile!==PROFILE)return json(400,{error:'device_profile_invalid'});let jwk;try{jwk=validateJwk(body?.public_jwk)}catch(e){return json(400,{error:String((e as Error)?.message||e)})}const fp=await sha256(JSON.stringify({kty:jwk.kty,crv:jwk.crv,x:jwk.x,y:jwk.y}));const out=await rpc(ENROLL_RPC,{p_client_id:client,p_profile:PROFILE,p_public_jwk:jwk,p_key_fingerprint_sha256:fp,p_pairing_token_hash:tokenHash});if(out?.accepted!==true)return json(409,{error:'device_enrollment_rejected',reason:out?.reason||'UNKNOWN'});return json(201,{device_id:out.device_id,profile:out.profile||PROFILE,enrolled_at:out.enrolled_at||null,key_fingerprint_sha256:out.key_fingerprint_sha256||fp,reason:out.reason,authority_effect:false})}
function fromB64url(v:string){const t=v.replace(/-/g,'+').replace(/_/g,'/');const p=t+'='.repeat((4-(t.length%4||4))%4);const b=atob(p);return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function authenticateSigned(req:Request,path:string,bodyText:string){const profile=String(req.headers.get('x-a2-device-profile')||'');const deviceId=String(req.headers.get('x-a2-device-id')||'');const timestamp=String(req.headers.get('x-a2-device-timestamp')||'');const nonce=String(req.headers.get('x-a2-device-nonce')||'');const claimed=String(req.headers.get('x-a2-device-body-sha256')||'').toLowerCase();const sig=String(req.headers.get('x-a2-device-signature')||'');const client=clientId(req);if(profile!==PROFILE||!client||!UUID_RE.test(deviceId)||!HEX64_RE.test(claimed)||nonce.length<16||nonce.length>96||!B64URL_RE.test(nonce)||sig.length<64||sig.length>256||!B64URL_RE.test(sig))return{ok:false,reason:'SIGNED_HEADERS_INVALID'};const ts=Date.parse(timestamp);if(!Number.isFinite(ts)||Math.abs(Date.now()-ts)>MAX_SKEW_MS)return{ok:false,reason:'SIGNED_TIMESTAMP_INVALID'};const bodyHash=await sha256(bodyText);if(bodyHash!==claimed)return{ok:false,reason:'SIGNED_BODY_HASH_MISMATCH'};const rows=await rest(`${DEVICE_TABLE}?device_id=eq.${deviceId}&active=eq.true&select=device_id,client_id,profile,public_jwk,revoked_at&limit=1`);const row=Array.isArray(rows)?rows[0]:null;if(!row||row.client_id!==client||row.profile!==PROFILE||row.revoked_at)return{ok:false,reason:'SIGNED_DEVICE_INVALID'};const material=[PROFILE,`device_id:${deviceId}`,`method:${req.method.toUpperCase()}`,`path:${path}`,`timestamp:${timestamp}`,`nonce:${nonce}`,`body_sha256:${bodyHash}`].join('\n');let key;try{key=await crypto.subtle.importKey('jwk',row.public_jwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify'])}catch(_){return{ok:false,reason:'SIGNED_PUBLIC_KEY_INVALID'}}let signature;try{signature=fromB64url(sig)}catch(_){return{ok:false,reason:'SIGNED_SIGNATURE_ENCODING'}}const verified=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,signature,new TextEncoder().encode(material));if(!verified)return{ok:false,reason:'SIGNED_SIGNATURE_REJECTED'};const consumed=await rpc(NONCE_RPC,{p_device_id:deviceId,p_client_id:client,p_nonce_sha256:await sha256(nonce),p_request_timestamp:timestamp});if(consumed?.accepted!==true)return{ok:false,reason:String(consumed?.reason||'NONCE_REJECTED')};return{ok:true,device_id:deviceId,client_id:client,profile:PROFILE}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const path=requestPath(req);try{if(req.method==='GET'&&path==='/health')return json(200,{ok:true,schema:'metaengine.a2-browser-device-auth.canary.v2',profile:PROFILE,enroll_rpc:ENROLL_RPC,replay_fence:NONCE_RPC});if(req.method==='POST'&&path==='/v1/device/enroll')return enroll(req);const bodyText=req.method==='GET'?'':await req.text();const auth=await authenticateSigned(req,path,bodyText);if(!auth.ok)return json(401,{error:'device_signature_required',reason:auth.reason});if(req.method==='POST'&&path==='/v1/device/verify')return json(200,{ok:true,authenticated:true,device_id:auth.device_id,client_id:auth.client_id,profile:PROFILE,authority_effect:false});return json(404,{error:'not_found'})}catch(e){console.error('a2_device_auth_v2_failure',String((e as Error)?.message||e));return json(502,{error:'device_auth_v2_failure'})}});
