import test from "node:test";
import assert from "node:assert/strict";
import { generateKeyPairSync, sign, createHash } from "node:crypto";
import { INGRESS_VERIFIER_ID, PriorityInbox, exactModel, peerOf, mandatoryPeerHashes, causalParents, isActionConflict, verifyEd25519RawPublicKey, deriveFrontierHash, createVerifiedIngressReceipt, ingressReceiptMessage, ingressSignatureSha256, ingressReceiptMessageV2, peerReceiptBatches, spanIdForAction, traceIdForRound, traceparent, type A2Event } from "./a2_protocol.js";

function ev(n:number,agent:"GPT"|"GLM",priority:0|1|2|3=2,type="CLAIM",action="A"):A2Event{return{event_id:`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`,commit_seq:n,workspace_id:"00000000-0000-4000-8000-000000000999",session_id:"00000000-0000-4000-8000-000000000998",agent,agent_seq:n,semantic_point:"X",event_type:type,priority,parent_hashes:[],payload:{proposed_action:{kind:action}},payload_sha256:"a".repeat(64),event_hash:createHash("sha256").update(String(n)).digest("hex"),signature_key_fingerprint_sha256:"b".repeat(64)};}

test("exact model identities are immutable",()=>{assert.equal(exactModel("GPT"),"openai/gpt-5.6-sol");assert.equal(exactModel("GLM"),"zai/glm-5.3");assert.equal(peerOf("GPT"),"GLM");});
test("mandatory peer hashes only include unseen P0/P1",()=>{const es=[ev(1,"GPT",0),ev(2,"GLM",2),ev(3,"GLM",1)];assert.deepEqual(mandatoryPeerHashes("GPT",es,1),[es[2].event_hash]);});
test("causal parents include latest own and peer",()=>{const es=[ev(1,"GPT"),ev(2,"GLM"),ev(3,"GPT")];assert.deepEqual(causalParents("GPT",es).sort(),[es[2].event_hash,es[1].event_hash].sort());});
test("action conflict requires distinct agents and action kinds",()=>{assert.equal(isActionConflict(ev(1,"GPT",2,"ACTION_PROPOSAL","A"),ev(2,"GLM",2,"ACTION_PROPOSAL","B")),true);assert.equal(isActionConflict(ev(1,"GPT",2,"ACTION_PROPOSAL","A"),ev(2,"GLM",2,"ACTION_PROPOSAL","A")),false);});
test("P0/P1 never silently evicted",()=>{const q=new PriorityInbox(8);for(let i=1;i<=8;i++)q.push(ev(i,"GPT",2));assert.throws(()=>q.push(ev(9,"GLM",0)),/fail_closed/);});
test("P2 never silently drops behind an all-mandatory queue",()=>{const q=new PriorityInbox(8);for(let i=1;i<=8;i++)q.push(ev(i,"GPT",1));assert.throws(()=>q.push(ev(9,"GLM",2)),/p2_backpressure_fail_closed/);});
test("P3 can coalesce under pressure",()=>{const q=new PriorityInbox(8);for(let i=1;i<=8;i++)q.push(ev(i,"GPT",3,"MODEL_STARTED"));q.push(ev(9,"GPT",3,"MODEL_STARTED"));assert.equal(q.size,8);});
test("ed25519 raw key verification rejects forged and wrong-key signatures",()=>{const kp=generateKeyPairSync("ed25519"),wrong=generateKeyPairSync("ed25519");const raw=(kp.publicKey.export({format:"der",type:"spki"}) as Buffer).subarray(-32),wrongRaw=(wrong.publicKey.export({format:"der",type:"spki"}) as Buffer).subarray(-32);const hash=createHash("sha256").update("event").digest("hex");const sig=sign(null,Buffer.from(hash,"hex"),kp.privateKey).toString("base64");assert.equal(verifyEd25519RawPublicKey(raw.toString("base64"),hash,sig),true);assert.equal(verifyEd25519RawPublicKey(wrongRaw.toString("base64"),hash,sig),false);assert.equal(verifyEd25519RawPublicKey(raw.toString("base64"),"0".repeat(64),sig),false);});
test("trusted ingress receipt binds the exact detached signature bytes",()=>{const kp=generateKeyPairSync("ed25519"),wrong=generateKeyPairSync("ed25519");const raw=(kp.publicKey.export({format:"der",type:"spki"}) as Buffer).subarray(-32),wrongRaw=(wrong.publicKey.export({format:"der",type:"spki"}) as Buffer).subarray(-32);const eventHash=createHash("sha256").update("ingress-event").digest("hex"),signature=sign(null,Buffer.from(eventHash,"hex"),kp.privateKey).toString("base64");const common={eventHash,sessionId:"00000000-0000-4000-8000-000000000998",fingerprint:createHash("sha256").update(raw).digest("hex"),verifierId:INGRESS_VERIFIER_ID,issuedAt:new Date("2026-08-24T12:30:00.000Z"),expiresAt:new Date("2026-08-24T12:31:00.000Z"),nonce:"ab".repeat(32),signatureBase64:signature,hmacSecret:"trusted-ingress-secret-with-at-least-32-bytes"};const receipt=createVerifiedIngressReceipt({...common,rawPublicKeyBase64:raw.toString("base64")});assert.match(receipt.hmacSha256,/^[0-9a-f]{64}$/);assert.notEqual(ingressReceiptMessage(common),ingressReceiptMessage({...common,signatureBase64:Buffer.alloc(64,7).toString("base64")}));assert.throws(()=>createVerifiedIngressReceipt({...common,rawPublicKeyBase64:wrongRaw.toString("base64")}),/local_signature_verify_failed/);});
test("frontier hash deterministic independent of input order",()=>{const a=ev(1,"GPT"),b=ev(2,"GLM");assert.equal(deriveFrontierHash(a.workspace_id,[a,b]),deriveFrontierHash(a.workspace_id,[b,a]));});
test("signature-bound ingress receipt changes with detached signature",()=>{const a=Buffer.alloc(64,1).toString("base64"),b=Buffer.alloc(64,2).toString("base64");const as=ingressSignatureSha256(a),bs=ingressSignatureSha256(b);assert.notEqual(as,bs);const common={eventHash:"a".repeat(64),sessionId:"00000000-0000-4000-8000-000000000001",keyFingerprint:"b".repeat(64),issuedEpoch:"1787574000.000000",expiresEpoch:"1787574060.000000",nonce:"c".repeat(48)};const ma=ingressReceiptMessageV2({...common,signatureSha256:as}),mb=ingressReceiptMessageV2({...common,signatureSha256:bs});assert.notEqual(ma,mb);assert.match(ma,/A2_INGRESS_RECEIPT_V2/);});
test("signature digest rejects non-64-byte detached signature",()=>{assert.throws(()=>ingressSignatureSha256(Buffer.alloc(63).toString("base64")),/signature_length/);});
test("every peer action is receipted in bounded batches without receipt recursion",()=>{const events=Array.from({length:130},(_,i)=>ev(i+1,"GLM",3,i===4?"PEER_EVENT_APPLIED":"FILE_READ"));events.push(ev(131,"GPT",2,"CLAIM"));const batches=peerReceiptBatches("GPT",events);assert.deepEqual(batches.map(batch=>batch.length),[64,64,1]);assert.equal(batches.flat().some(event=>event.event_type==="PEER_EVENT_APPLIED"),false);assert.equal(batches.flat().some(event=>event.agent==="GPT"),false);});
test("round trace context is stable while action spans remain distinct",()=>{const round="00000000-0000-4000-8000-000000000111",trace=traceIdForRound(round),a=spanIdForAction("00000000-0000-4000-8000-000000000201"),b=spanIdForAction("00000000-0000-4000-8000-000000000202");assert.equal(trace.length,32);assert.notEqual(a,b);assert.equal(traceparent(trace,a),`00-${trace}-${a}-01`);assert.throws(()=>traceparent("0".repeat(32),a),/trace_id_invalid/);});
