import { randomUUID, generateKeyPairSync, createPrivateKey, createPublicKey, sign as edSign, createHash, type KeyObject } from "node:crypto";
import { exactModel, peerOf, causalParents, boundedContext, verifyEd25519RawPublicKey, type Agent, type A2Event, type Frontier } from "./a2_protocol.js";

type Json=Record<string,unknown>;
const WORKSPACE_ID=req("A2_WORKSPACE_ID");
const AGENT=(req("A2_AGENT").toUpperCase()) as Agent;if(!["GPT","GLM"].includes(AGENT))throw new Error("A2_AGENT_invalid");
const MODEL_URL=req("A2_MODEL_URL").replace(/\/$/,"");
const MODEL_TOKEN=process.env.A2_MODEL_TOKEN||"";
const MODEL=process.env.A2_MODEL||exactModel(AGENT);if(MODEL!==exactModel(AGENT))throw new Error(`exact_model_required:${exactModel(AGENT)}`);
const PROVIDER=process.env.A2_PROVIDER||(AGENT==="GPT"?"openai":"z.ai");
const RUNTIME_ID=process.env.A2_RUNTIME_ID||`a2-${AGENT.toLowerCase()}-${process.pid}`;
const EPOCH=int(process.env.A2_CAPABILITY_EPOCH,1,1,1_000_000);
const POLL_MS=int(process.env.A2_POLL_MS,250,50,5000);
const MICROSTEP_TIMEOUT=int(process.env.A2_MICROSTEP_TIMEOUT_MS,15000,1000,120000);
const TOOL_URL=(process.env.A2_TOOL_EXECUTOR_URL||"").replace(/\/$/,"");
const TOOL_TOKEN=process.env.A2_TOOL_EXECUTOR_TOKEN||"";
const INGRESS_URL=req("A2_INGRESS_URL").replace(/\/$/,"");
const INGRESS_TOKEN=process.env.A2_INGRESS_TOKEN||"";
let aborter:AbortController|null=null,proofSeenSeq=0,sessionId="",semanticPoint="",lastApplied=0,stopped=false,streamAfter=0;
const pendingMandatoryPeerHashes=new Set<string>();
const keypair=loadKey();
const publicRaw=rawPublic(keypair.publicKey),publicB64=publicRaw.toString("base64"),fingerprint=createHash("sha256").update(publicRaw).digest("hex");
const caps={reasoning_summary_stream:AGENT==="GPT",tool_calls:true,max_emit_rate_hz:4,inbound_queue_depth:200,resume_from_commit_seq:true,max_opaque_ms:MICROSTEP_TIMEOUT,trusted_ingress:"A2_TRUSTED_ED25519_INGRESS_V1",direct_database_access:false};
const PEER_RECEIPT_TYPES=new Set(["PLAN","HYPOTHESIS","CLAIM","COUNTERCLAIM","QUESTION","EVIDENCE","ASSUMPTION","FALSIFIER","CRITIQUE","AGREEMENT","SYNTHESIS","ACTION_PROPOSAL","REQUEST_DUEL","TOOL_RESULT","TOOL_ERROR","TEST_RESULT","AUTHORITY_DRIFT","CHECKPOINT","DUEL_OPENED","DUEL_DECIDED"]);

function req(n:string){const v=process.env[n];if(!v)throw new Error(`${n}_required`);return v;}
function int(v:string|undefined,f:number,min:number,max:number){const n=Number(v??f);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):f;}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
function loadKey():{privateKey:KeyObject;publicKey:KeyObject}{const b64=process.env.A2_ED25519_PRIVATE_KEY_PEM_B64;if(b64){const privateKey=createPrivateKey(Buffer.from(b64,"base64").toString("utf8"));return{privateKey,publicKey:createPublicKey(privateKey)};}return generateKeyPairSync("ed25519");}
function rawPublic(k:KeyObject){const der=k.export({format:"der",type:"spki"}) as Buffer;if(der.length<32)throw new Error("ed25519_spki_invalid");return der.subarray(der.length-32);}
function authHeaders(){return {"content-type":"application/json",...(INGRESS_TOKEN?{authorization:`Bearer ${INGRESS_TOKEN}`}:{})};}
async function peerRpc<T=any>(fn:string,args:any[]):Promise<T>{const r=await fetch(`${INGRESS_URL}/v1/a2/rpc`,{method:"POST",headers:authHeaders(),body:JSON.stringify({fn,args})});const text=await r.text();if(!r.ok)throw new Error(`a2_peer_rpc_${r.status}:${text.slice(0,700)}`);const j=JSON.parse(text);return j.value as T;}
async function getWorkspace(){const s=await peerRpc<any>("h205f22_a2_read_snapshot_v1",[WORKSPACE_ID,1]);if(!s?.workspace)throw new Error("workspace_not_found");return s.workspace;}
async function register(){const v=await peerRpc<any>("h205f22_a2_register_peer_session_v1",[WORKSPACE_ID,AGENT,RUNTIME_ID,PROVIDER,MODEL,MODEL,caps,EPOCH,publicB64]);sessionId=String(v.session_id);}
async function readEvents(after=0,limit=1000):Promise<A2Event[]>{const r=await peerRpc<any>("h205f22_a2_read_events_v1",[WORKSPACE_ID,after,limit]);return Array.isArray(r.events)?r.events:[];}
async function frontier():Promise<Frontier>{return peerRpc("h205f22_a2_read_frontier_v1",[WORKSPACE_ID]);}
async function frontierAt(through:number):Promise<Frontier>{return peerRpc("h205f22_a2_read_frontier_at_v1",[WORKSPACE_ID,through]);}
async function seq():Promise<number>{const r=await peerRpc<any>("h205f22_a2_next_agent_seq_v1",[sessionId]);return Number(r.next_agent_seq);}
async function submitIngress(body:Json):Promise<any>{const r=await fetch(`${INGRESS_URL}/v1/a2/emit`,{method:"POST",headers:authHeaders(),body:JSON.stringify(body)});const text=await r.text();if(!r.ok)throw new Error(`a2_ingress_${r.status}:${text.slice(0,700)}`);return JSON.parse(text);}
async function emitRuntime(type:string,priority:0|1|2|3,payload:Json,parents:string[]=[]):Promise<any>{return emit(type,priority,payload,parents,null);}
async function emit(type:string,priority:0|1|2|3,payload:Json,parents:string[],proofId:string|null):Promise<any>{const agentSeq=await seq();const eventId=randomUUID();const provenance={provider:PROVIDER,requested_model:MODEL,reported_model:MODEL,runtime_id:RUNTIME_ID,capability_epoch:EPOCH};const prep=await peerRpc<any>("h205f22_a2_prepare_event_v1",[eventId,sessionId,agentSeq,semanticPoint,type,priority,parents,payload,proofId,provenance]);const hash=String(prep.event_hash);const signature=edSign(null,Buffer.from(hash,"hex"),keypair.privateKey).toString("base64");if(!verifyEd25519RawPublicKey(publicB64,hash,signature))throw new Error("a2_local_signature_verify_failed");return submitIngress({event_id:eventId,session_id:sessionId,agent_seq:agentSeq,semantic_point:semanticPoint,event_type:type,priority,parent_hashes:parents,payload,visibility_proof_id:proofId,model_provenance:provenance,event_hash:hash,signature_base64:signature,signature_key_fingerprint_sha256:fingerprint});}
function receiptablePeerEvents(events:A2Event[]){return events.filter(e=>e.agent!==AGENT&&e.event_type!=="PEER_EVENT_APPLIED"&&(Number(e.priority)<=1||PEER_RECEIPT_TYPES.has(e.event_type))).slice(-64);}
async function catchUp(){const events=await readEvents(lastApplied,1000);if(!events.length)return events;const appliedThrough=Math.max(...events.map(e=>Number(e.commit_seq)));for(const e of events)if(e.agent!==AGENT&&Number(e.priority)<=1)pendingMandatoryPeerHashes.add(e.event_hash);const appliedFrontier=await frontierAt(appliedThrough);await peerRpc("h205f22_a2_update_cursor_v1",[sessionId,appliedThrough,appliedThrough,appliedFrontier.frontier_hash]);lastApplied=appliedThrough;const peer=receiptablePeerEvents(events);if(peer.length){const hashes=peer.map(e=>e.event_hash);await emitRuntime("PEER_EVENT_APPLIED",3,{receipt_policy:"BATCH_NO_RECURSION_V1",peer_agent:peerOf(AGENT),peer_event_hashes:hashes,peer_commit_seq_min:Math.min(...peer.map(e=>Number(e.commit_seq))),peer_commit_seq_max:Math.max(...peer.map(e=>Number(e.commit_seq))),applied_through_commit_seq:appliedThrough,applied_frontier_hash:appliedFrontier.frontier_hash},hashes);}return events;}
function prompt(events:A2Event[],f:Frontier){const peer=peerOf(AGENT);return `You are ${AGENT} in A2_CCP_V1 collaborating with ${peer}. Hidden chain-of-thought is not requested. Produce exactly one public engineering microstep as JSON.\nReturn: {"event_type":"PLAN|HYPOTHESIS|CLAIM|COUNTERCLAIM|QUESTION|EVIDENCE|ASSUMPTION|FALSIFIER|CRITIQUE|AGREEMENT|SYNTHESIS|ACTION_PROPOSAL|REQUEST_DUEL","priority":2,"payload":{"reasoning_summary":["..."],"claim":"...","evidence_used":[],"assumptions":[],"falsifier":"...","proposed_action":{"kind":"..."},"tool_request":{"name":"optional","arguments":{}}},"respond_to_hashes":[]}\nBe concise and causal. Do not claim tools/evidence you did not observe.\nsemantic_point=${semanticPoint}\napplied_frontier=${JSON.stringify(f)}\ncommitted_context=${JSON.stringify(boundedContext(events,80))}`;}
async function callModel(body:Json,signal:AbortSignal):Promise<any>{const r=await fetch(`${MODEL_URL}/v1/chat/completions`,{method:"POST",headers:{"content-type":"application/json",...(MODEL_TOKEN?{authorization:`Bearer ${MODEL_TOKEN}`}:{})},body:JSON.stringify(body),signal});if(!r.ok)throw new Error(`model_${r.status}:${(await r.text()).slice(0,500)}`);const j:any=await r.json();const c=j?.choices?.[0]?.message?.content;if(typeof c!=="string")throw new Error("model_content_missing");const stripped=c.trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();return JSON.parse(stripped);}
function cleanModelEvent(x:any){const allowed=new Set(["PLAN","HYPOTHESIS","CLAIM","COUNTERCLAIM","QUESTION","EVIDENCE","ASSUMPTION","FALSIFIER","CRITIQUE","AGREEMENT","SYNTHESIS","ACTION_PROPOSAL","REQUEST_DUEL"]);if(!allowed.has(x?.event_type))throw new Error("model_event_type_invalid");const priority=(Number(x.priority)===1?1:2) as 1|2;const payload=(x.payload&&typeof x.payload==="object")?x.payload:{};const refs=Array.isArray(x.respond_to_hashes)?x.respond_to_hashes.filter((v:any)=>typeof v==="string"):[];return{event_type:x.event_type as string,priority,payload,refs};}
async function toolIfRequested(modelEvent:any,parents:string[]){const tr=modelEvent.payload?.tool_request;if(!tr||typeof tr!=="object"||!tr.name)return;const call=await emitRuntime("TOOL_CALL",1,{tool:String(tr.name),arguments:tr.arguments||{}},parents);if(!TOOL_URL){await emitRuntime("TOOL_ERROR",1,{tool:String(tr.name),error:"tool_executor_unconfigured"},[String(call.event_hash)]);return;}try{const r=await fetch(`${TOOL_URL}/execute`,{method:"POST",headers:{"content-type":"application/json",...(TOOL_TOKEN?{authorization:`Bearer ${TOOL_TOKEN}`}:{})},body:JSON.stringify({workspace_id:WORKSPACE_ID,agent:AGENT,tool:tr.name,arguments:tr.arguments||{}})});const text=await r.text();await emitRuntime(r.ok?"TOOL_RESULT":"TOOL_ERROR",1,{tool:String(tr.name),status:r.status,result:text.slice(0,20000)},[String(call.event_hash)]);}catch(e){await emitRuntime("TOOL_ERROR",1,{tool:String(tr.name),error:String(e)},[String(call.event_hash)]);}}
async function microstep(){const prior=await readEvents(Math.max(0,lastApplied-1000),1000);const f=await frontierAt(lastApplied);const mandatory=[...pendingMandatoryPeerHashes].sort();const manifest={workspace_id:WORKSPACE_ID,semantic_point:semanticPoint,applied_frontier:f,events:boundedContext(prior,80).filter(e=>Number(e.commit_seq)<=lastApplied).map(e=>({commit_seq:e.commit_seq,agent:e.agent,event_type:e.event_type,event_hash:e.event_hash,payload:e.payload}))};const proof=await peerRpc<any>("h205f22_a2_create_visibility_proof_v1",[sessionId,f.head_commit_seq,f.gpt_seq,f.glm_seq,manifest,mandatory]);proofSeenSeq=Number(proof.seen_commit_seq);const parents=causalParents(AGENT,prior.filter(e=>Number(e.commit_seq)<=lastApplied));const started=await emitRuntime("MODEL_STARTED",3,{visibility_proof_id:proof.proof_id,input_frontier_hash:proof.input_frontier_hash,mandatory_peer_event_hashes:mandatory},parents);aborter=new AbortController();const timer=setTimeout(()=>aborter?.abort("microstep_timeout"),MICROSTEP_TIMEOUT);let raw:any;try{raw=await callModel({model:MODEL,temperature:0.2,messages:[{role:"system",content:"A2 public cognition microstep. Output strict JSON only."},{role:"user",content:prompt(prior.filter(e=>Number(e.commit_seq)<=lastApplied),f)}]},aborter.signal);}catch(e){clearTimeout(timer);aborter=null;const aborted=String(e).includes("AbortError")||String(e).includes("aborted");await emitRuntime(aborted?"MODEL_INTERRUPTED":"ERROR",aborted?1:0,{reason:String(e),visibility_proof_id:proof.proof_id},[String(started.event_hash)]);return;}clearTimeout(timer);aborter=null;const m=cleanModelEvent(raw);const visiblePrior=prior.filter(e=>Number(e.commit_seq)<=lastApplied);const allKnown=new Set(visiblePrior.map(e=>e.event_hash));const refs=m.refs.filter((h:string)=>allKnown.has(h));const event=await emit(m.event_type,m.priority,{...m.payload,reasoning_visibility:"PUBLIC_ENGINEERING_SUMMARY_V1"},causalParents(AGENT,visiblePrior,[String(started.event_hash),...refs]),String(proof.proof_id));pendingMandatoryPeerHashes.clear();await emitRuntime("MODEL_COMPLETED",3,{accepted_event_hash:event.event_hash,visibility_proof_id:proof.proof_id},[String(event.event_hash)]);await toolIfRequested(m,[String(event.event_hash)]);}
function handleStreamEvent(e:any){const seq=Number(e?.commit_seq||0);if(!seq||seq<=streamAfter)return;streamAfter=seq;if(e.agent!==AGENT&&Number(e.priority)<=1&&seq>proofSeenSeq&&aborter)aborter.abort(`peer_p${e.priority}_event_${seq}`);}
async function streamLoop(){while(!stopped){try{const r=await fetch(`${INGRESS_URL}/v1/a2/stream?workspace_id=${encodeURIComponent(WORKSPACE_ID)}&after=${streamAfter}`,{headers:{...(INGRESS_TOKEN?{authorization:`Bearer ${INGRESS_TOKEN}`}:{})}});if(!r.ok||!r.body)throw new Error(`stream_${r.status}`);const reader=r.body.getReader(),decoder=new TextDecoder();let buf="";while(!stopped){const {done,value}=await reader.read();if(done)break;buf+=decoder.decode(value,{stream:true});let idx;while((idx=buf.indexOf("\n\n"))>=0){const frame=buf.slice(0,idx);buf=buf.slice(idx+2);for(const line of frame.split("\n")){if(!line.startsWith("data: "))continue;try{const e=JSON.parse(line.slice(6));if(e.type!=="heartbeat")handleStreamEvent(e);}catch{}}}}}catch(e){if(!stopped)console.error("a2_stream_reconnect",String(e));}if(!stopped)await sleep(500);}}
async function main(){const ws=await getWorkspace();semanticPoint=String(ws.semantic_point);await register();await catchUp();streamAfter=lastApplied;void streamLoop();await emitRuntime("CHECKPOINT",0,{state:"A2_RUNTIME_READY",agent:AGENT,runtime_id:RUNTIME_ID,exact_model:MODEL,direct_database_access:false});while(!stopped){await catchUp();try{await microstep();}catch(e){console.error("a2_microstep_failed",e);try{await emitRuntime("ERROR",0,{stage:"microstep",error:String(e)});}catch{}await sleep(1000);}await sleep(POLL_MS);}}
process.on("SIGTERM",()=>{stopped=true;aborter?.abort("shutdown");});process.on("SIGINT",()=>{stopped=true;aborter?.abort("shutdown");});
void main().catch(e=>{console.error(e);process.exit(1);});
