import { randomUUID, generateKeyPairSync, createPrivateKey, createPublicKey, sign as edSign, createHash, type KeyObject } from "node:crypto";
import { Pool, Client } from "pg";
import { exactModel, peerOf, mandatoryPeerHashes, causalParents, boundedContext, isActionConflict, verifyEd25519RawPublicKey, type Agent, type A2Event, type Frontier } from "./a2_protocol.js";

type Json=Record<string,unknown>;
const DATABASE_URL=req("DATABASE_URL");
const WORKSPACE_ID=req("A2_WORKSPACE_ID");
const AGENT=(req("A2_AGENT").toUpperCase()) as Agent;if(!["GPT","GLM"].includes(AGENT))throw new Error("A2_AGENT_invalid");
const MODEL_URL=req("A2_MODEL_URL").replace(/\/$/,"");
const MODEL_TOKEN=process.env.A2_MODEL_TOKEN||"";
const MODEL=process.env.A2_MODEL||exactModel(AGENT);if(MODEL!==exactModel(AGENT))throw new Error(`exact_model_required:${exactModel(AGENT)}`);
const PROVIDER=process.env.A2_PROVIDER||(AGENT==="GPT"?"openai":"z.ai");
const RUNTIME_ID=process.env.A2_RUNTIME_ID||`a2-${AGENT.toLowerCase()}-${process.pid}`;
const EPOCH=int(process.env.A2_CAPABILITY_EPOCH,1,1,1_000_000);
const POLL_MS=int(process.env.A2_POLL_MS,250,50,5000);
const MICROSTEP_TIMEOUT=int(process.env.A2_MICROSTEP_TIMEOUT_MS,15000,1000,120000);
const TOOL_URL=(process.env.A2_TOOL_EXECUTOR_URL||"").replace(/\/$/,"");
const TOOL_TOKEN=process.env.A2_TOOL_EXECUTOR_TOKEN||"";
const pool=new Pool({connectionString:DATABASE_URL,max:6});
const listener=new Client({connectionString:DATABASE_URL});
let aborter:AbortController|null=null, proofSeenSeq=0, sessionId="", semanticPoint="", lastApplied=0, stopped=false;
const keypair=loadKey();
const publicRaw=rawPublic(keypair.publicKey);const publicB64=publicRaw.toString("base64");const fingerprint=createHash("sha256").update(publicRaw).digest("hex");
const caps={reasoning_summary_stream:AGENT==="GPT",tool_calls:true,max_emit_rate_hz:4,inbound_queue_depth:200,resume_from_commit_seq:true,max_opaque_ms:MICROSTEP_TIMEOUT};
const PEER_RECEIPT_TYPES=new Set(["PLAN","HYPOTHESIS","CLAIM","COUNTERCLAIM","QUESTION","EVIDENCE","ASSUMPTION","FALSIFIER","CRITIQUE","AGREEMENT","SYNTHESIS","ACTION_PROPOSAL","REQUEST_DUEL","TOOL_RESULT","TOOL_ERROR","TEST_RESULT","AUTHORITY_DRIFT","CHECKPOINT","DUEL_OPENED","DUEL_DECIDED"]);

function req(n:string){const v=process.env[n];if(!v)throw new Error(`${n}_required`);return v;}
function int(v:string|undefined,f:number,min:number,max:number){const n=Number(v??f);return Number.isFinite(n)?Math.max(min,Math.min(max,Math.trunc(n))):f;}
function loadKey():{privateKey:KeyObject;publicKey:KeyObject}{const b64=process.env.A2_ED25519_PRIVATE_KEY_PEM_B64;if(b64){const privateKey=createPrivateKey(Buffer.from(b64,"base64").toString("utf8"));return{privateKey,publicKey:createPublicKey(privateKey)};}return generateKeyPairSync("ed25519");}
function rawPublic(k:KeyObject){const der=k.export({format:"der",type:"spki"}) as Buffer;if(der.length<32)throw new Error("ed25519_spki_invalid");return der.subarray(der.length-32);}
async function rpc<T=any>(fn:string,args:any[]):Promise<T>{const slots=args.map((_,i)=>`$${i+1}`).join(",");const r=await pool.query<{v:T}>(`select public.${fn}(${slots}) as v`,args);return r.rows[0]!.v;}
async function getWorkspace(){const r=await pool.query<any>("select workspace_id,semantic_point,mode from destruktion_meta.compute_fabric_a2_workspace_h205f22 where workspace_id=$1",[WORKSPACE_ID]);if(!r.rows[0])throw new Error("workspace_not_found");return r.rows[0];}
async function register(){const v=await rpc<any>("h205f22_a2_register_peer_session_v1",[WORKSPACE_ID,AGENT,RUNTIME_ID,PROVIDER,MODEL,MODEL,JSON.stringify(caps),EPOCH,publicB64]);sessionId=String(v.session_id);}
async function readEvents(after=0,limit=1000):Promise<A2Event[]>{const r=await rpc<any>("h205f22_a2_read_events_v1",[WORKSPACE_ID,after,limit]);return r.events||[];}
async function frontier():Promise<Frontier>{return rpc("h205f22_a2_read_frontier_v1",[WORKSPACE_ID]);}
async function seq():Promise<number>{const r=await rpc<any>("h205f22_a2_next_agent_seq_v1",[sessionId]);return Number(r.next_agent_seq);}
async function emitRuntime(type:string,priority:0|1|2|3,payload:Json,parents:string[]=[]):Promise<any>{return emit(type,priority,payload,parents,null);}
async function emit(type:string,priority:0|1|2|3,payload:Json,parents:string[],proofId:string|null):Promise<any>{const agentSeq=await seq();const eventId=randomUUID();const provenance={provider:PROVIDER,requested_model:MODEL,reported_model:MODEL,runtime_id:RUNTIME_ID,capability_epoch:EPOCH};const prep=await rpc<any>("h205f22_a2_prepare_event_v1",[eventId,sessionId,agentSeq,semanticPoint,type,priority,parents,JSON.stringify(payload),proofId,JSON.stringify(provenance)]);const hash=String(prep.event_hash);const signature=edSign(null,Buffer.from(hash,"hex"),keypair.privateKey).toString("base64");if(!verifyEd25519RawPublicKey(publicB64,hash,signature))throw new Error("a2_local_signature_verify_failed");return rpc("h205f22_a2_emit_agent_event_v1",[eventId,sessionId,agentSeq,semanticPoint,type,priority,parents,JSON.stringify(payload),proofId,JSON.stringify(provenance),hash,signature,fingerprint,true]);}
function receiptablePeerEvents(events:A2Event[]){return events.filter(e=>e.agent!==AGENT&&e.event_type!=="PEER_EVENT_APPLIED"&&(Number(e.priority)<=1||PEER_RECEIPT_TYPES.has(e.event_type))).slice(-64);}
async function catchUp(){const events=await readEvents(lastApplied,1000);if(!events.length)return events;const appliedThrough=Math.max(...events.map(e=>Number(e.commit_seq)));const f=await frontier();lastApplied=appliedThrough;await rpc("h205f22_a2_update_cursor_v1",[sessionId,lastApplied,lastApplied,f.frontier_hash]);const peer=receiptablePeerEvents(events);if(peer.length){const hashes=peer.map(e=>e.event_hash);await emitRuntime("PEER_EVENT_APPLIED",3,{receipt_policy:"BATCH_NO_RECURSION_V1",peer_agent:peerOf(AGENT),peer_event_hashes:hashes,peer_commit_seq_min:Math.min(...peer.map(e=>Number(e.commit_seq))),peer_commit_seq_max:Math.max(...peer.map(e=>Number(e.commit_seq))),applied_through_commit_seq:appliedThrough},hashes);}return events;}
function prompt(events:A2Event[],f:Frontier){const peer=peerOf(AGENT);return `You are ${AGENT} in A2_CCP_V1 collaborating with ${peer}. Hidden chain-of-thought is not requested. Produce exactly one public engineering microstep as JSON.\nReturn: {"event_type":"PLAN|HYPOTHESIS|CLAIM|COUNTERCLAIM|QUESTION|EVIDENCE|ASSUMPTION|FALSIFIER|CRITIQUE|AGREEMENT|SYNTHESIS|ACTION_PROPOSAL|REQUEST_DUEL","priority":2,"payload":{"reasoning_summary":["..."],"claim":"...","evidence_used":[],"assumptions":[],"falsifier":"...","proposed_action":{"kind":"..."},"tool_request":{"name":"optional","arguments":{}}},"respond_to_hashes":[]}\nBe concise and causal. Do not claim tools/evidence you did not observe.\nsemantic_point=${semanticPoint}\nfrontier=${JSON.stringify(f)}\ncommitted_context=${JSON.stringify(boundedContext(events,80))}`;}
async function callModel(body:Json,signal:AbortSignal):Promise<any>{const r=await fetch(`${MODEL_URL}/v1/chat/completions`,{method:"POST",headers:{"content-type":"application/json",...(MODEL_TOKEN?{authorization:`Bearer ${MODEL_TOKEN}`}:{})},body:JSON.stringify(body),signal});if(!r.ok)throw new Error(`model_${r.status}:${(await r.text()).slice(0,500)}`);const j:any=await r.json();const c=j?.choices?.[0]?.message?.content;if(typeof c!=="string")throw new Error("model_content_missing");const stripped=c.trim().replace(/^```json\s*/i,"").replace(/```$/," ").trim();return JSON.parse(stripped);}
function cleanModelEvent(x:any){const allowed=new Set(["PLAN","HYPOTHESIS","CLAIM","COUNTERCLAIM","QUESTION","EVIDENCE","ASSUMPTION","FALSIFIER","CRITIQUE","AGREEMENT","SYNTHESIS","ACTION_PROPOSAL","REQUEST_DUEL"]);if(!allowed.has(x?.event_type))throw new Error("model_event_type_invalid");const priority=(Number(x.priority)===1?1:2) as 1|2;const payload=(x.payload&&typeof x.payload==="object")?x.payload:{};const refs=Array.isArray(x.respond_to_hashes)?x.respond_to_hashes.filter((v:any)=>typeof v==="string"):[];return{event_type:x.event_type as string,priority,payload,refs};}
async function toolIfRequested(modelEvent:any,parents:string[]){const tr=modelEvent.payload?.tool_request;if(!tr||typeof tr!=="object"||!tr.name)return;const call=await emitRuntime("TOOL_CALL",1,{tool:String(tr.name),arguments:tr.arguments||{}},parents);if(!TOOL_URL){await emitRuntime("TOOL_ERROR",1,{tool:String(tr.name),error:"tool_executor_unconfigured"},[String(call.event_hash)]);return;}try{const r=await fetch(`${TOOL_URL}/execute`,{method:"POST",headers:{"content-type":"application/json",...(TOOL_TOKEN?{authorization:`Bearer ${TOOL_TOKEN}`}:{})},body:JSON.stringify({workspace_id:WORKSPACE_ID,agent:AGENT,tool:tr.name,arguments:tr.arguments||{}})});const text=await r.text();await emitRuntime(r.ok?"TOOL_RESULT":"TOOL_ERROR",1,{tool:String(tr.name),status:r.status,result:text.slice(0,20000)},[String(call.event_hash)]);}catch(e){await emitRuntime("TOOL_ERROR",1,{tool:String(tr.name),error:String(e)},[String(call.event_hash)]);}}
async function maybeConflict(newEvent:A2Event,events:A2Event[]){if(AGENT!=="GPT")return;const peer=[...events].reverse().find(e=>e.agent!==AGENT&&isActionConflict(newEvent,e));if(!peer)return;await rpc("h205f22_a2_open_conflict_v1",[WORKSPACE_ID,semanticPoint,newEvent.event_hash,peer.event_hash,"action_kind_mismatch","HIGH"]);}
async function maybeEscalateConflicts(){if(AGENT!=="GPT")return;const r=await pool.query<any>("select c.*, le.commit_seq left_seq, re.commit_seq right_seq from destruktion_meta.compute_fabric_a2_semantic_conflict_h205f22 c join destruktion_meta.compute_fabric_a2_agent_event_h205f22 le on le.event_hash=c.left_event_hash join destruktion_meta.compute_fabric_a2_agent_event_h205f22 re on re.event_hash=c.right_event_hash where c.workspace_id=$1 and c.status in ('OPEN','DIRECT_RESOLUTION') order by c.created_at",[WORKSPACE_ID]);for(const c of r.rows){const minSeq=Math.min(Number(c.left_seq),Number(c.right_seq));const x=await pool.query<any>("select count(*)::int n, bool_or(event_type='REQUEST_DUEL') requested from destruktion_meta.compute_fabric_a2_agent_event_h205f22 where workspace_id=$1 and semantic_point=$2 and commit_seq >= $3 and event_type in ('CLAIM','COUNTERCLAIM','CRITIQUE','SYNTHESIS','ACTION_PROPOSAL','REQUEST_DUEL')",[WORKSPACE_ID,semanticPoint,minSeq]);const n=Number(x.rows[0]?.n||0),requested=x.rows[0]?.requested===true;if(!requested&&n<6)continue;const ws=await pool.query<any>("select * from destruktion_meta.compute_fabric_a2_workspace_h205f22 where workspace_id=$1",[WORKSPACE_ID]);const w=ws.rows[0];const f=await frontier();const key=`a2-v4::${WORKSPACE_ID}::${c.conflict_id}::${f.frontier_hash}`;const subject={mode:"A2_CAUSAL_CONFLICT_V1",semantic_point:semanticPoint,conflict_id:c.conflict_id,causal_frontier_hash:f.frontier_hash,left_event_hash:c.left_event_hash,right_event_hash:c.right_event_hash,debate_protocol:"SAME_POINT_DUEL_V4",authority_rule:"DUEL_DECISION_NONAUTHORITY_UNTIL_EXECUTOR_REVALIDATES"};const duel=await rpc<any>("h205f22_duel_create_same_point_v4",[key,"A2_REALTIME_MULTI_AGENT_COGNITIVE_BUS",w.base_github_sha,JSON.stringify(subject),"SOVEREIGN_ONLY",exactModel("GPT"),exactModel("GLM")]);const duelId=String(duel.duel_id);await rpc("h205f22_a2_attach_duel_v1",[c.conflict_id,duelId]);await emitRuntime("DUEL_OPENED",0,{conflict_id:c.conflict_id,duel_id:duelId,frontier_hash:f.frontier_hash});await pool.query("select pg_notify($1,$2)",["h205f22_same_point_v4_ready",JSON.stringify({duel_id:duelId,source:"a2-conflict-bridge"})]);}}
async function syncDecidedDuels(){if(AGENT!=="GPT")return;const r=await pool.query<any>("select conflict_id,duel_id from destruktion_meta.compute_fabric_a2_semantic_conflict_h205f22 where workspace_id=$1 and status='DUEL' and duel_id is not null",[WORKSPACE_ID]);for(const c of r.rows){const d=await rpc<any>("h205f22_duel_read_same_point_v4",[c.duel_id]);if(d.status!=="DECIDED")continue;const e=await emitRuntime("DUEL_DECIDED",0,{conflict_id:c.conflict_id,duel_id:c.duel_id,decision:d.decision||null,resulting_action:d.resulting_action||null,canonical:false,authority_effect:false});await rpc("h205f22_a2_resolve_conflict_v1",[c.conflict_id,e.event_hash]);}}
async function microstep(){const prior=await readEvents(Math.max(0,lastApplied-1000),1000);const f=await frontier();const mandatory=mandatoryPeerHashes(AGENT,prior,lastApplied);const manifest={workspace_id:WORKSPACE_ID,semantic_point:semanticPoint,frontier:f,events:boundedContext(prior,80).map(e=>({commit_seq:e.commit_seq,agent:e.agent,event_type:e.event_type,event_hash:e.event_hash,payload:e.payload}))};const proof=await rpc<any>("h205f22_a2_create_visibility_proof_v1",[sessionId,f.head_commit_seq,f.gpt_seq,f.glm_seq,JSON.stringify(manifest),mandatory]);proofSeenSeq=Number(proof.seen_commit_seq);const parents=causalParents(AGENT,prior);const started=await emitRuntime("MODEL_STARTED",3,{visibility_proof_id:proof.proof_id,input_frontier_hash:proof.input_frontier_hash},parents);aborter=new AbortController();const timer=setTimeout(()=>aborter?.abort("microstep_timeout"),MICROSTEP_TIMEOUT);let raw:any;try{raw=await callModel({model:MODEL,temperature:0.2,messages:[{role:"system",content:"A2 public cognition microstep. Output strict JSON only."},{role:"user",content:prompt(prior,f)}]},aborter.signal);}catch(e){clearTimeout(timer);aborter=null;const aborted=String(e).includes("AbortError")||String(e).includes("aborted");await emitRuntime(aborted?"MODEL_INTERRUPTED":"ERROR",aborted?1:0,{reason:String(e),visibility_proof_id:proof.proof_id},[String(started.event_hash)]);return;}clearTimeout(timer);aborter=null;const m=cleanModelEvent(raw);const allKnown=new Set(prior.map(e=>e.event_hash));const refs=m.refs.filter((h:string)=>allKnown.has(h));const event=await emit(m.event_type,m.priority,{...m.payload,reasoning_visibility:"PUBLIC_ENGINEERING_SUMMARY_V1"},causalParents(AGENT,prior,[String(started.event_hash),...refs]),String(proof.proof_id));await emitRuntime("MODEL_COMPLETED",3,{accepted_event_hash:event.event_hash,visibility_proof_id:proof.proof_id},[String(event.event_hash)]);await toolIfRequested(m,[String(event.event_hash)]);await maybeConflict({...event,payload:m.payload,semantic_point:semanticPoint,agent:AGENT,event_type:m.event_type,priority:m.priority} as A2Event,prior);}
async function startListener(){await listener.connect();await listener.query("listen h205f22_a2_event");listener.on("notification",(msg:any)=>{try{const p=JSON.parse(msg.payload||"{}");if(p.workspace_id!==WORKSPACE_ID||p.agent===AGENT)return;if(Number(p.priority)<=1&&Number(p.commit_seq)>proofSeenSeq&&aborter)aborter.abort(`peer_p${p.priority}_event_${p.commit_seq}`);}catch{}});}
async function main(){const ws=await getWorkspace();semanticPoint=String(ws.semantic_point);await register();await startListener();await catchUp();await emitRuntime("CHECKPOINT",0,{state:"A2_RUNTIME_READY",agent:AGENT,runtime_id:RUNTIME_ID,exact_model:MODEL});while(!stopped){await catchUp();await syncDecidedDuels();await maybeEscalateConflicts();try{await microstep();}catch(e){console.error("a2_microstep_failed",e);try{await emitRuntime("ERROR",0,{stage:"microstep",error:String(e)});}catch{}await new Promise(r=>setTimeout(r,1000));}await new Promise(r=>setTimeout(r,POLL_MS));}}
process.on("SIGTERM",()=>{stopped=true;aborter?.abort("shutdown");});process.on("SIGINT",()=>{stopped=true;aborter?.abort("shutdown");});
void main().catch(async e=>{console.error(e);await Promise.allSettled([pool.end(),listener.end()]);process.exit(1);});