import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

// Keep npm's Windows command line below cmd.exe's limit. Each Node invocation
// checks one reviewed source file, without a shell or a combined argument list.
export const SOURCE_CHECK_FILES = Object.freeze([
  "src/final-runtime-entry.mjs",
  "src/final-runtime-activation.mjs",
  "src/final-runtime-activation-registry.mjs",
  "src/development-plane-activated.mjs",
  "src/native-supervisor-client-activated.mjs",
  "src/main-entry.mjs",
  "src/browser-startup-observability.mjs",
  "src/single-instance-guard.mjs",
  "src/main.mjs",
  "src/shell-layout.mjs",
  "src/browser-policy.mjs",
  "src/legacy-provider-quarantine.mjs",
  "src/compute-bridge-client.mjs",
  "src/browser-agent-platform.mjs",
  "src/computer-authority-plane.mjs",
  "src/computer-effect-binding.mjs",
  "src/windows-local-computer-executor.mjs",
  "src/agent-platform-task-config.mjs",
  "src/agent-origin-proof.mjs",
  "src/fleet-submit-readiness.mjs",
  "src/fleet-provisioner.mjs",
  "src/fleet-elastic-governor.mjs",
  "src/fleet-provisioner-core.mjs",
  "src/fleet-runtime-bridge.mjs",
  "src/fleet-target-revalidation.mjs",
  "src/fleet-target-local-observer.mjs",
  "src/fleet-target-persistence.mjs",
  "src/fleet-state-target-revalidation.mjs",
  "src/federated-agent-identity.mjs",
  "src/autonomy-governor.mjs",
  "src/devos-native-task-cycle.mjs",
  "src/devos-native-task-cycle-core.mjs",
  "src/devos-runtime-compatibility.mjs",
  "src/devos-runtime-control.mjs",
  "src/metaengine-devos-projection-core.cjs",
  "src/metaengine-devos-projection.mjs",
  "src/metaengine-devos-session-layout.mjs",
  "src/metaengine-devos-session-layout-projection.mjs",
  "src/metaengine-devos-presentation-focus.mjs",
  "src/metaengine-devos-shell-view-model.mjs",
  "src/workspace-workbench-projection.mjs",
  "supabase/a2-browser-native-supervisor-devos-routes.mjs",
  "src/meta-objective-compiler.mjs",
  "supabase/a2-browser-native-supervisor-v1/devos-routes.mjs",
  "supabase/a2-browser-native-supervisor-v1/meta-routes.mjs",
  "supabase/a2-browser-native-supervisor-v1/workspace-observation-routes.mjs",
  "supabase/a2-browser-native-supervisor-v1/runtime-capabilities.mjs",
  "supabase/a2-browser-native-supervisor-v1/cognitive-delta-routes.mjs",
  "supabase/a2-browser-native-supervisor-v1/postgres-command-wake.mjs",
  "src/owner-safety-gate-registry.mjs",
  "src/development-plane.mjs",
  "src/development-plane-worker.cjs",
  "src/candidate-capsule.cjs",
  "src/verification-sandbox-plan.cjs",
  "src/verification-sandbox-backend-binding.cjs",
  "src/advisory-evidence-verifier.cjs",
  "src/development-plane-smoke.mjs",
  "smoke/dp/main.cjs",
  "src/tab-registry.mjs",
  "src/tab-network-activity.mjs",
  "src/chatgpt-session-monitor.mjs",
  "src/chatgpt-retry-policy.mjs",
  "src/supervisor-device-identity.mjs",
  "src/browser-persistent-cdp-session.mjs",
  "src/native-effect-runtime-observation.mjs",
  "src/native-effect-binding.mjs",
  "src/browser-cognitive-delta-bus.mjs",
  "src/browser-cognitive-delta-transport.mjs",
  "src/browser-cognitive-message-port-hub.mjs",
  "src/browser-webcontents-tab-index.mjs",
  "src/browser-main-event-loop-pressure.mjs",
  "src/browser-brain-stream-clock.mjs",
  "src/browser-brain-cognition-fabric.mjs",
  "src/browser-brain-collaboration-fabric.mjs",
  "src/browser-brain-collaboration-journal.mjs",
  "src/browser-brain-episodic-memory.mjs",
  "src/browser-brain-stall-detector.mjs",
  "src/browser-brain-routing-v2.mjs",
  "src/browser-brain-a2a-adapter.mjs",
  "src/browser-brain-collaboration-runtime-v2.mjs",
  "src/browser-brain-durable-persistence.mjs",
  "src/browser-brain-continuous-coordinator.mjs",
  "src/native-supervisor-command-lanes.mjs",
  "src/native-supervisor-exact-target.mjs",
  "src/browser-realtime-process-plane.mjs",
  "src/native-supervisor-client.mjs",
  "src/native-supervisor-command-fastlane.mjs",
  "src/native-supervisor-command-batch-fastlane.mjs",
  "src/rsi-operator-console.mjs",
  "src/native-browser-control.mjs",
  "src/verified-download-manager.mjs",
  "src/trusted-dev-release-resolver.mjs",
  "src/bounded-network-fetch.mjs",
  "src/supervisor-keepalive.mjs",
  "src/supervisor-lifecycle-runtime-core.mjs",
  "src/supervisor-lifecycle-runtime.mjs",
  "src/supervisor-mesh.mjs",
  "src/supervisor-mesh-runtime.mjs",
  "src/supervisor-mesh-epoch-fence.mjs",
  "src/supervisor-mesh-wire-projection.mjs",
  "src/self-update-runtime.mjs",
  "src/self-update-runtime-v8.mjs",
  "src/self-update-handoff.mjs",
  "src/self-update-transaction-journal.mjs",
  "src/self-update-successor-qualification.mjs",
  "src/self-update-signed-heartbeat.mjs",
  "src/self-update-bootstrap-recovery-classifier.mjs",
  "src/self-update-smoke.mjs",
  "src/browser-guardian-machine-bootstrap-launcher.mjs",
  "src/browser-guardian-core.mjs",
  "src/browser-guardian-session-broker-core.mjs",
  "src/browser-guardian-session-broker-effect-gate.mjs",
  "src/browser-guardian-session-broker-controller.mjs",
  "src/browser-guardian-owner-session-binding.mjs",
  "src/host-resilience-runtime.mjs",
  "src/browser-sentinel.mjs",
  "src/browser-sentinel-worker.cjs",
  "src/preload-shell.cjs",
  "test/self-update-feed-server.cjs",
  "src/browser-cognitive-system-deltas.mjs",
  "src/metaengine-mission-control-projection.mjs",
  "src/supervisor-loopback-rpc-server.mjs",
  "src/native-supervisor-control-state.mjs",
  "scripts/devos-source-snapshot-builder.cjs",
  "src/runtime-genesis.mjs",
  "src/emergency-maintenance-trust-root.mjs",
  "src/me2/me2-daemon-host.mjs",
  "src/me2/me2-fleet-bridge.mjs",
  "src/me2/me2-integration-entry.mjs",
  "src/me2/me2-fleet-tabs-host.mjs",
  "src/me2/me2-brain-adapter.mjs",
  "src/me2/me2-supervisor-mesh-bridge.mjs",
  "scripts/build-identity.cjs",
  "scripts/build-identity-cli.mjs",
  "scripts/dependency-resolution-digest.mjs",
  "scripts/package-build-reservation.mjs",
  "scripts/package-lock-material.cjs",
  "scripts/package-lock-material.mjs",
  "scripts/npm-sbom-evidence.mjs",
  "scripts/electron-builder-before-pack.cjs",
  "scripts/electron-builder-after-all-artifact-build.cjs",
  "src/me2/me2-socket-client.mjs",
  "src/me2/me2-ui-host.mjs",
  "src/me2/me2-ui-gateway.mjs",
  "scripts/verify-me2-daemon-bundle.mjs",
  "scripts/composed-sbom-evidence.mjs",
  "scripts/stage-client-state-runtime.mjs",
  "scripts/offline-runtime-package-binding.cjs",
  "src/local-state-provider-bootstrap.mjs",
  "src/local-state-provider-policy.mjs",
  "src/local-runtime-host-controller.mjs",
  "src/local-restored-pg17-setup.mjs",
  "src/local-restored-pg17-auto-prepare.mjs",
  "src/private-windows-storage-acl.mjs",
  "src/local-restored-pg17-setup-preload.cjs",
  "src/remote-support-mcp.mjs",
  "src/managed-task-project-runtime.mjs",
  "src/managed-task-project-command-adapter.mjs",
  "src/managed-task-project-binding-rpc.mjs",
  "src/managed-task-project-sqlite-journal.mjs",
  "src/chat-command-policy.mjs",
  "src/github-chat-relay.mjs",
  "src/github-chat-egress-policy.mjs",
  "src/github-chat-relay-journal.mjs",
  "src/github-chat-relay-bootstrap.mjs",
  "src/github-chat-capture.mjs",
  "supabase/a2-browser-native-supervisor-v1/chat-command-routes.mjs",
  "src/github-chat-setup.mjs",
  "src/github-chat-setup-preload.cjs",
  "src/github-chat-setup-renderer.js"
]);
const root = fileURLToPath(new URL('../', import.meta.url));

export function runSourceChecks({ execute = spawnSync } = {}) {
  for (const file of SOURCE_CHECK_FILES) {
    const result = execute(process.execPath, ['--check', file], {
      cwd: root, shell: false, stdio: 'inherit',
    });
    if (result.error || result.signal || result.status !== 0) {
      console.error('source_check_failed:' + file);
      return Number.isInteger(result.status) && result.status > 0 ? result.status : 1;
    }
  }
  return 0;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  process.exitCode = runSourceChecks();
  if (process.exitCode === 0) console.log('source_checks_passed:' + SOURCE_CHECK_FILES.length);
}
