import { createDevosSupervisorRoutes } from './devos-routes.mjs';
import { createMetaSupervisorRoutes } from './meta-routes.mjs';

const SUPABASE_URL=(Deno.env.get('SUPABASE_URL')||'').replace(/\/+$/,'');
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const WORKSPACE_ID='2de9f84b-7c0a-4091-911c-894ff1d6eaf4';
const PROFILE='A2_DEVICE_HTTP_SIGNATURE_V1';
const SERVICE_MARKER='/a2-browser-native-supervisor-v1';
const DEVICE_TABLE='compute_fabric_a2_browser_device_h205f22';
const NONCE_RPC='h205f22_a2_browser_device_consume_nonce_v2';
const ENROLL_TABLE='compute_fabric_a2_browser_device_enrollment_request_h205f22';
const STATE_TABLE='compute_fabric_a2_browser_supervisor_state_h205f22';
const COMMAND_TABLE='compute_fabric_a2_browser_supervisor_command_h205f22';
const LEASE_RPC='h205f22_a2_browser_supervisor_lease_v3';
const COMPLETE_RPC='h205f22_a2_browser_supervisor_complete_v5';
const ACTIVATE_RPC='h205f22_a2_browser_device_activate_approved_v1';
const MESH_SYNC_RPC='h205f22_a2_supervisor_mesh_sync_v1';
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-a2-chat-bridge-client,x-a2-device-profile,x-a2-device-id,x-a2-device-timestamp,x-a2-device-nonce,x-a2-device-body-sha256,x-a2-device-signature,x-metaengine-enroll-timestamp,x-metaengine-enroll-nonce,x-metaengine-enroll-signature','cache-control':'no-store','x-content-type-options':'nosniff'};
const json=(status:number,body:any)=>new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json; charset=utf-8'}});
function restHeaders(extra:Record<string,string>={}){if(!SERVICE_ROLE)throw new Error('service_role_missing');return{apikey:SERVICE_ROLE,authorization:`Bearer ${SERVICE_ROLE}`,'content-type':'application/json',...extra}}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:restHeaders((init.headers||{}) as Record<string,string>)});const t=await r.text();if(!r.ok)throw new Error(`rest_${r.status}:${t.slice(0,200)}`);return t?JSON.parse(t):null}
const rpc=(name:string,args:any)=>rest(`rpc/${encodeURIComponent(name)}`,{method:'POST',body:JSON.stringify(args)});
async function sha256(v:string){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function b64urlBytes(v:string){if(!/^[A-Za-z0-9_-]+$/.test(v))throw new Error('signature_encoding_invalid');const pad='='.repeat((4-v.length%4)%4);const bin=atob(v.replace(/-/g,'+').replace(/_/g,'/')+pad);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
function canonicalJwk(value:any){if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('jwk_invalid');const jwk={crv:String(value.crv||''),ext:value.ext===true,key_ops:Array.isArray(value.key_ops)?value.key_ops.map(String):[],kty:String(value.kty||''),x:String(value.x||''),y:String(value.y||'')};if(jwk.kty!=='EC'||jwk.crv!=='P-256'||!jwk.ext||jwk.key_ops.length!==1||jwk.key_ops[0]!=='verify'||!/^[A-Za-z0-9_-]{43}$/.test(jwk.x)||!/^[A-Za-z0-9_-]{43}$/.test(jwk.y))throw new Error('jwk_invalid');return jwk}
async function verifyP256(jwk:any,material:string,signatureText:string){const sig=b64urlBytes(signatureText);if(sig.byteLength!==64)return false;const key=await crypto.subtle.importKey('jwk',jwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);return crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,sig,new TextEncoder().encode(material)).catch(()=>false)}
function clientId(req:Request){return String(req.headers.get('x-a2-chat-bridge-client')||'').trim().slice(0,160)}
function modeOf(v:any){const m=String(v||'OFF').toUpperCase();return ['OFF','MONITOR','CONTROL'].includes(m)?m:'OFF'}
function parseJson(text:string){try{return text?JSON.parse(text):{}}catch{return null}}
function boundedObject(value:any,maxBytes:number){if(!value||typeof value!=='object'||Array.isArray(value))return null;try{const text=JSON.stringify(value);if(text.length>maxBytes)return null;return JSON.parse(text)}catch{return null}}
function boundedMesh(value:any){
  if(!value||typeof value!=='object'||Array.isArray(value)||String(value.schema||'')!=='metaengine.supervisor-mesh-runtime.v1'||value.authority_effect===true)return null;
  const mesh=value.mesh;if(!mesh||typeof mesh!=='object'||Array.isArray(mesh)||String(mesh.schema||'')!=='metaengine.supervisor-mesh.state.v1'||!Array.isArray(mesh.supervisors)||mesh.supervisors.length>16)return null;
  const supervisors=[];for(const row of mesh.supervisors){const supervisor_id=String(row?.supervisor_id||'').toLowerCase();const conversation_url_sha256=String(row?.conversation_url_sha256||'').toLowerCase();const status=String(row?.status||'LOST').toUpperCase();const tab_id=row?.tab_id==null?null:String(row.tab_id).slice(0,160);if(!/^sup_[a-f0-9]{24}$/.test(supervisor_id)||!/^[a-f0-9]{64}$/.test(conversation_url_sha256)||supervisor_id!==`sup_${conversation_url_sha256.slice(0,24)}`||!['ACTIVE','PAUSED','LOST','AMBIGUOUS_INCARNATION'].includes(status)||row?.authority_effect===true)return null;supervisors.push({supervisor_id,conversation_url_sha256,status,tab_id:status==='LOST'||status==='AMBIGUOUS_INCARNATION'?null:tab_id,selected:row?.selected===true,authority_effect:false});}
  const preferred=mesh.preferred_supervisor_id==null?null:String(mesh.preferred_supervisor_id).toLowerCase();if(preferred!==null&&!/^sup_[a-f0-9]{24}$/.test(preferred))return null;
  return{schema:'metaengine.supervisor-mesh-runtime.v1',running:value.running===true,last_reconcile_at:value.last_reconcile_at||null,last_error:String(value.last_error||'').slice(0,500)||null,authority_effect:false,mesh:{schema:'metaengine.supervisor-mesh.state.v1',version:String(mesh.version||'').slice(0,32),mesh_epoch:Math.max(1,Number(mesh.mesh_epoch)||1),preferred_supervisor_id:preferred,supervisors,authority_effect:false}};
}
async function verifyEnrollment(req:Request,bodyText:string,body:any){const id=clientId(req);if(!id)return{ok:false,reason:'CLIENT_ID_REQUIRED'};let jwk;try{jwk=canonicalJwk(body?.public_jwk)}catch{return{ok:false,reason:'JWK_INVALID'}};if(String(body?.profile||'')!==PROFILE)return{ok:false,reason:'PROFILE_INVALID'};const fingerprint=await sha256(JSON.stringify(jwk));if(String(body?.key_fingerprint_sha256||'')!==fingerprint)return{ok:false,reason:'FINGERPRINT_MISMATCH'};const timestamp=String(req.headers.get('x-metaengine-enroll-timestamp')||'');const nonce=String(req.headers.get('x-metaengine-enroll-nonce')||'');const signature=String(req.headers.get('x-metaengine-enroll-signature')||'');const parsed=Date.parse(timestamp);if(!Number.isFinite(parsed)||Math.abs(Date.now()-parsed)>120000)return{ok:false,reason:'TIMESTAMP_OUT_OF_WINDOW'};if(!/^[A-Za-z0-9_-]{16,96}$/.test(nonce)||!/^[A-Za-z0-9_-]{80,128}$/.test(signature))return{ok:false,reason:'ENROLL_HEADERS_INVALID'};const material=['METAENGINE_NATIVE_ENROLLMENT_V1',`client_id:${id}`,`profile:${PROFILE}`,`fingerprint:${fingerprint}`,`timestamp:${timestamp}`,`nonce:${nonce}`,`body_sha256:${await sha256(bodyText)}`].join('\n');if(!await verifyP256(jwk,material,signature))return{ok:false,reason:'INVALID_SIGNATURE'};return{ok:true,id,jwk,fingerprint}}
async function enrollmentRequest(req:Request,bodyText:string,body:any){const proof=await verifyEnrollment(req,bodyText,body);if(!proof.ok)return json(401,{error:'enrollment_proof_required',reason:proof.reason});const existing=await rest(`${ENROLL_TABLE}?client_id=eq.${encodeURIComponent(proof.id!)}&key_fingerprint_sha256=eq.${proof.fingerprint}&status=in.(PENDING,APPROVED)&expires_at=gt.${encodeURIComponent(new Date().toISOString())}&select=request_id,status,requested_at,expires_at,key_fingerprint_sha256&order=requested_at.desc&limit=1`);if(Array.isArray(existing)&&existing[0])return json(existing[0].status==='APPROVED'?200:202,{accepted:true,...existing[0],reason:'EXISTING_REQUEST',authority_effect:false});const rows=await rest(ENROLL_TABLE,{method:'POST',headers:{prefer:'return=representation'},body:JSON.stringify({client_id:proof.id,profile:PROFILE,public_jwk:proof.jwk,key_fingerprint_sha256:proof.fingerprint,status:'PENDING',metadata:{client_kind:'METAENGINE_BROWSER_ELECTRON_NATIVE',shell_version:String(body?.metadata?.shell_version||'').slice(0,32)},authority_effect:false})});const row=Array.isArray(rows)?rows[0]:null;if(!row)throw new Error('enrollment_insert_failed');return json(202,{accepted:true,request_id:row.request_id,status:row.status,requested_at:row.requested_at,expires_at:row.expires_at,key_fingerprint_sha256:proof.fingerprint,reason:'APPROVAL_REQUIRED',authority_effect:false})}
async function enrollmentStatus(req:Request,bodyText:string,body:any){const proof=await verifyEnrollment(req,bodyText,body);if(!proof.ok)return json(401,{error:'enrollment_proof_required',reason:proof.reason});const requestId=String(body?.request_id||'');if(!/^[0-9a-f-]{36}$/i.test(requestId))return json(400,{error:'request_id_invalid'});const rows=await rest(`${ENROLL_TABLE}?request_id=eq.${encodeURIComponent(requestId)}&client_id=eq.${encodeURIComponent(proof.id!)}&key_fingerprint_sha256=eq.${proof.fingerprint}&select=request_id,status,requested_at,expires_at,approved_at,device_id&limit=1`);const row=Array.isArray(rows)?rows[0]:null;if(!row)return json(404,{error:'enrollment_request_not_found'});if(row.status==='PENDING')return json(202,{accepted:false,request_id:row.request_id,status:'PENDING',reason:'APPROVAL_REQUIRED',expires_at:row.expires_at,authority_effect:false});if(row.status==='REJECTED'||row.status==='EXPIRED')return json(409,{accepted:false,request_id:row.request_id,status:row.status,reason:`REQUEST_${row.status}`,authority_effect:false});const activated=await rpc(ACTIVATE_RPC,{p_request_id:row.request_id,p_client_id:proof.id,p_profile:PROFILE,p_key_fingerprint_sha256:proof.fingerprint,p_public_jwk:proof.jwk});return json(activated?.accepted===true?200:409,{...activated,request_id:row.request_id,authority_effect:false})}
async function authenticateDevice(req:Request,path:string,bodyText:string){const id=clientId(req);if(!id)return{ok:false,reason:'CLIENT_ID_REQUIRED'};const profile=String(req.headers.get('x-a2-device-profile')||'');const deviceId=String(req.headers.get('x-a2-device-id')||'');const timestamp=String(req.headers.get('x-a2-device-timestamp')||'');const nonce=String(req.headers.get('x-a2-device-nonce')||'');const bodyHash=String(req.headers.get('x-a2-device-body-sha256')||'').toLowerCase();const signature=String(req.headers.get('x-a2-device-signature')||'');if(profile!==PROFILE||!/^[0-9a-f-]{36}$/i.test(deviceId)||!Number.isFinite(Date.parse(timestamp))||!/^[A-Za-z0-9_-]{16,96}$/.test(nonce)||!/^[0-9a-f]{64}$/.test(bodyHash)||!/^[A-Za-z0-9_-]{80,128}$/.test(signature))return{ok:false,reason:'DEVICE_HEADERS_INVALID'};if(await sha256(bodyText)!==bodyHash)return{ok:false,reason:'BODY_HASH_MISMATCH'};const rows=await rest(`${DEVICE_TABLE}?device_id=eq.${encodeURIComponent(deviceId)}&client_id=eq.${encodeURIComponent(id)}&select=device_id,client_id,profile,public_jwk,enrollment_pairing_token_hash,active,revoked_at&limit=1`);const device=Array.isArray(rows)?rows[0]:null;if(!device)return{ok:false,reason:'DEVICE_NOT_FOUND'};if(device.active!==true||device.revoked_at)return{ok:false,reason:'DEVICE_REVOKED'};let jwk;try{jwk=canonicalJwk(device.public_jwk)}catch{return{ok:false,reason:'DEVICE_KEY_INVALID'}};const material=[PROFILE,`device_id:${deviceId}`,`method:${req.method.toUpperCase()}`,`path:${path}`,`timestamp:${timestamp}`,`nonce:${nonce}`,`body_sha256:${bodyHash}`].join('\n');if(!await verifyP256(jwk,material,signature))return{ok:false,reason:'INVALID_SIGNATURE'};const grant=String(device.enrollment_pairing_token_hash||'');const grants=await rest(`compute_fabric_a2_chat_bridge_remote_pairing_h205f22?token_hash=eq.${grant}&active=eq.true&select=token_hash&limit=1`);if(!Array.isArray(grants)||grants.length!==1)return{ok:false,reason:'PAIRING_REVOKED'};const nr=await rpc(NONCE_RPC,{p_device_id:deviceId,p_client_id:id,p_nonce_sha256:await sha256(nonce),p_request_timestamp:timestamp});if(nr?.accepted!==true)return{ok:false,reason:String(nr?.reason||'NONCE_REJECTED')};return{ok:true,id,device_id:deviceId,profile:PROFILE,key_fingerprint_sha256:nr.key_fingerprint_sha256||null}}
function boundedState(value:any){const s=value&&typeof value==='object'?value:{};const tabs=Array.isArray(s.tabs)?s.tabs.slice(0,64).map((t:any)=>({tab_id:String(t?.tab_id||'').slice(0,80),url:String(t?.url||'').slice(0,1200),title:String(t?.title||'').slice(0,240),kind:String(t?.kind||'').slice(0,40),selected:t?.selected===true})):[];return{schema:'metaengine.native-browser-supervisor.state.v1',client_kind:'METAENGINE_BROWSER_ELECTRON_NATIVE',shell_version:String(s.shell_version||'').slice(0,32),supervisor_mode:modeOf(s.supervisor_mode),armed:s.armed===true,operator_mode:String(s.operator_mode||'CONTROL').slice(0,32),tabs,active_tab:s.active_tab&&typeof s.active_tab==='object'?s.active_tab:null,development_plane:boundedObject(s.development_plane,32768),fleet:boundedObject(s.fleet,65536),perception:boundedObject(s.perception,32768),supervisor_lifecycle:boundedObject(s.supervisor_lifecycle,32768),supervisor_mesh:boundedMesh(s.supervisor_mesh),self_update:boundedObject(s.self_update,32768),last_error:String(s.last_error||'').slice(0,500)||null,started_at:s.started_at||null,heartbeat_at:new Date().toISOString()}}
async function upsertState(req:Request,body:any,identity:any){const id=clientId(req);const s=boundedState(body?.state);if(s.supervisor_mesh)await rpc(MESH_SYNC_RPC,{p_client_id:id,p_mesh:s.supervisor_mesh});const row={client_id:id,workspace_id:WORKSPACE_ID,last_seen_at:new Date().toISOString(),extension_version:s.shell_version||null,operator_runtime:'native-electron-supervisor-v1',supervisor_mode:s.supervisor_mode,armed:s.armed,operator_mode:s.operator_mode,ordering_policy:'NATIVE_TYPED_COMMAND_LEASE_V1',last_command_id:body?.last_command_id||null,last_command_status:body?.last_command_status||null,state:{...s,transport_identity:{profile:identity.profile,device_id:identity.device_id,key_fingerprint_sha256:identity.key_fingerprint_sha256}},authority_effect:s.supervisor_mode==='CONTROL'||s.armed===true};await rest(`${STATE_TABLE}?on_conflict=client_id`,{method:'POST',headers:{prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});return row}
async function lease(req:Request,body:any){return rpc(LEASE_RPC,{p_workspace_id:WORKSPACE_ID,p_client_id:clientId(req),p_supervisor_mode:modeOf(body?.supervisor_mode),p_lease_timeout_seconds:120})}
async function complete(req:Request,commandId:string,body:any){const rows=await rest(`${COMMAND_TABLE}?workspace_id=eq.${WORKSPACE_ID}&command_id=eq.${encodeURIComponent(commandId)}&select=command_id,action&limit=1`);const row=Array.isArray(rows)?rows[0]:null;if(!row)return json(404,{error:'command_not_found'});const r=await rpc(COMPLETE_RPC,{p_workspace_id:WORKSPACE_ID,p_command_id:commandId,p_client_id:clientId(req),p_ok:body?.ok===true,p_receipt:body?.receipt&&typeof body.receipt==='object'?body.receipt:{},p_error:body?.ok===true?null:String(body?.error||'command_failed').slice(0,500),p_authority_effect:false});return json(r?.accepted===true?200:409,r)}
async function status(){const states=await rest(`${STATE_TABLE}?workspace_id=eq.${WORKSPACE_ID}&select=*&order=last_seen_at.desc&limit=8`);const commands=await rest(`${COMMAND_TABLE}?workspace_id=eq.${WORKSPACE_ID}&select=command_id,idempotency_key,action,platform,status,issued_by,issued_at,expires_at,leased_by,leased_at,completed_at,authority_effect,receipt,error&order=issued_at.desc&limit=40`);return{schema:'metaengine.native-browser-supervisor.status.v1',workspace_id:WORKSPACE_ID,device_auth_required:true,approval_enrollment:true,typed_commands_only:true,arbitrary_eval:false,supervisor_mesh:true,devos_routes:true,meta_orchestrator_routes:true,states,commands}}
const devosRoutes=createDevosSupervisorRoutes({rpc,workspaceId:WORKSPACE_ID});
const metaRoutes=createMetaSupervisorRoutes({rpc,workspaceId:WORKSPACE_ID});

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const url=new URL(req.url);const i=url.pathname.indexOf(SERVICE_MARKER);const path=i>=0?(url.pathname.slice(i+SERVICE_MARKER.length)||'/'):url.pathname;try{if(req.method==='GET'&&path==='/health')return json(200,{ok:true,schema:'metaengine.native-browser-supervisor.health.v1',profile:PROFILE,approval_enrollment:true,typed_commands_only:true,arbitrary_eval:false,supervisor_mesh:true,devos_routes:true,meta_orchestrator_routes:true});const bodyText=req.method==='GET'?'':await req.text();const body=parseJson(bodyText);if(body===null)return json(400,{error:'invalid_json'});if(req.method==='POST'&&path==='/v1/device/enrollment/request')return enrollmentRequest(req,bodyText,body);if(req.method==='POST'&&path==='/v1/device/enrollment/status')return enrollmentStatus(req,bodyText,body);const canonicalPath=`${SERVICE_MARKER}${path}`;const identity=await authenticateDevice(req,canonicalPath,bodyText);if(identity.ok!==true)return json(401,{error:'device_auth_required',reason:identity.reason});const meta=await metaRoutes({req,path,body,clientId:identity.id});if(meta)return meta;const devos=await devosRoutes({req,path,body,clientId:identity.id});if(devos)return devos;if(req.method==='POST'&&path==='/v1/state')return json(202,{accepted:true,state:await upsertState(req,body,identity)});if(req.method==='POST'&&path==='/v1/commands/next')return json(200,await lease(req,body));const m=path.match(/^\/v1\/commands\/([^/]+)\/result$/);if(req.method==='POST'&&m)return complete(req,decodeURIComponent(m[1]),body);if(req.method==='GET'&&path==='/v1/status')return json(200,await status());return json(404,{error:'not_found'})}catch(e){console.error('native_supervisor_v1_failure',String((e as any)?.message||e));return json(502,{error:'native_supervisor_failure'})}});