const ROADMAP_RE=/^[a-z0-9][a-z0-9._:-]{2,159}$/;
const CONFLICTS=['meta_plan_generation_fenced','meta_plan_roadmap_authority_drift','meta_plan_next_generation_mismatch','meta_plan_roadmap_authority_missing'];
const FORBIDDEN_TASK_KEYS=['result_summary','lease_agent_id','lease_tab_id','lease_target_id','lease_agent_generation_epoch','claim_id','lease_expires_at'];
const META_KEYS=new Set(['roadmap_id','alignment_epoch','plan_generation','parent_plan_point','parent_point_id']);
const json=(status,body)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'}});
const object=(v)=>v&&typeof v==='object'&&!Array.isArray(v)?v:null;
const roadmap=(v)=>{const x=String(v||'').trim().toLowerCase();return ROADMAP_RE.test(x)?x:null};
function zero(v,label){const x=object(v);if(!x)throw new Error(`${label}_invalid`);for(const k of ['automatic_retry_allowed','scheduler_authority','browser_authority','release_authority','authority_effect'])if(x[k]===true)throw new Error(`${label}_${k}_invalid`);return x}
function inputs(v,workspaceId,roadmapId){const x=zero(v,'meta_provider_bundle');if(x.schema!=='metaengine.meta-orchestrator.authoritative-inputs.v1'||String(x.workspace_id)!==workspaceId||String(x.roadmap_id||'').toLowerCase()!==roadmapId)throw new Error('meta_provider_bundle_identity_invalid');if(x.task_meta_projection_only!==true||x.task_payload_exposed!==false||x.result_summary_exposed!==false||x.scheduler_identity_exposed!==false||x.receipt_summary_exposed!==false||x.receipt_evidence_exposed!==false)throw new Error('meta_provider_membrane_invalid');zero(x.plan_state,'meta_provider_plan_state');if(!Array.isArray(x.tasks)||x.tasks.length>512)throw new Error('meta_provider_tasks_invalid');for(const t of x.tasks){if(!object(t)||FORBIDDEN_TASK_KEYS.some(k=>Object.hasOwn(t,k))||t.authority_effect===true)throw new Error('meta_provider_task_forbidden');const spec=object(t.task_spec),meta=object(spec?.meta_orchestrator);if(!meta||Object.keys(spec).some(k=>k!=='meta_orchestrator')||Object.keys(meta).some(k=>!META_KEYS.has(k)))throw new Error('meta_provider_task_spec_not_meta_only')}if(!Array.isArray(x.roadmap_receipts)||x.roadmap_receipts.length>512)throw new Error('meta_provider_receipts_invalid');for(const r of x.roadmap_receipts)if(!object(r)||['summary','evidence','research'].some(k=>Object.hasOwn(r,k))||r.authority_effect===true)throw new Error('meta_provider_receipt_forbidden');const c=zero(x.capacity,'meta_provider_capacity');if(c.source==='UNSPECIFIED_FAIL_CLOSED'&&Number(c.available_slots)!==0)throw new Error('meta_provider_capacity_fail_closed_invalid');return x}
function activation(v,workspaceId,roadmapId,expected){const x=zero(v,'meta_provider_activation');if(x.schema!=='metaengine.meta-orchestrator.plan-state.v1'||String(x.workspace_id)!==workspaceId||String(x.roadmap_id||'').toLowerCase()!==roadmapId||Number(x.plan_generation)!==expected+1||x.state!=='ACTIVE')throw new Error('meta_provider_activation_readback_invalid');return x}
export function createMetaSupervisorRoutes({rpc,workspaceId}={}){if(typeof rpc!=='function')throw new Error('meta_provider_rpc_required');const fixed=String(workspaceId||'');if(!/^[0-9a-f-]{36}$/i.test(fixed))throw new Error('meta_provider_workspace_invalid');return async({req,path,body,clientId}={})=>{if(!String(path||'').startsWith('/v1/meta/'))return null;if(!clientId)return json(401,{error:'device_auth_required',automatic_retry_allowed:false,authority_effect:false});const p=object(body)||{};if(Object.hasOwn(p,'workspace_id'))return json(400,{error:'workspace_override_forbidden',automatic_retry_allowed:false,authority_effect:false});if(req?.method==='POST'&&path==='/v1/meta/authoritative-inputs'){const id=roadmap(p.roadmap_id);if(!id)return json(400,{error:'roadmap_id_invalid',automatic_retry_allowed:false,authority_effect:false});const result=await rpc('meta_orchestrator_authoritative_inputs_v1',{p_workspace_id:fixed,p_roadmap_id:id});return json(200,inputs(result,fixed,id))}if(req?.method==='POST'&&path==='/v1/meta/activate-plan'){const id=roadmap(p.roadmap_id),expected=Number(p.expected_current_generation),plan=object(p.plan);if(!id||!Number.isSafeInteger(expected)||expected<0||!plan)return json(400,{error:'meta_plan_request_invalid',automatic_retry_allowed:false,authority_effect:false});if(plan.schema!=='metaengine.meta-orchestrator.plan.v1'||['task_content_authority','scheduler_authority','browser_authority','release_authority','authority_effect'].some(k=>plan[k]===true))return json(400,{error:'meta_plan_zero_authority_required',automatic_retry_allowed:false,authority_effect:false});try{const result=await rpc('meta_orchestrator_plan_activate_v1',{p_workspace_id:fixed,p_roadmap_id:id,p_expected_current_generation:expected,p_plan:plan});return json(200,activation(result,fixed,id,expected))}catch(error){const message=String(error?.message||error||'meta_plan_activation_failed');if(CONFLICTS.some(x=>message.includes(x)))return json(409,{error:'meta_plan_activation_fenced',reason:message.slice(0,240),automatic_retry_allowed:false,authority_effect:false});throw error}}return json(404,{error:'meta_route_not_found',automatic_retry_allowed:false,authority_effect:false})}}
