import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createRemoteJWKSet, jwtVerify } from "npm:jose@6.1.0";

const ISSUER="https://token.actions.githubusercontent.com";
const AUDIENCE="metaengine-h205f22-a2-acceptance";
const JWKS=createRemoteJWKSet(new URL("https://token.actions.githubusercontent.com/.well-known/jwks"));
const EXPECTED={repository:"PatrickFrome/Compute",repository_id:"1341371143",repository_owner_id:"20597814",ref:"refs/heads/work/same-point-duel-v4-a2-cognitive-bus",sub:"repo:PatrickFrome@20597814/Compute@1341371143:ref:refs/heads/work/same-point-duel-v4-a2-cognitive-bus",workflow_ref:"PatrickFrome/Compute/.github/workflows/a2-live-acceptance.yml@refs/heads/work/same-point-duel-v4-a2-cognitive-bus"};
function reply(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store, max-age=0","pragma":"no-cache","x-content-type-options":"nosniff"}});}
function env(name:string){const v=Deno.env.get(name);if(!v)throw new Error(`${name}_unavailable`);return v;}
async function rpc(fn:string,body:Record<string,unknown>){const url=env("SUPABASE_URL"),key=env("SUPABASE_SERVICE_ROLE_KEY");const r=await fetch(`${url}/rest/v1/rpc/${fn}`,{method:"POST",headers:{apikey:key,authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify(body)});const text=await r.text();if(!r.ok){console.error("a2_acceptance_rpc_failed",fn,r.status,text.slice(0,300));throw new Error(String(text).includes("a2_acceptance_oidc_replay_denied")?"a2_acceptance_oidc_replay_denied":"acceptance_exchange_denied");}return text?JSON.parse(text):null;}
function b64url(bytes:Uint8Array){let raw="";for(const b of bytes)raw+=String.fromCharCode(b);return btoa(raw).replaceAll("+","-").replaceAll("/","_").replace(/=+$/g,"");}
function hex(bytes:ArrayBuffer){return [...new Uint8Array(bytes)].map((b)=>b.toString(16).padStart(2,"0")).join("");}
async function sha256(s:string){return hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s)));}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return reply({error:"method_not_allowed"},405);const auth=req.headers.get("authorization")||"";if(!auth.startsWith("Bearer "))return reply({error:"github_oidc_required"},401);try{const {payload,protectedHeader}=await jwtVerify(auth.slice(7),JWKS,{issuer:ISSUER,audience:AUDIENCE,algorithms:["RS256"],clockTolerance:5});if(protectedHeader.typ!=="JWT")throw new Error("oidc_typ_invalid");if(payload.repository!==EXPECTED.repository||String(payload.repository_id??"")!==EXPECTED.repository_id||String(payload.repository_owner_id??"")!==EXPECTED.repository_owner_id)throw new Error("repository_forbidden");if(payload.ref!==EXPECTED.ref||payload.sub!==EXPECTED.sub||payload.workflow_ref!==EXPECTED.workflow_ref)throw new Error("workflow_forbidden");if(payload.event_name!=="push"||payload.runner_environment!=="github-hosted"||payload.repository_visibility!=="public")throw new Error("event_forbidden");const sha=String(payload.sha??""),runId=String(payload.run_id??""),actorId=String(payload.actor_id??""),attempt=Number(payload.run_attempt??0),jti=String(payload.jti??"");if(!/^[0-9a-f]{40}$/.test(sha)||!/^[0-9]+$/.test(runId)||!/^[0-9]+$/.test(actorId)||!Number.isInteger(attempt)||attempt<1||jti.length<8||jti.length>512)throw new Error("claims_invalid");const consumed=await rpc("h205f22_a2_acceptance_consume_oidc_jti_v1",{p_oidc_jti:jti,p_repository_id:EXPECTED.repository_id,p_github_sha:sha,p_github_run_id:runId,p_github_run_attempt:attempt,p_actor_id:actorId,p_workflow_ref:EXPECTED.workflow_ref,p_ref:EXPECTED.ref});const runtimeToken=b64url(crypto.getRandomValues(new Uint8Array(32))),tokenSha=await sha256(runtimeToken);const capability=await rpc("h205f22_a2_issue_runtime_access_token_v1",{p_token_sha256:tokenSha,p_subject:`github:${runId}:${attempt}`,p_github_sha:sha,p_scopes:["rpc","emit","stream"],p_ttl_seconds:1800});const rail=await rpc("h205f22_aop1_vercel_gateway_runtime_secret_v1",{});const vercelKey=String(rail?.vercel_ai_gateway_api_key??""),vercelSha=String(rail?.api_key_sha256??"");if(vercelKey.length<20||!/^[0-9a-f]{64}$/.test(vercelSha))throw new Error("gateway_secret_invalid");const supabaseUrl=env("SUPABASE_URL");return reply({schema:"metaengine.compute.a2-acceptance-bundle.h205f22.v2",github_sha:sha,oidc_exchange:consumed,capability:{...capability,token_sha256:tokenSha},bundle:{a2_runtime_token:runtimeToken,a2_ingress_url:`${supabaseUrl}/functions/v1/metaengine-a2-ingress-h205f22`,vercel_ai_gateway_api_key:vercelKey,vercel_ai_gateway_api_key_sha256:vercelSha},canonical:false,authority_effect:false});}catch(error){console.error("a2_acceptance_exchange_denied",error instanceof Error?error.message:"error");return reply({error:String(error).includes("replay")?"a2_acceptance_oidc_replay_denied":"acceptance_exchange_denied"},403);}});
