#!/usr/bin/env bash
# build-sealed-bootstrap.sh v1.0 — regenerates the SEALED secrets bootstrap from LIVE secret files.
# Repo-safe: this builder contains NO secret literals; values flow file→file only, never printed.
#
# Sealed script lives ONLY on surviving channels (PolarFS /tmp + mirrors) because
# PatrickFrome/Compute is anonymously readable and GitHub auto-revokes PATs found in commits.
# Re-run this builder after ANY secret rotation.
set -euo pipefail

GH_ENV=/home/z/.a2/.github.env
PROJ_ENV=/home/z/my-project/.env
ENVF=/tmp/my-project/.a2-backup/me2.env.20260922
CREDS_DOC=/tmp/my-project/.a2-creds-01.md
SEAL_DIR=/tmp/my-project/phoenix-sealed
OUT="$SEAL_DIR/secrets-bootstrap.sh"
SB_URL="https://sibnfciqcpkuquxzduqr.supabase.co"   # live h205f22 project host (URL is not a secret)
STAMP="$(date +%Y-%m-%d_%H:%M:%S)"

[ -s "$GH_ENV" ] || { echo "BLOCKER: $GH_ENV missing/empty — nothing to seal"; exit 2; }

# --- harvest values (file -> var; never echoed) ---
GH=""
# shellcheck disable=SC1090
. "$GH_ENV" && GH="${GITHUB_TOKEN_ADMIN:-}"
[ -n "$GH" ] || { echo "BLOCKER: GITHUB_TOKEN_ADMIN empty"; exit 2; }

DB=""
[ -s "$PROJ_ENV" ] && DB="$(grep -E '^DATABASE_URL=' "$PROJ_ENV" | head -1 | cut -d= -f2- || true)"

# --- emit sealed script ---
mkdir -p "$SEAL_DIR" /tmp/context-vault-mirror/phoenix-sealed
umask 077
{
  echo '#!/usr/bin/env bash'
  echo "# secrets-bootstrap.sh — SEALED (contains live secrets; DO NOT commit, DO NOT print, DO NOT push to GitHub)"
  echo "# Generated by scripts/phoenix/tools/build-sealed-bootstrap.sh at $STAMP"
  echo "# Purpose: post-env-reset self-restore of secret carriers. Post-reset flow:"
  echo "#   anonymous clone (repo is readable w/o auth) -> scripts/phoenix/phoenix-secrets-restore.sh"
  echo "#   -> finds THIS file on PolarFS/mirrors -> restores /home/z/.a2/.github.env etc."
  echo "set -u"
  printf 'GH_PAT=%q\n' "$GH"
  printf 'SB_URL=%q\n' "$SB_URL"
  echo 'SB_JWT=""  # LOST 2026-09-26 17:11 (ENVF wiped to 0B); cloud copy circular; operator must re-issue, then re-run builder'
  printf 'DB_URL=%q\n' "$DB"
  echo 'GH_REPO_URL=https://github.com/PatrickFrome/Compute.git'
  echo 'TH="${SECRETS_TARGET_HOME:-/home/z}"'
  cat << 'BODY'
gh_api() { curl -s -o /dev/null -w '%{http_code}' -H "Authorization: token $1" https://api.github.com/user; }
restore() {
  A2="$TH/.a2"; mkdir -p "$A2"
  T="$(mktemp)"; printf 'GITHUB_TOKEN_ADMIN=%s\n' "$GH_PAT" > "$T"; chmod 600 "$T"
  CUR_OK=0
  if [ -s "$A2/.github.env" ]; then
    C="$( ( set -a; . "$A2/.github.env" 2>/dev/null; set +a; [ -n "${GITHUB_TOKEN_ADMIN:-}" ] && gh_api "${GITHUB_TOKEN_ADMIN}" ) || echo 000 )"
    [ "$C" = "200" ] && CUR_OK=1
  fi
  if [ "$CUR_OK" = "1" ]; then echo "keep: .github.env (already valid)"; rm -f "$T"
  else cp "$T" "$A2/.github.env"; chmod 600 "$A2/.github.env"; echo "wrote: $A2/.github.env (was missing or invalid)"; rm -f "$T"; fi
  mkdir -p /tmp/my-project/.a2-backup
  if [ ! -s /tmp/my-project/.a2-backup/me2.env.20260922 ]; then
    { printf 'SUPABASE_URL=%s\n' "$SB_URL"
      echo '# SUPABASE_SERVICE_ROLE_JWT= <LOST 2026-09-26 17:11 — operator re-issue required>'
      echo '# cloud copy: Supabase me2-evidence/context-vault/me2.env.20260922.restore-key (unreachable w/o the JWT itself)'; } \
      > /tmp/my-project/.a2-backup/me2.env.20260922
    chmod 600 /tmp/my-project/.a2-backup/me2.env.20260922; echo "wrote: ENVF (URL only; JWT pending operator re-issue)"
  else echo "keep: ENVF (present)"; fi
  if [ -n "$DB_URL" ]; then
    if [ ! -s "$TH/my-project/.env" ]; then
      mkdir -p "$TH/my-project"
      printf 'DATABASE_URL=%s\n' "$DB_URL" > "$TH/my-project/.env"; chmod 600 "$TH/my-project/.env"; echo "wrote: project .env"
    else echo "keep: project .env"; fi
  else echo "skip: project .env (no DB_URL sealed)"; fi
}
case "${1:-restore}" in
  validate) echo "github_api=$(gh_api "$GH_PAT")" ;;
  restore)  restore; echo "github_api=$(gh_api "$GH_PAT")" ;;
  *) echo "usage: $0 [restore|validate]" ;;
esac
BODY
} > "$OUT"
chmod 600 "$OUT"

# --- ensure ENVF has at least the URL right now (0B incident fix) ---
if [ ! -s "$ENVF" ]; then
  mkdir -p "$(dirname "$ENVF")"
  { printf 'SUPABASE_URL=%s\n' "$SB_URL"
    echo '# SUPABASE_SERVICE_ROLE_JWT= <LOST 2026-09-26 17:11 — operator re-issue required>'
    echo '# cloud copy: Supabase me2-evidence/context-vault/me2.env.20260922.restore-key (circular)'; } > "$ENVF"
  chmod 600 "$ENVF"; ENVF_STATE="rebuilt(URL only)"
else ENVF_STATE="present"; fi

# --- creds doc: append dated sections (idempotent) ---
if [ -f "$CREDS_DOC" ] && ! grep -q "SEC-RESTORE-1" "$CREDS_DOC"; then
  {
    echo ""
    echo "## GITHUB ADMIN TOKEN — ОБНОВЛЕНИЕ 2026-09-27 (SEC-RESTORE-1)"
    echo "Новый PAT выдан оператором 2026-09-27 ~00:45, валиден (HTTP 200). Значение:"
    printf '%s\n' "$GH"
    echo "Раздел «GITHUB ADMIN TOKEN (значение)» ниже по файлу — МЁРТВ (HTTP 401, аудит CTX-5)."
    echo ""
    echo "## Supabase — УТОЧНЕНИЕ 2026-09-27 (SEC-RESTORE-1)"
    echo "Проект xpeibufgzjknrhbhpffp (выше) мёртв — подтверждено. ЖИВОЙ проект h205f22: $SB_URL"
    echo "SUPABASE_SERVICE_ROLE_JWT утерян локально 2026-09-26 17:11 (ENVF обнулён до 0B);"
    echo "облачная копия me2-evidence/context-vault/me2.env.20260922.restore-key — циклична (нужен сам JWT)."
    echo "До перевыпуска оператором канал Supabase-бэкапов (heartbeat/supabase-persist) НЕ РАБОТАЕТ."
    echo ""
    echo "## SEALED BOOTSTRAP — 2026-09-27 (SEC-RESTORE-1)"
    echo "Секреты запечатаны в $SEAL_DIR/secrets-bootstrap.sh (chmod 600, ТОЛЬКО PolarFS/зеркала — НЕ в git)."
    echo "Оркестратор восстановления (без литералов): scripts/phoenix/phoenix-secrets-restore.sh в репо."
    echo "После ЛЮБОЙ ротации секретов — перезапустить scripts/phoenix/tools/build-sealed-bootstrap.sh."
  } >> "$CREDS_DOC"
  DOC_STATE="appended"
else DOC_STATE="skipped(already or missing)"; fi

# --- mirrors (best effort) ---
MIRRORS=""
for M in /tmp/context-vault-mirror/phoenix-sealed /home/sync/me2-context-backups/phoenix-sealed; do
  if mkdir -p "$M" 2>/dev/null && cp "$OUT" "$M/" 2>/dev/null; then MIRRORS="$MIRRORS $M"; fi
done

# --- status (no values) ---
SHA12="$(sha256sum "$OUT" | cut -c1-12)"
CODE="$( set -a; . "$GH_ENV"; set +a; curl -s -o /dev/null -w '%{http_code}' -H "Authorization: token ${GITHUB_TOKEN_ADMIN}" https://api.github.com/user )"
echo "sealed: $(stat -c%s "$OUT")B sha12=$SHA12"
echo "github_api=$CODE (PAT alive check)"
echo "ENVF: $ENVF_STATE; creds-doc: $DOC_STATE"
echo "mirrors:$MIRRORS"
