import "jsr:@supabase/functions-js/edge-runtime.d.ts";

type Json=Record<string,unknown>; type Fault={status:number;code:string};
const SUPABASE_URL=required("SUPABASE_URL"),SERVICE_KEY=required("SUPABASE_SERVICE_ROLE_KEY");
const EDGE_VERIFIER_ID="A2_EDGE_WEBCRYPTO_ED25519_V1",INGRESS_VERIFIER_ID="A2_TRUSTED_ED25519_INGRESS_V2";
const RPC_ARGS:Record<string,string[]>={
 h205f22_a2_register_peer_session_v1:["p_workspace_id","p_agent","p_runtime_id","p_provider","p_requested_model","p_reported_model","p_capabilities","p_capability_epoch","p_public_key_base64"],
 h205f22_a2_close_peer_session_v1:["p_session_id"],h205f22_a2_create_visibility_proof_v1:["p_session_id","p_seen_commit_seq","p_seen_gpt_seq","p_seen_glm_seq","p_context_manifest","p_mandatory_peer_event_hashes"],
 h205f22_a2_next_agent_seq_v1:["p_session_id"],h205f22_a2_read_frontier_v1:["p_workspace_id"],h205f22_a2_read_frontier_at_v1:["p_workspace_id","p_through_commit_seq"],
 h205f22_a2_prepare_event_v1:["p_event_id","p_session_id","p_agent_seq","p_semantic_point","p_event_type","p_priority","p_parent_hashes","p_payload","p_visibility_proof_id","p_model_provenance"],
 h205f22_a2_update_cursor_v1:["p_session_id","p_last_received_commit_seq","p_last_applied_commit_seq","p_causal_frontier_hash"],h205f22_a2_read_events_v1:["p_workspace_id","p_after_commit_seq","p_limit"],
 h205f22_a2_read_snapshot_v1:["p_workspace_id","p_recent_limit"],h205f22_a2_read_visibility_proof_v1:["p_proof_id"],h205f22_a2_read_event_ancestry_v1:["p_event_id","p_max_depth"],
 h205f22_a2_join_sync_round_v1:["p_session_id","p_ttl_seconds"],h205f22_a2_abandon_sync_round_v1:["p_session_id","p_round_id","p_reason"],h205f22_a2_read_sync_state_v1:["p_workspace_id"]};
function required(n:string){const v=Deno.env.get(n);if(!v)throw new Error(`${n}_required`);return v;}function reply(body:unknown,status=200,extra:HeadersInit={}){return new Response(JSON.stringify(body),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store, max-age=0",pragma:"no-cache","x-content-type-options":"nosniff",...extra}});}function pathEnds(u:URL,s:string){return u.pathname===s||u.pathname.endsWith(s);}function isUuid(v:unknown):v is string{return typeof v==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v);}function isHash64(v:unknown):v is string{return typeof v==="string"&&/^[0-9a-f]{64}$/.test(v);}function b64(v:string){const s=atob(v);return Uint8Array.from(s,c=>c.charCodeAt(0));}function hexBytes(v:string){const o=new Uint8Array(v.length/2);for(let i=0;i<o.length;i++)o[i]=parseInt(v.slice(i*2,i*2+2),16);return o;}function bytesHex(v:ArrayBuffer|Uint8Array){const b=v instanceof Uint8Array?v:new Uint8Array(v);return[...b].map(x=>x.toString(16).padStart(2,"0")).join("");}async function sha256Hex(v:string|Uint8Array){const d=typeof v==="string"?new TextEncoder().encode(v):v;return bytesHex(await crypto.subtle.digest("SHA-256",d));}
async function dbRpc<T=unknown>(fn:string,body:Json):Promise<T>{const r=await fetch(`${SUPABASE_URL}/rest/v1/rpc/${fn}`,{method:"POST",headers:{apikey:SERVICE_KEY,authorization:`Bearer ${SERVICE_KEY}`,"content-type":"application/json"},body:JSON.stringify(body)}),text=await r.text();if(!r.ok){console.error("a2_edge_db_rpc_failed",fn,r.status,text.slice(0,400));throw new Error("a2_edge_db_rpc_failed");}return(text?JSON.parse(text):null)as T;}function bearer(req:Request){const h=req.headers.get("authorization")||"";return h.startsWith("Bearer ")?h.slice(7):(req.headers.get("x-a2-runtime-token")||"");}async function requireCapability(req:Request,scope:"rpc"|"emit"|"stream"){const raw=bearer(req);if(raw.length<32||raw.length>512)throw{status:401,code:"runtime_capability_required"}satisfies Fault;const tokenSha=await sha256Hex(raw),v=await dbRpc<any>("h205f22_a2_validate_runtime_access_token_v1",{p_token_sha256:tokenSha,p_required_scope:scope});if(v?.accepted!==true)throw{status:403,code:"runtime_capability_denied"}satisfies Fault;}function rpcBody(fn:string,args:unknown[]):Json{const names=RPC_ARGS[fn];if(!names||args.length!==names.length)throw{status:400,code:"a2_peer_rpc_not_allowed"}satisfies Fault;return Object.fromEntries(names.map((n,i)=>[n,args[i]]));}
async function reconcile(workspaceId:unknown){if(!isUuid(workspaceId))return;try{await dbRpc("h205f22_a2_reconcile_workspace_conflicts_v2",{p_workspace_id:workspaceId});}catch(e){console.error("a2_edge_reconcile_deferred",e instanceof Error?e.message:"error");}}
async function verifyEd25519(pub64:string,hash:string,sig64:string){let pub:Uint8Array,sig:Uint8Array;try{pub=b64(pub64);sig=b64(sig64);}catch{return false;}if(pub.length!==32||sig.length!==64||!isHash64(hash))return false;try{const key=await crypto.subtle.importKey("raw",pub,{name:"Ed25519"},false,["verify"]);return await crypto.subtle.verify({name:"Ed25519"},key,sig,hexBytes(hash));}catch(e){console.error("a2_edge_ed25519_verify_failed",e instanceof Error?e.name:"error");return false;}}
async function emit(body:any){let sig:Uint8Array;try{sig=typeof body?.signature_base64==="string"?b64(body.signature_base64):new Uint8Array();}catch{sig=new Uint8Array();}if(!isUuid(body?.event_id)||!isUuid(body?.session_id)||!Number.isSafeInteger(body?.agent_seq)||body.agent_seq<1||typeof body?.semantic_point!=="string"||body.semantic_point.length<1||body.semantic_point.length>512||typeof body?.event_type!=="string"||body.event_type.length<1||body.event_type.length>64||![0,1,2,3].includes(Number(body?.priority))||!Array.isArray(body?.parent_hashes)||body.parent_hashes.length>64||!body.parent_hashes.every(isHash64)||!isHash64(body?.event_hash)||sig.length!==64||!isHash64(body?.signature_key_fingerprint_sha256))throw{status:400,code:"emit_body_invalid"}satisfies Fault;const identity=await dbRpc<any>("h205f22_a2_ingress_session_identity_v1",{p_session_id:body.session_id});if(identity?.status!=="ACTIVE"||!identity?.lease_expires_at||Date.parse(identity.lease_expires_at)<=Date.now())throw{status:409,code:"a2_ingress_session_not_active"}satisfies Fault;if(identity?.public_key_alg!=="Ed25519"||identity?.key_fingerprint_sha256!==body.signature_key_fingerprint_sha256)throw{status:400,code:"a2_ingress_key_fingerprint_mismatch"}satisfies Fault;let pub:Uint8Array;try{pub=b64(String(identity.public_key_base64||""));}catch{throw{status:500,code:"internal_error"}satisfies Fault;}if(await sha256Hex(pub)!==body.signature_key_fingerprint_sha256)throw{status:500,code:"internal_error"}satisfies Fault;if(!await verifyEd25519(String(identity.public_key_base64),body.event_hash,body.signature_base64))throw{status:400,code:"a2_ingress_ed25519_invalid"}satisfies Fault;return await dbRpc("h205f22_a2_ingress_emit_edge_verified_v1",{p_event_id:body.event_id,p_session_id:body.session_id,p_agent_seq:body.agent_seq,p_semantic_point:body.semantic_point,p_event_type:body.event_type,p_priority:Number(body.priority),p_parent_hashes:body.parent_hashes,p_payload:body.payload&&typeof body.payload==="object"?body.payload:{},p_visibility_proof_id:body.visibility_proof_id??null,p_model_provenance:body.model_provenance&&typeof body.model_provenance==="object"?body.model_provenance:{},p_event_hash:body.event_hash,p_signature_base64:body.signature_base64,p_signature_key_fingerprint_sha256:body.signature_key_fingerprint_sha256,p_ed25519_verified:true,p_edge_verifier_id:EDGE_VERIFIER_ID});}function faultOf(e:unknown):Fault{return e&&typeof e==="object"&&"status"in e&&"code"in e?e as Fault:{status:500,code:"internal_error"};}
Deno.serve(async(req:Request)=>{const url=new URL(req.url);try{if(req.method==="GET"&&pathEnds(url,"/healthz"))return reply({status:"ok",service:"metaengine-a2-ingress-h205f22",verification:"EDGE_WEBCRYPTO_ED25519_THEN_DB_SIGNATURE_BOUND_HMAC_V3",edge_verifier_id:EDGE_VERIFIER_ID,ingress_verifier_id:INGRESS_VERIFIER_ID,runtime_access:"EPHEMERAL_SCOPED_BEARER_CAPABILITY_SHA256_DB_FENCED",conflict_reconciliation:"DB_RESIDENT_ON_ACTION_PLUS_SNAPSHOT_STREAM_POLL",direct_database_access_for_peers:false,vault_secret_exposed:false,canonical:false,authority_effect:false});if(req.method==="POST"&&pathEnds(url,"/v1/a2/rpc")){await requireCapability(req,"rpc");const input=await req.json().catch(()=>({}))as any;if(typeof input?.fn!=="string"||!Array.isArray(input?.args)||!(input.fn in RPC_ARGS))throw{status:400,code:"a2_peer_rpc_not_allowed"}satisfies Fault;if(input.fn==="h205f22_a2_read_snapshot_v1"||input.fn==="h205f22_a2_read_sync_state_v1")await reconcile(input.args[0]);return reply({value:await dbRpc(input.fn,rpcBody(input.fn,input.args))});}if(req.method==="POST"&&pathEnds(url,"/v1/a2/emit")){await requireCapability(req,"emit");return reply(await emit(await req.json().catch(()=>({}))));}if(req.method==="GET"&&pathEnds(url,"/v1/a2/stream")){await requireCapability(req,"stream");const w=url.searchParams.get("workspace_id")||"";if(!isUuid(w))throw{status:400,code:"workspace_id_invalid"}satisfies Fault;await reconcile(w);const a0=Number(url.searchParams.get("after")||0),a=Number.isSafeInteger(a0)&&a0>=0?a0:0,v=await dbRpc<any>("h205f22_a2_read_events_v1",{p_workspace_id:w,p_after_commit_seq:a,p_limit:250}),events=Array.isArray(v?.events)?v.events:[];await new Promise(r=>setTimeout(r,200));return new Response(["retry: 250\n",...events.map((e:any)=>`id: ${Number(e.commit_seq)||0}\ndata: ${JSON.stringify(e)}\n`)].join("\n"),{headers:{"content-type":"text/event-stream","cache-control":"no-cache, no-transform","x-content-type-options":"nosniff"}});}return reply({error:"not_found"},404);}catch(e){const f=faultOf(e);if(f.code==="internal_error")console.error("a2_edge_request_internal_error",e);return reply({error:f.code},f.status);}});
