\set ON_ERROR_STOP on
\i supabase/migrations/20260902074500_compute_unified_recovery_restart_effect_intent_v1.sql
DO $$
declare r jsonb; i jsonb; o jsonb; src text := repeat('a',40);
begin
r := jsonb_build_object('schema','metaengine.compute-unified.recovery-restart-precondition-readback.v1','verified',true,'reason','RECOVERY_RESTART_PRECONDITION_DURABLE_PROOF_VERIFIED','workspace_id','33333333-3333-3333-3333-333333333333','recovery_attempt_id','recovery-intent-1','restart_intent_id','restart-intent-1','lease_id','lease-intent-1','actuator_type','NATIVE_BROWSER_TYPED_ACTUATOR','effect_scope','BROWSER_RESTART','target_client_id','client-intent','target_process_incarnation_id','proc-intent','supervisor_epoch',13,'expected_source_git_commit',src,'recovery_restart_precondition_fingerprint_sha256',repeat('b',64),'preconditions_verified',true,'automatic_retry_allowed',false,'effect_must_be_single_shot',true,'post_effect_readback_required',true,'restart_authorized',false,'wake_replay_authorized',false,'lease_mutation_authorized',false,'promotion_authorized',false,'authority_effect',false);
i := jsonb_build_object('schema','metaengine.compute-unified.restart-effect-intent.v1','workspace_id','33333333-3333-3333-3333-333333333333','recovery_attempt_id','recovery-intent-1','restart_intent_id','restart-intent-1','lease_id','lease-intent-1','actuator_type','NATIVE_BROWSER_TYPED_ACTUATOR','effect_scope','BROWSER_RESTART','target_client_id','client-intent','target_process_incarnation_id','proc-intent','supervisor_epoch',13,'expected_source_git_commit',src,'automatic_retry_allowed',false,'effect_must_be_single_shot',true,'post_effect_readback_required',true,'restart_authorized',false,'wake_replay_authorized',false,'lease_mutation_authorized',false,'promotion_authorized',false,'authority_effect',false);
o := public.h205f22_compute_unified_recovery_restart_effect_intent_v1(r,i);
if not coalesce((o->>'intent_bound')::boolean,false) or o->>'reason' is distinct from 'DURABLE_RECOVERY_RESTART_EFFECT_INTENT_BOUND' or coalesce((o->>'restart_authorized')::boolean,true) or coalesce((o->>'authority_effect')::boolean,true) then raise exception 'valid effect intent rejected or authority leaked'; end if;
begin perform public.h205f22_compute_unified_recovery_restart_effect_intent_v1(r,jsonb_set(i,'{target_process_incarnation_id}','"proc-drift"')); raise exception 'process drift accepted'; exception when others then if sqlerrm='process drift accepted' then raise; end if; end;
begin perform public.h205f22_compute_unified_recovery_restart_effect_intent_v1(r,jsonb_set(i,'{automatic_retry_allowed}','true')); raise exception 'retry intent accepted'; exception when others then if sqlerrm='retry intent accepted' then raise; end if; end;
end $$;
