import assert from 'node:assert/strict';
import test from 'node:test';
import { compileMetaPlan } from '../src/meta-orchestrator-core.mjs';
import {
  MetaOrchestratorActivationOutcomeError,
  MetaOrchestratorNativeProvider,
} from '../src/meta-orchestrator-native-provider.mjs';

const workspace='2de9f84b-7c0a-4091-911c-894ff1d6eaf4';
const roadmap='metaengine-development-os-v1';
const baseline='84a71aaedc49186c24a992f507ca1d3f14767181';
const authority={authority_key:'METAENGINE_DEVOS',roadmap_id:roadmap,active_milestone_key:'DEVOS_IDE_V1',integration_line:'integration/metaengine-development-os-v1',baseline_sha:baseline,alignment_epoch:1,updated_at:'2026-08-31T20:00:00Z'};
const plan=compileMetaPlan({authority,plan_generation:3,nodes:[{point_id:'devos_ide_v1',role:'IMPLEMENTER',objective:'Implement the safe slice.',dependencies:[],required_capabilities:['repo.write'],risk:'HIGH',priority:80,evidence_contract:{required:['roadmap_receipt:mainline_seal'],min_verified:1}}]});
function planState(overrides={}){return{schema:'metaengine.meta-orchestrator.plan-state.v1',found:true,workspace_id:workspace,roadmap_id:roadmap,plan_generation:3,alignment_epoch:1,baseline_sha:baseline,plan_sha256:'a'.repeat(64),plan_spec:plan,state:'ACTIVE',automatic_retry_allowed:false,task_content_authority:false,scheduler_authority:false,browser_authority:false,release_authority:false,authority_effect:false,...overrides}}
function inputs(overrides={}){return{schema:'metaengine.meta-orchestrator.authoritative-inputs.v1',workspace_id:workspace,roadmap_id:roadmap,roadmap_authority:authority,plan_state:planState(),tasks:[],roadmap_receipts:[],capacity:{source:'UNSPECIFIED_FAIL_CLOSED',available_slots:0,authority_effect:false},task_meta_projection_only:true,task_payload_exposed:false,result_summary_exposed:false,scheduler_identity_exposed:false,receipt_summary_exposed:false,receipt_evidence_exposed:false,automatic_retry_allowed:false,task_content_authority:false,scheduler_authority:false,browser_authority:false,release_authority:false,authority_effect:false,...overrides}}
function identity(){const signed=[];return{signed,async ensure(){return{device_id:'11111111-1111-4111-8111-111111111111'}},async deviceHeaders(method,path,body){signed.push({method,path,body});return{'x-test-signature':'ok'}}}}
function json(status,value){return new Response(JSON.stringify(value),{status,headers:{'content-type':'application/json'}})}

test('read path is one signed bounded Meta request with no caller workspace in body',async()=>{const id=identity();const calls=[];const provider=new MetaOrchestratorNativeProvider({identity:id,workspace_id:workspace,baseUrl:'https://provider.test',runtimePath:'/native',fetchImpl:async(url,init)=>{calls.push({url,init});return json(200,inputs())}});const value=await provider.readAuthoritativeInputs({workspace_id:workspace,roadmap_id:roadmap});assert.equal(value.roadmap_id,roadmap);assert.equal(calls.length,1);assert.equal(calls[0].url,'https://provider.test/v1/meta/authoritative-inputs');assert.deepEqual(JSON.parse(calls[0].init.body),{roadmap_id:roadmap});assert.deepEqual(id.signed,[{method:'POST',path:'/native/v1/meta/authoritative-inputs',body:JSON.stringify({roadmap_id:roadmap})}]);assert.equal(provider.snapshot().second_polling_loop,false)});

test('privileged adapter consumes one atomic provider bundle, not five independent reads',async()=>{let reads=0;const id=identity();const provider=new MetaOrchestratorNativeProvider({identity:id,workspace_id:workspace,baseUrl:'https://provider.test',runtimePath:'/native',fetchImpl:async(url)=>{if(url.endsWith('/authoritative-inputs')){reads++;return json(200,inputs())}throw new Error('unexpected_request')}});const bundle=await provider.privilegedAdapter().readAuthoritativeBundle({workspace_id:workspace,roadmap_id:roadmap});assert.equal(reads,1);assert.equal(bundle.snapshot.capacity.available_slots,0);assert.equal(bundle.scheduler_authority,false)});

test('ambiguous activation is reconciled by readback and never retried when effect is present',async()=>{const id=identity();const calls=[];const provider=new MetaOrchestratorNativeProvider({identity:id,workspace_id:workspace,baseUrl:'https://provider.test',runtimePath:'/native',fetchImpl:async(url)=>{calls.push(url);if(url.endsWith('/activate-plan'))throw new Error('connection_lost_after_send');if(url.endsWith('/authoritative-inputs'))return json(200,inputs());throw new Error('unexpected_request')}});const result=await provider.activatePlan({p_workspace_id:workspace,p_roadmap_id:roadmap,p_expected_current_generation:2,p_plan:plan});assert.equal(result.plan_generation,3);assert.deepEqual(calls,['https://provider.test/v1/meta/activate-plan','https://provider.test/v1/meta/authoritative-inputs']);assert.equal(provider.snapshot().last_activation.state,'EFFECT_CONFIRMED');assert.equal(provider.snapshot().last_activation.automatic_retry_allowed,false)});

test('readback proving effect absent marks retryable but performs no hidden activation retry',async()=>{const id=identity();const calls=[];const prior=compileMetaPlan({authority,plan_generation:2,nodes:plan.nodes});const provider=new MetaOrchestratorNativeProvider({identity:id,workspace_id:workspace,baseUrl:'https://provider.test',runtimePath:'/native',fetchImpl:async(url)=>{calls.push(url);if(url.endsWith('/activate-plan'))throw new Error('connection_lost_before_result');if(url.endsWith('/authoritative-inputs'))return json(200,inputs({plan_state:planState({plan_generation:2,plan_spec:prior})}));throw new Error('unexpected_request')}});await assert.rejects(()=>provider.activatePlan({p_workspace_id:workspace,p_roadmap_id:roadmap,p_expected_current_generation:2,p_plan:plan}),(error)=>error instanceof MetaOrchestratorActivationOutcomeError&&error.effect_state==='EFFECT_ABSENT'&&error.automatic_retry_allowed===true);assert.deepEqual(calls,['https://provider.test/v1/meta/activate-plan','https://provider.test/v1/meta/authoritative-inputs']);assert.equal(provider.snapshot().last_activation.state,'EFFECT_ABSENT')});

test('409 generation fence is definitive and is never retried or readback-replayed',async()=>{const id=identity();let calls=0;const provider=new MetaOrchestratorNativeProvider({identity:id,workspace_id:workspace,baseUrl:'https://provider.test',runtimePath:'/native',fetchImpl:async()=>{calls++;return json(409,{error:'meta_plan_activation_fenced',reason:'meta_plan_generation_fenced'})}});await assert.rejects(()=>provider.activatePlan({p_workspace_id:workspace,p_roadmap_id:roadmap,p_expected_current_generation:2,p_plan:plan}),(error)=>error.effect_state==='FENCED'&&error.automatic_retry_allowed===false);assert.equal(calls,1)});

test('workspace and zero-authority fences fail before network',async()=>{const id=identity();let calls=0;const provider=new MetaOrchestratorNativeProvider({identity:id,workspace_id:workspace,baseUrl:'https://provider.test',runtimePath:'/native',fetchImpl:async()=>{calls++;return json(500,{})}});await assert.rejects(()=>provider.readAuthoritativeInputs({workspace_id:'11111111-1111-4111-8111-111111111111',roadmap_id:roadmap}),/workspace_drift/);await assert.rejects(()=>provider.activatePlan({p_workspace_id:workspace,p_roadmap_id:roadmap,p_expected_current_generation:2,p_plan:{...plan,scheduler_authority:true}}),/zero_authority/);assert.equal(calls,0)});
