import assert from 'node:assert/strict';
import test from 'node:test';
import { readFile } from 'node:fs/promises';
import { createMetaSupervisorRoutes } from '../supabase/a2-browser-native-supervisor-v1/meta-routes.mjs';

const workspaceId='2de9f84b-7c0a-4091-911c-894ff1d6eaf4';
const roadmapId='metaengine-development-os-v1';
const baseline='84a71aaedc49186c24a992f507ca1d3f14767181';
const taskId='98903ffd-dc3f-4a3e-ab09-55931c5100a9';
const plan={schema:'metaengine.meta-orchestrator.plan.v1',roadmap_id:roadmapId,plan_generation:3,alignment_epoch:1,baseline_sha:baseline,task_content_authority:false,scheduler_authority:false,browser_authority:false,release_authority:false,authority_effect:false,nodes:[]};
function bundle(overrides={}){return{schema:'metaengine.meta-orchestrator.authoritative-inputs.v1',workspace_id:workspaceId,roadmap_id:roadmapId,roadmap_authority:{authority_key:'METAENGINE_DEVOS',roadmap_id:roadmapId,active_milestone_key:'DEVOS_IDE_V1',integration_line:'integration/metaengine-development-os-v1',baseline_sha:baseline,alignment_epoch:1},plan_state:{schema:'metaengine.meta-orchestrator.plan-state.v1',found:true,workspace_id:workspaceId,roadmap_id:roadmapId,plan_generation:3,plan_spec:plan,state:'ACTIVE',automatic_retry_allowed:false,task_content_authority:false,scheduler_authority:false,browser_authority:false,release_authority:false,authority_effect:false},tasks:[{task_id:taskId,point_id:'devos_ide_v1',role:'IMPLEMENTER',base_sha:baseline,state:'COMPLETED',lease_generation:7,updated_at:'2026-08-31T19:40:00Z',authority_effect:false,task_spec:{meta_orchestrator:{roadmap_id:roadmapId,alignment_epoch:'1',plan_generation:'3',parent_plan_point:'devos_ide_v1',parent_point_id:null}}}],roadmap_receipts:[],capacity:{source:'UNSPECIFIED_FAIL_CLOSED',available_slots:0,authority_effect:false},task_meta_projection_only:true,task_payload_exposed:false,result_summary_exposed:false,scheduler_identity_exposed:false,receipt_summary_exposed:false,receipt_evidence_exposed:false,automatic_retry_allowed:false,task_content_authority:false,scheduler_authority:false,browser_authority:false,release_authority:false,authority_effect:false,...overrides}}
function schedulerCapacity(overrides={}){return{schema:'metaengine.devos.scheduler-capacity.v1',workspace_id:workspaceId,state:'FRESH',source:'DEVOS_SCHEDULER_SNAPSHOT',available_slots:2,by_role:{IMPLEMENTER:1,CRITIC:1},observed_at:'2026-08-31T20:00:00Z',freshness_horizon_seconds:45,transport_admission:'ACTIVE_EXACT_PROOF_V1',scheduler_source:'NATIVE_SUPERVISOR_HEARTBEAT',scheduler_policy:'IDLE_ROLE_FAIR_SHARE_V1',automatic_retry_allowed:false,authority_effect:false,...overrides}}
const request=(method='POST')=>({method});
async function body(response){return JSON.parse(await response.text())}

test('non-meta path is ignored and missing authenticated client fails closed',async()=>{const routes=createMetaSupervisorRoutes({workspaceId,rpc:async()=>{throw new Error('must_not_call')}});assert.equal(await routes({req:request(),path:'/v1/devos/cycle',body:{},clientId:'device'}),null);assert.equal((await routes({req:request(),path:'/v1/meta/authoritative-inputs',body:{roadmap_id:roadmapId},clientId:''})).status,401)});

test('authoritative input route fixes workspace server-side and joins read-only projections',async()=>{const calls=[];const routes=createMetaSupervisorRoutes({workspaceId,rpc:async(name,args)=>{calls.push({name,args});if(name==='meta_orchestrator_authoritative_inputs_v1')return bundle();if(name==='devos_fleet_capacity_snapshot_v1')return schedulerCapacity();throw new Error('unexpected_rpc')}});const response=await routes({req:request(),path:'/v1/meta/authoritative-inputs',body:{roadmap_id:roadmapId},clientId:'device'});assert.equal(response.status,200);assert.equal((await body(response)).capacity.available_slots,2);assert.equal(calls.length,2)});

test('task admission route accepts only roadmap generation and point and fixes workspace server-side',async()=>{const calls=[];const routes=createMetaSupervisorRoutes({workspaceId,rpc:async(name,args)=>{calls.push({name,args});return{schema:'metaengine.meta-orchestrator.task-admission.v1',workspace_id:workspaceId,roadmap_id:roadmapId,alignment_epoch:1,plan_generation:3,point_id:'devos_ide_v1',parent_plan_point:'devos_ide_v1',variant:'PRIMARY',task_id:taskId,duplicate:false,task_spec_sha256:'a'.repeat(64),task_payload_returned:false,scheduler_identity_returned:false,automatic_retry_allowed:false,task_content_authority:false,scheduler_authority:false,browser_authority:false,release_authority:false,authority_effect:false}}});const response=await routes({req:request(),path:'/v1/meta/admit-task',body:{roadmap_id:roadmapId,plan_generation:3,point_id:'devos_ide_v1'},clientId:'device'});assert.equal(response.status,200);assert.deepEqual(calls,[{name:'meta_orchestrator_task_admit_v1',args:{p_workspace_id:workspaceId,p_roadmap_id:roadmapId,p_plan_generation:3,p_point_id:'devos_ide_v1'}}]);const out=await body(response);assert.equal(out.task_id,taskId);assert.equal(out.task_payload_returned,false)});

test('task admission rejects privileged task content before RPC',async()=>{let calls=0;const routes=createMetaSupervisorRoutes({workspaceId,rpc:async()=>{calls++;return{}}});const response=await routes({req:request(),path:'/v1/meta/admit-task',body:{roadmap_id:roadmapId,plan_generation:3,point_id:'devos_ide_v1',objective:'override',role:'IMPLEMENTER',task_spec:{}},clientId:'device'});assert.equal(response.status,400);assert.equal(calls,0);assert.equal((await body(response)).error,'meta_task_admission_fields_forbidden')});

test('stale or invalid admission is fenced once with no route retry',async()=>{let calls=0;const routes=createMetaSupervisorRoutes({workspaceId,rpc:async()=>{calls++;throw new Error('meta_admit_active_plan_missing')}});const response=await routes({req:request(),path:'/v1/meta/admit-task',body:{roadmap_id:roadmapId,plan_generation:3,point_id:'devos_ide_v1'},clientId:'device'});assert.equal(response.status,409);assert.equal(calls,1);assert.equal((await body(response)).automatic_retry_allowed,false)});

test('caller cannot override workspace and malformed/raw provider rows are rejected',async()=>{let calls=0;const routes=createMetaSupervisorRoutes({workspaceId,rpc:async(name)=>{calls++;if(name==='meta_orchestrator_authoritative_inputs_v1')return bundle({tasks:[{...bundle().tasks[0],lease_agent_id:'secret'}]});return schedulerCapacity()}});const denied=await routes({req:request(),path:'/v1/meta/authoritative-inputs',body:{roadmap_id:roadmapId,workspace_id:'11111111-1111-4111-8111-111111111111'},clientId:'device'});assert.equal(denied.status,400);assert.equal(calls,0);await assert.rejects(()=>routes({req:request(),path:'/v1/meta/authoritative-inputs',body:{roadmap_id:roadmapId},clientId:'device'}),/meta_provider_task_forbidden/)});

test('plan activation has one fenced RPC and never retries stale generation',async()=>{let calls=0;const routes=createMetaSupervisorRoutes({workspaceId,rpc:async()=>{calls++;throw new Error('meta_plan_generation_fenced')}});const response=await routes({req:request(),path:'/v1/meta/activate-plan',body:{roadmap_id:roadmapId,expected_current_generation:2,plan},clientId:'device'});assert.equal(response.status,409);assert.equal(calls,1)});

test('SQL durable admission reconstructs task from ACTIVE plan and calls the existing enqueue only inside DB boundary',async()=>{const sql=await readFile(new URL('../../../supabase/migrations/20260901001500_meta_orchestrator_task_admission_v1.sql',import.meta.url),'utf8');assert.match(sql,/state = 'ACTIVE'/);assert.match(sql,/jsonb_array_elements/);assert.match(sql,/devos_fleet_enqueue_v1/);assert.match(sql,/meta-task-admit:/);assert.match(sql,/task_payload_returned',false/);assert.match(sql,/scheduler_identity_returned',false/);for(const forbidden of ['p_objective','p_role text','p_task_spec','p_agent','p_tab','p_target','p_lease'])assert.equal(sql.toLowerCase().includes(forbidden.toLowerCase()),false)});

test('SQL capacity projection mirrors ACTIVE transport admission without scheduling work',async()=>{const sql=await readFile(new URL('../../../supabase/migrations/20260831204000_devos_fleet_scheduler_capacity_snapshot_v1.sql',import.meta.url),'utf8');assert.match(sql,/TRANSPORT_PROOF_REQUIRED/);assert.match(sql,/lifecycle_state' <> 'ACTIVE'/);assert.match(sql,/devos_fleet_claim_h205f22/);assert.match(sql,/DEVOS_SCHEDULER_SNAPSHOT/);for(const forbidden of ['devos_fleet_lease_v1','devos_fleet_enqueue_v1','devos_fleet_mark_running_v1','devos_fleet_complete_v1'])assert.equal(sql.toLowerCase().includes(forbidden.toLowerCase()),false)});

test('native supervisor wiring keeps Meta routes behind existing device authentication',async()=>{const source=await readFile(new URL('../supabase/a2-browser-native-supervisor-v1/index.ts',import.meta.url),'utf8');const auth=source.indexOf('authenticateDevice(req,canonicalPath,bodyText)');const meta=source.indexOf('await metaRoutes(');assert.ok(auth>=0&&meta>auth);assert.equal(source.includes('setInterval'),false);assert.equal(source.includes('setTimeout'),false)});
