import test from 'node:test';
import assert from 'node:assert/strict';
import { compileMetaPlan, deriveProgressLedger, reconcileMetaOrchestrator, assertZeroAuthorityMetaOutput } from '../src/meta-orchestrator-core.mjs';
import { metaTaskProposalToDevosEnqueue, buildMetaCapacityProposal } from '../src/meta-orchestrator-devos-adapter.mjs';

const SHA='d91e94b307ed60e890aabc53a2678a8ae9c6a79d';
const WS='11111111-1111-4111-8111-111111111111';
const authority={roadmap_id:'compute-unified-v1',active_milestone_key:'META_ORCHESTRATOR_V1',integration_line:'work/browser-orchestra-hotfix-convergence-v1',baseline_sha:SHA,alignment_epoch:7};
const node=(point_id,overrides={})=>({point_id,role:'IMPLEMENTER',objective:`Implement ${point_id}`,required_capabilities:['capability.repo_write'],evidence_contract:{required:['ci_green','commit_bound'],min_verified:2},...overrides});
const plan=(nodes=[node('meta.core')])=>compileMetaPlan({authority,plan_generation:3,nodes});
const reconcile=(p,extra={})=>reconcileMetaOrchestrator({plan:p,observed_alignment_epoch:7,observed_plan_generation:3,leader:{expected_epoch:4,observed_epoch:4},tasks:[],evidence:[],capacity:{available_slots:4},policy:{max_parallel_proposals:8},...extra});

test('compiles exact baseline DAG with zero authority',()=>{const p=plan();assert.equal(p.baseline_sha,SHA);assert.equal(p.authority_effect,false);assert.equal(p.scheduler_authority,false);});
test('rejects duplicate points',()=>assert.throws(()=>plan([node('meta.core'),node('meta.core')]),/duplicate_point/));
test('rejects missing dependency',()=>assert.throws(()=>plan([node('meta.child',{dependencies:['meta.missing']})]),/dependency_missing/));
test('rejects dependency cycle',()=>assert.throws(()=>plan([node('meta.a',{dependencies:['meta.b']}),node('meta.b',{dependencies:['meta.a']})]),/dependency_cycle/));
test('rejects baseline drift',()=>assert.throws(()=>plan([node('meta.core',{base_sha:'a'.repeat(40)})]),/base_sha_drift/));
test('rejects scheduler identity in plan node',()=>assert.throws(()=>plan([node('meta.core',{agent_id:'agent_12345678'})]),/scheduler_owned_field_forbidden/));
test('normalizes capabilities and roles without agent identity',()=>{const p=plan([node('meta.core',{role:'researcher',required_capabilities:['capability.web','capability.web','capability.repo_read']})]);assert.deepEqual(p.nodes[0].required_capabilities,['capability.repo_read','capability.web']);assert.equal(p.nodes[0].role,'RESEARCHER');});

test('unscheduled node is pending',()=>assert.equal(deriveProgressLedger({plan:plan(),tasks:[],evidence:[]}).rows[0].state,'PENDING'));
test('completed task is not verified without evidence',()=>assert.equal(deriveProgressLedger({plan:plan(),tasks:[{point_id:'meta.core',state:'COMPLETED'}],evidence:[]}).rows[0].state,'EVIDENCE_PENDING'));
test('completed task becomes verified only from explicit zero-authority evidence',()=>{const p=plan();const ev=[{point_id:'meta.core',kind:'ci_green',verified:true,authority_effect:false},{point_id:'meta.core',kind:'commit_bound',verified:true,authority_effect:false}];assert.equal(deriveProgressLedger({plan:p,tasks:[{point_id:'meta.core',state:'COMPLETED'}],evidence:ev}).rows[0].state,'VERIFIED');});
test('authority-bearing evidence is ignored',()=>{const p=plan();const ev=[{point_id:'meta.core',kind:'ci_green',verified:true,authority_effect:true},{point_id:'meta.core',kind:'commit_bound',verified:true,authority_effect:false}];assert.equal(deriveProgressLedger({plan:p,tasks:[{point_id:'meta.core',state:'COMPLETED'}],evidence:ev}).rows[0].state,'EVIDENCE_PENDING');});
test('ambiguous is first-class state',()=>assert.equal(deriveProgressLedger({plan:plan(),tasks:[{point_id:'meta.core',state:'AMBIGUOUS'}],evidence:[]}).rows[0].state,'AMBIGUOUS'));

test('leader epoch drift fences without work proposal',()=>{const r=reconcile(plan(),{leader:{expected_epoch:4,observed_epoch:3}});assert.equal(r.state,'FENCED');assert.equal(r.actions[0].type,'NOOP');});
test('roadmap epoch drift requests reasoning not dispatch',()=>{const r=reconcileMetaOrchestrator({plan:plan(),observed_alignment_epoch:8,observed_plan_generation:3,leader:{expected_epoch:1,observed_epoch:1},tasks:[],evidence:[],capacity:{available_slots:2}});assert.equal(r.actions[0].type,'REQUEST_REASONING');});
test('plan generation drift requests reasoning',()=>{const r=reconcileMetaOrchestrator({plan:plan(),observed_alignment_epoch:7,observed_plan_generation:4,leader:{expected_epoch:1,observed_epoch:1},tasks:[],evidence:[],capacity:{available_slots:2}});assert.equal(r.actions[0].type,'REQUEST_REASONING');});
test('ambiguous effect requests reconciliation and never retry',()=>{const r=reconcile(plan(),{tasks:[{point_id:'meta.core',state:'AMBIGUOUS'}]});assert.equal(r.actions[0].type,'REQUEST_RECONCILIATION');assert.equal(r.actions[0].automatic_retry_allowed,false);assert.equal(r.actions.some(a=>a.type.includes('RETRY')),false);});
test('missing completion evidence requests evidence',()=>{const r=reconcile(plan(),{tasks:[{point_id:'meta.core',state:'COMPLETED'}]});assert.equal(r.actions[0].type,'REQUEST_EVIDENCE');});
test('dependency waits until predecessor verified',()=>{const p=plan([node('meta.a'),node('meta.b',{dependencies:['meta.a']})]);const r=reconcile(p,{capacity:{available_slots:4}});assert.deepEqual(r.actions.filter(a=>a.type==='PROPOSE_TASK').map(a=>a.point_id),['meta.a']);});
test('verified dependency unlocks successor',()=>{const p=plan([node('meta.a'),node('meta.b',{dependencies:['meta.a']})]);const tasks=[{point_id:'meta.a',state:'COMPLETED'}];const evidence=[{point_id:'meta.a',kind:'ci_green',verified:true,authority_effect:false},{point_id:'meta.a',kind:'commit_bound',verified:true,authority_effect:false}];const r=reconcile(p,{tasks,evidence,capacity:{available_slots:4}});assert.deepEqual(r.actions.filter(a=>a.type==='PROPOSE_TASK').map(a=>a.point_id),['meta.b']);});
test('failed dependency triggers semantic replan, not successor task',()=>{const p=plan([node('meta.a'),node('meta.b',{dependencies:['meta.a']})]);const r=reconcile(p,{tasks:[{point_id:'meta.a',state:'FAILED'}]});assert.equal(r.state,'BLOCKED');assert.equal(r.actions[0].type,'REQUEST_REASONING');});
test('zero capacity requests capacity rather than dispatch',()=>{const r=reconcile(plan(),{capacity:{available_slots:0}});assert.equal(r.state,'CAPACITY_WAIT');assert.equal(r.actions[0].type,'REQUEST_CAPACITY');});
test('adaptive fanout obeys proposal bound',()=>{const p=plan([node('meta.a'),node('meta.b'),node('meta.c')]);const r=reconcile(p,{capacity:{available_slots:10},policy:{max_parallel_proposals:2}});assert.equal(r.actions.length,2);});
test('critical risk adds critic and falsifier within budget',()=>{const p=plan([node('meta.core',{risk:'CRITICAL'})]);const r=reconcile(p,{capacity:{available_slots:4},policy:{max_parallel_proposals:4}});assert.deepEqual(r.actions.map(a=>a.role),['IMPLEMENTER','CRITIC','FALSIFIER']);});
test('high risk adds critic',()=>{const p=plan([node('meta.core',{risk:'HIGH'})]);const r=reconcile(p,{capacity:{available_slots:4},policy:{max_parallel_proposals:4}});assert.deepEqual(r.actions.map(a=>a.role),['IMPLEMENTER','CRITIC']);});
test('active semantic point is not duplicated',()=>{const r=reconcile(plan(),{tasks:[{point_id:'meta.core',state:'RUNNING'}],capacity:{available_slots:4}});assert.equal(r.actions.some(a=>a.type==='PROPOSE_TASK'),false);});
test('fully verified plan converges with no authority effect',()=>{const p=plan();const tasks=[{point_id:'meta.core',state:'COMPLETED'}];const evidence=[{point_id:'meta.core',kind:'ci_green',verified:true,authority_effect:false},{point_id:'meta.core',kind:'commit_bound',verified:true,authority_effect:false}];const r=reconcile(p,{tasks,evidence});assert.equal(r.state,'CONVERGED');assert.equal(r.authority_effect,false);});
test('all emitted output recursively satisfies zero-authority contract',()=>assert.equal(assertZeroAuthorityMetaOutput(reconcile(plan())),true));

test('task proposal maps only to existing enqueue RPC',()=>{const a=reconcile(plan()).actions.find(x=>x.type==='PROPOSE_TASK');const q=metaTaskProposalToDevosEnqueue(a,{workspace_id:WS});assert.equal(q.rpc,'devos_fleet_enqueue_v1');assert.equal(q.scheduler_admission_required,true);assert.equal(q.authority_effect,false);assert.equal(q.args.p_spec.automatic_retry_allowed,false);});
test('enqueue proposal contains no scheduler-owned incarnation fields',()=>{const a=reconcile(plan()).actions.find(x=>x.type==='PROPOSE_TASK');const q=metaTaskProposalToDevosEnqueue(a,{workspace_id:WS});const body=JSON.stringify(q.args.p_spec);for(const key of ['agent_id','tab_id','target_id','lease_generation'])assert.equal(body.includes(`"${key}"`),false);});
test('enqueue idempotency is plan-generation stable',()=>{const a=reconcile(plan()).actions.find(x=>x.type==='PROPOSE_TASK');const q1=metaTaskProposalToDevosEnqueue(a,{workspace_id:WS});const q2=metaTaskProposalToDevosEnqueue(a,{workspace_id:WS});assert.equal(q1.args.p_key,q2.args.p_key);});
test('adapter rejects fabricated scheduler field',()=>{const a={...reconcile(plan()).actions.find(x=>x.type==='PROPOSE_TASK'),agent_id:'agent_12345678'};assert.throws(()=>metaTaskProposalToDevosEnqueue(a,{workspace_id:WS}),/scheduler_field_forbidden|action_invalid/);});
test('capacity proposal uses existing fleet reconcile and no second scheduler loop',()=>{const r=reconcile(plan(),{capacity:{available_slots:0}});const q=buildMetaCapacityProposal({reconcile_result:r,autonomy_target:{target_agents:12,authority_effect:false}});assert.equal(q.execute_via_existing_fleet_reconcile,true);assert.equal(q.second_scheduler_loop,false);});
