create table if not exists destruktion_meta.compute_fabric_a2_macroblock_h205f22 (
 macroblock_id uuid primary key default gen_random_uuid(), workspace_id uuid not null references destruktion_meta.compute_fabric_a2_workspace_h205f22(workspace_id), macroblock_key text not null, title text not null,
 start_snapshot_sha256 text not null check(start_snapshot_sha256~'^[0-9a-f]{64}$'), plan jsonb not null check(jsonb_typeof(plan)='object' and jsonb_typeof(plan->'nodes')='array'), plan_sha256 text not null check(plan_sha256~'^[0-9a-f]{64}$'),
 state text not null default 'ACK_OPEN' check(state in('ACK_OPEN','SEALED','EXECUTING','HARD_GATE','COMPLETED','ABANDONED')),
 gpt_ack_sha256 text check(gpt_ack_sha256 is null or gpt_ack_sha256~'^[0-9a-f]{64}$'), glm_ack_sha256 text check(glm_ack_sha256 is null or glm_ack_sha256~'^[0-9a-f]{64}$'), current_hard_gate jsonb,
 hard_gate_sha256 text check(hard_gate_sha256 is null or hard_gate_sha256~'^[0-9a-f]{64}$'), gpt_gate_ack_sha256 text check(gpt_gate_ack_sha256 is null or gpt_gate_ack_sha256~'^[0-9a-f]{64}$'), glm_gate_ack_sha256 text check(glm_gate_ack_sha256 is null or glm_gate_ack_sha256~'^[0-9a-f]{64}$'),
 created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(), canonical boolean not null default false check(canonical=false), authority_effect boolean not null default false check(authority_effect=false), unique(workspace_id,macroblock_key));
create unique index if not exists compute_fabric_a2_macroblock_one_active_h205f22 on destruktion_meta.compute_fabric_a2_macroblock_h205f22(workspace_id) where state in('ACK_OPEN','SEALED','EXECUTING','HARD_GATE');
create table if not exists destruktion_meta.compute_fabric_a2_macroblock_node_h205f22 (
 macroblock_id uuid not null references destruktion_meta.compute_fabric_a2_macroblock_h205f22(macroblock_id) on delete cascade, node_key text not null, ordinal integer not null check(ordinal>=0), milestone_key text,
 execution_class text not null check(execution_class in('A_DETERMINISTIC','B_BOUNDED','C_SEMANTIC')), depends_on text[] not null default '{}'::text[], action jsonb not null check(jsonb_typeof(action)='object'), hard_gate_after boolean not null default false,
 state text not null default 'PENDING' check(state in('PENDING','READY','RUNNING','WAITING_EXTERNAL','SUCCEEDED','FAILED','SKIPPED')), executor_binding jsonb, authority_binding jsonb, evidence jsonb, result_sha256 text check(result_sha256 is null or result_sha256~'^[0-9a-f]{64}$'),
 started_at timestamptz, finished_at timestamptz, created_at timestamptz not null default clock_timestamp(), updated_at timestamptz not null default clock_timestamp(), canonical boolean not null default false check(canonical=false), authority_effect boolean not null default false check(authority_effect=false), primary key(macroblock_id,node_key));
create index if not exists compute_fabric_a2_macroblock_node_state_h205f22 on destruktion_meta.compute_fabric_a2_macroblock_node_h205f22(macroblock_id,state,ordinal);
create or replace function destruktion_meta.compute_fabric_a2_macroblock_direct_write_guard_h205f22() returns trigger language plpgsql security definer set search_path='pg_catalog','destruktion_meta' as $$begin if current_setting('metaengine.a2_macroblock_rpc',true) is distinct from 'on' then raise exception 'a2_macroblock_direct_write_denied'; end if; if tg_op='DELETE' then raise exception 'a2_macroblock_delete_denied'; end if; new.canonical:=false; new.authority_effect:=false; new.updated_at:=clock_timestamp(); return new; end$$;
drop trigger if exists compute_fabric_a2_macroblock_guard_h205f22 on destruktion_meta.compute_fabric_a2_macroblock_h205f22; create trigger compute_fabric_a2_macroblock_guard_h205f22 before insert or update or delete on destruktion_meta.compute_fabric_a2_macroblock_h205f22 for each row execute function destruktion_meta.compute_fabric_a2_macroblock_direct_write_guard_h205f22();
drop trigger if exists compute_fabric_a2_macroblock_node_guard_h205f22 on destruktion_meta.compute_fabric_a2_macroblock_node_h205f22; create trigger compute_fabric_a2_macroblock_node_guard_h205f22 before insert or update or delete on destruktion_meta.compute_fabric_a2_macroblock_node_h205f22 for each row execute function destruktion_meta.compute_fabric_a2_macroblock_direct_write_guard_h205f22();
revoke all on destruktion_meta.compute_fabric_a2_macroblock_h205f22 from public,anon,authenticated,service_role; revoke all on destruktion_meta.compute_fabric_a2_macroblock_node_h205f22 from public,anon,authenticated,service_role;
