-- ─────────────────────────────────────────────────────────────────────────────
-- ME2 DEPRECATED-реестр RPC (R52, план electron-rebuild §D8) — ДЛЯ ОПЕРАТОРА.
-- Источник: живой OpenAPI /rest/v1/ (243 функции). Роль (план §D8): Supabase =
-- federation/evidence/control-plane; SQLite = истина. FREEZE = пометить, НЕ удалять
-- (старые циклы могут ссылаться друг на друга; удаление — отдельное решение оператора).
-- Применение: psql $DATABASE_URL -f 0002-rpc-registry.sql  (после create table).
-- ─────────────────────────────────────────────────────────────────────────────

create table if not exists public.me2_rpc_registry_h205f22 (
  rpc_name   text primary key,
  tier       text not null check (tier in ('ACTIVE','CONTROL_PLANE','FREEZE')),
  decided_at timestamptz not null default now(),
  decided_by text not null default 'R52-registry',
  note       text
);
alter table public.me2_rpc_registry_h205f22 enable row level security;

-- ACTIVE (24): единая система — aop1_* (vercel gateway), supervisor_mesh_*, evidence_*
insert into public.me2_rpc_registry_h205f22 (rpc_name,tier,note) values
  ('h205f22_a2_supervisor_mesh_heartbeat_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_a2_supervisor_mesh_register_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_a2_supervisor_mesh_sync_legacy_h205f22','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_a2_supervisor_mesh_sync_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_complete_run_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_consume_bootstrap_bundle_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_defer_run_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_issue_deploy_bundle_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_lease_run_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_reap_expired_exhausted_leases_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_rearm_authority_rebind_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_recover_exhausted_analyst_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_register_runtime_endpoint_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_signal_role_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_signal_run_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_signal_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_snapshot_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_store_vercel_gateway_key_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_supervisor_adopt_active_claim_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_supervisor_rearm_exhausted_analyst_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_supervisor_return_authority_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_vercel_gateway_bootstrap_input_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_vercel_gateway_key_receipt_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)'),
  ('h205f22_aop1_vercel_gateway_runtime_secret_v1','ACTIVE','active: unified ME2 system (R49-R52 contract)') on conflict (rpc_name) do update set tier=excluded.tier, note=excluded.note;

-- CONTROL_PLANE (37): живые таблицы control-plane (enrollment/lease/command/nonce/pairing)
insert into public.me2_rpc_registry_h205f22 (rpc_name,tier,note) values
  ('devos_supervisor_admission_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_device_activate_approved_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_device_consume_nonce_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_device_consume_nonce_v2','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_device_enroll_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_device_rotate_embedded_bootstrap_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_bind_effect_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_complete_batch_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_complete_v4','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_complete_v5','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_continue_if_needed_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_enqueue_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_enqueue_v2','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_enqueue_v3','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_issue_developer_emergency_update_','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_issue_mesh_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_issue_native_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_batch_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_bootstrap_v3','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_control_v4','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_emergency_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_v2','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_browser_supervisor_lease_v3','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_workspace_binding_readback_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_workspace_binding_register_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_workspace_binding_retire_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_a2_workspace_binding_snapshot_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_development_gate_policy_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_supervisor_status','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_worker_enrollment_admit_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_worker_enrollment_bind_auth_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_worker_enrollment_prepare_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_worker_enrollment_record_probe_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_worker_enrollment_record_probe_v2','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('h205f22_worker_enrollment_revoke_v1','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision'),
  ('metaengine_record_peer_health_h205f22','CONTROL_PLANE','control-plane-live: backs live tables; keep until фаза D decision') on conflict (rpc_name) do update set tier=excluded.tier, note=excluded.note;

-- FREEZE (182): старые циклы (duel/macroblock/fabric/fail_run/legacy a2_*) — пометить, не удалять
insert into public.me2_rpc_registry_h205f22 (rpc_name,tier,note) values
  ('coordination_read_barrier_h205f22','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_environment_reset_legacy_h205f22','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_environment_reset_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_environment_resume_legacy_h205f22','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_environment_resume_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_environment_state_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_capacity_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_complete_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_enqueue_legacy_admission_h205f22','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_enqueue_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_lease_legacy_h205f22','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_lease_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_mark_running_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_reconcile_ambiguous_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_reconcile_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_transport_promotion_lease_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_fleet_transport_promotion_release_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_meta_dispatch_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_meta_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_recovery_debt_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_roadmap_assert_alignment_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_roadmap_baseline_sync_commit_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_roadmap_baseline_sync_read_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_roadmap_contract_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_runtime_capabilities_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_transport_promotion_lease_legacy_admission_h205f22','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_transport_promotion_lease_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('devos_transport_promotion_release_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_abandon_sync_round_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_acceptance_consume_oidc_jti_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_attach_duel_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_browser_cognitive_accept_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_chat_bridge_remote_transition_v3','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_chat_bridge_remote_try_lease_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_clear_provider_block_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_close_peer_session_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_create_visibility_proof_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_emit_agent_event_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_emit_agent_event_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_emit_agent_event_v3','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_heartbeat_peer_session_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_ingress_emit_edge_verified_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_ingress_session_identity_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_commitment_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_read_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_adopt_legacy_reveal_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_challenge_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_commit_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_decide_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_direct_resolution_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_open_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_read_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_round_reveal_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_interactive_submit_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_issue_runtime_access_token_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_join_sync_round_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_lookup_peer_session_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_abandon_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_ack_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_bind_node_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_gate_ack_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_gate_resume_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_node_result_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_open_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_read_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_macroblock_start_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_next_agent_seq_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_open_conflict_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_open_workspace_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_prepare_event_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_event_ancestry_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_events_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_frontier_at_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_frontier_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_sync_state_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_read_visibility_proof_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_reap_stale_sessions_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_reconcile_workspace_conflicts_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_register_peer_session_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_resolve_conflict_from_duel_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_resolve_conflict_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_revoke_runtime_access_token_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_update_cursor_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_a2_validate_runtime_access_token_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_admit_runtime_candidate','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_attest_worker_capability_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_cat_fetch_target_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_commit_cat_fetch_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_dependency_status','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_complete_lockstep_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_complete_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_create_lockstep_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_create_peer_relay_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_create_same_point_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_create_sovereign_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_create_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_finalize_same_point_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_lease_autonomous_peer_relay_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_lease_lockstep_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_lease_target_lockstep_v3','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_lease_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_list_peer_relay_pending_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_read_lockstep_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_read_peer_relay_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_read_same_point_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_record_event_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_release_autonomous_peer_relay_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_submit_pair_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_submit_pair_v3','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_submit_peer_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_duel_submit_rebut_finalize_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_execution_contract_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fabric_plan_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fabric_status_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fabric_status_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fail_run','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fail_run_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fail_run_v3','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fail_run_v4','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fail_run_v5','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_fail_run_v6','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_health','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_heartbeat','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_heartbeat_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_ingest_capability_result_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_lease_check','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_promote_cat_fetch_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_publish_event','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_pull_run','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_pull_run_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_read_signature_verification_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_record_benchmark_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_record_lineage_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_record_signature_verification_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_resolve_capabilities_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_run_status','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_runtime_affinity_status','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_submit_run','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_submit_run_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_trust_plane_health_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_w1_admission_candidate_readback_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_worker_capability_status','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_worker_capability_status_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_worker_linux_safety_observe_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('h205f22_worker_resource_heartbeat_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_authoritative_inputs_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_controller_lease_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_frontier_admit_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_frontier_admit_v2','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_plan_activate_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_plan_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('meta_orchestrator_task_admit_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_adaptation_receipt_get_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_candidate_status_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_claim_task_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_conflict_status_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_epoch_status_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_finalization_get_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_finalize_epoch_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_open_epoch_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_progress_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_propose_integration_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_publish_snapshot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_reclaim_slot_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_record_adaptation_receipt_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_register_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_release_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_seed_role_genome_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_seed_task_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_session_status_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_slot_catalog_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_status_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_submit_candidate_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_submit_conflict_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_submit_review_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_sync_snapshot_get_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_task_dependencies_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_federation_task_get_v1','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision'),
  ('metaengine_h205f22_custom_access_token_hook','FREEZE','frozen: legacy cycle; DEPRECATED mark, do NOT drop without operator decision') on conflict (rpc_name) do update set tier=excluded.tier, note=excluded.note;

-- Сводка реестра
select tier, count(*) from public.me2_rpc_registry_h205f22 group by tier order by tier;
