const SUPABASE_URL=(Deno.env.get('SUPABASE_URL')||'').replace(/\/+$/,'');
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';
const WORKSPACE_ID='2de9f84b-7c0a-4091-911c-894ff1d6eaf4';
const DEVICE_TABLE='compute_fabric_a2_browser_device_h205f22';
const STATE_TABLE='compute_fabric_a2_browser_supervisor_state_h205f22';
const COMMAND_TABLE='compute_fabric_a2_browser_supervisor_command_h205f22';
const NONCE_RPC='h205f22_a2_browser_device_consume_nonce_v2';
const PROFILE='A2_DEVICE_HTTP_SIGNATURE_V1';
const LEASE_TIMEOUT_SECONDS=120;
const MAX_SKEW_MS=120000;
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const B64URL_RE=/^[A-Za-z0-9_-]+$/;
const HEX64_RE=/^[0-9a-f]{64}$/;
const cors={'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-a2-chat-bridge-client,x-a2-device-profile,x-a2-device-id,x-a2-device-timestamp,x-a2-device-nonce,x-a2-device-body-sha256,x-a2-device-signature','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'no-referrer'};
function json(status:number,body:unknown){return new Response(JSON.stringify(body),{status,headers:{...cors,'content-type':'application/json; charset=utf-8'}})}
function restHeaders(extra:Record<string,string>={}){if(!SERVICE_ROLE)throw new Error('service_role_missing');return{apikey:SERVICE_ROLE,authorization:`Bearer ${SERVICE_ROLE}`,'content-type':'application/json',...extra}}
async function rest(path:string,init:RequestInit={}){const r=await fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:restHeaders(init.headers as Record<string,string>||{})});const text=await r.text();if(!r.ok)throw new Error(`rest_${r.status}`);return text?JSON.parse(text):null}
async function rpc(name:string,args:unknown){return rest(`rpc/${encodeURIComponent(name)}`,{method:'POST',body:JSON.stringify(args)})}
async function sha256(v:unknown){const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(v??'')));return[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function clientId(req:Request){const v=String(req.headers.get('x-a2-chat-bridge-client')||'').trim().slice(0,161);return v.length>=1&&v.length<=160?v:null}
function requestPath(req:Request){const p=new URL(req.url).pathname;const marker='/a2-browser-supervisor-v4-auth-canary';const i=p.indexOf(marker);return i>=0?(p.slice(i+marker.length)||'/'):p}
function fromB64url(v:string){const t=v.replace(/-/g,'+').replace(/_/g,'/');const p=t+'='.repeat((4-(t.length%4||4))%4);const b=atob(p);return Uint8Array.from(b,c=>c.charCodeAt(0))}
async function authenticateSigned(req:Request,path:string,bodyText:string){const profile=String(req.headers.get('x-a2-device-profile')||'');const deviceId=String(req.headers.get('x-a2-device-id')||'');const timestamp=String(req.headers.get('x-a2-device-timestamp')||'');const nonce=String(req.headers.get('x-a2-device-nonce')||'');const claimed=String(req.headers.get('x-a2-device-body-sha256')||'').toLowerCase();const sig=String(req.headers.get('x-a2-device-signature')||'');const client=clientId(req);if(profile!==PROFILE||!client||!UUID_RE.test(deviceId)||!HEX64_RE.test(claimed)||nonce.length<16||nonce.length>96||!B64URL_RE.test(nonce)||sig.length<64||sig.length>256||!B64URL_RE.test(sig))return{ok:false,reason:'SIGNED_HEADERS_INVALID'};const ts=Date.parse(timestamp);if(!Number.isFinite(ts)||Math.abs(Date.now()-ts)>MAX_SKEW_MS)return{ok:false,reason:'SIGNED_TIMESTAMP_INVALID'};const actual=await sha256(bodyText);if(actual!==claimed)return{ok:false,reason:'SIGNED_BODY_HASH_MISMATCH'};const rows=await rest(`${DEVICE_TABLE}?device_id=eq.${deviceId}&active=eq.true&select=device_id,client_id,profile,public_jwk,revoked_at&limit=1`);const row=Array.isArray(rows)?rows[0]:null;if(!row||row.client_id!==client||row.profile!==PROFILE||row.revoked_at)return{ok:false,reason:'SIGNED_DEVICE_INVALID'};const material=[PROFILE,`device_id:${deviceId}`,`method:${req.method.toUpperCase()}`,`path:${path}`,`timestamp:${timestamp}`,`nonce:${nonce}`,`body_sha256:${actual}`].join('\n');let key;try{key=await crypto.subtle.importKey('jwk',row.public_jwk,{name:'ECDSA',namedCurve:'P-256'},false,['verify'])}catch(_){return{ok:false,reason:'SIGNED_PUBLIC_KEY_INVALID'}}let signature;try{signature=fromB64url(sig)}catch(_){return{ok:false,reason:'SIGNED_SIGNATURE_ENCODING'}}const verified=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,signature,new TextEncoder().encode(material));if(!verified)return{ok:false,reason:'SIGNED_SIGNATURE_REJECTED'};const consumed=await rpc(NONCE_RPC,{p_device_id:deviceId,p_client_id:client,p_nonce_sha256:await sha256(nonce),p_request_timestamp:timestamp});if(consumed?.accepted!==true)return{ok:false,reason:String(consumed?.reason||'NONCE_REJECTED')};return{ok:true,device_id:deviceId,client_id:client,profile:PROFILE}}
function boundedState(input:any){const state=input&&typeof input==='object'?input:{};const events=Array.isArray(state.events)?state.events.slice(-30):[];const semantic=Array.isArray(state.semantic_targets)?state.semantic_targets.slice(0,60):[];return{schema:'metaengine.a2-browser-supervisor.state.v4',operator_runtime:String(state.operator_runtime||'').slice(0,80),extension_version:String(state.extension_version||'').slice(0,32),armed:state.armed===true,operator_mode:String(state.operator_mode||'').slice(0,32),supervisor_mode:String(state.supervisor_mode||'OFF').slice(0,16),ordering_policy:String(state.ordering_policy||'').slice(0,80),bridge:{online_at:state.bridge?.online_at||null,error:String(state.bridge?.error||'').slice(0,240),command_fetch_suppressed:String(state.bridge?.command_fetch_suppressed||'').slice(0,40)||null},peers:state.peers&&typeof state.peers==='object'?state.peers:{},ordering:state.ordering&&typeof state.ordering==='object'?state.ordering:{},perception:state.perception&&typeof state.perception==='object'?state.perception:{},semantic_targets:semantic,prompt_intent:state.prompt_intent&&typeof state.prompt_intent==='object'?state.prompt_intent:null,current_supervisor_command:state.current_supervisor_command&&typeof state.current_supervisor_command==='object'?state.current_supervisor_command:null,events}}
async function upsertState(auth:any,body:any){const s=boundedState(body?.state||{});const row={client_id:auth.client_id,workspace_id:WORKSPACE_ID,last_seen_at:new Date().toISOString(),extension_version:s.extension_version||null,operator_runtime:s.operator_runtime||null,supervisor_mode:['OFF','MONITOR','CONTROL'].includes(s.supervisor_mode)?s.supervisor_mode:'OFF',armed:s.armed,operator_mode:s.operator_mode||null,ordering_policy:s.ordering_policy||null,last_command_id:body?.last_command_id||null,last_command_status:body?.last_command_status||null,state:{...s,authenticated_device_id:auth.device_id},authority_effect:false};await rest(`${STATE_TABLE}?on_conflict=client_id`,{method:'POST',headers:{prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify(row)});return row}
async function lease(auth:any,bootstrap=false){return rpc(bootstrap?'h205f22_a2_browser_supervisor_lease_bootstrap_v3':'h205f22_a2_browser_supervisor_lease_v2',{p_workspace_id:WORKSPACE_ID,p_client_id:auth.client_id,p_lease_timeout_seconds:LEASE_TIMEOUT_SECONDS})}
async function result(auth:any,commandId:string,body:any){const rows=await rest(`${COMMAND_TABLE}?command_id=eq.${encodeURIComponent(commandId)}&select=command_id,status,leased_by&limit=1`);const row=Array.isArray(rows)?rows[0]:null;if(!row)return json(404,{error:'command_not_found'});if(row.leased_by!==auth.client_id)return json(409,{error:'supervisor_lease_owner_mismatch'});if(row.status!=='LEASED')return json(409,{error:'supervisor_command_not_leased'});const ok=body?.ok===true;const receipt=body?.receipt&&typeof body.receipt==='object'?body.receipt:{};await rest(`${COMMAND_TABLE}?command_id=eq.${encodeURIComponent(commandId)}`,{method:'PATCH',headers:{prefer:'return=minimal'},body:JSON.stringify({status:ok?'COMPLETED':'FAILED',completed_at:new Date().toISOString(),receipt:{...receipt,authenticated_device_id:auth.device_id},error:ok?null:String(body?.error||receipt?.error||'command_failed').slice(0,500)})});return json(200,{accepted:true,status:ok?'COMPLETED':'FAILED',authenticated_device_id:auth.device_id,authority_effect:false})}
async function status(auth:any){const states=await rest(`${STATE_TABLE}?workspace_id=eq.${WORKSPACE_ID}&select=*&order=last_seen_at.desc&limit=8`);const commands=await rest(`${COMMAND_TABLE}?workspace_id=eq.${WORKSPACE_ID}&select=command_id,idempotency_key,action,platform,status,issued_by,issued_at,expires_at,leased_by,leased_at,completed_at,receipt,error&order=issued_at.desc&limit=30`);return{schema:'metaengine.a2-browser-supervisor.status.v4',workspace_id:WORKSPACE_ID,authenticated_device_id:auth.device_id,lease_timeout_seconds:LEASE_TIMEOUT_SECONDS,states,commands,authority_effect:false}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});const path=requestPath(req);try{if(req.method==='GET'&&path==='/health')return json(200,{ok:true,schema:'metaengine.a2-browser-supervisor.health.v4',auth_profile:PROFILE,replay_fence:NONCE_RPC,bootstrap_lease_rpc:'h205f22_a2_browser_supervisor_lease_bootstrap_v3'});const bodyText=req.method==='GET'?'':await req.text();const auth=await authenticateSigned(req,path,bodyText);if(!auth.ok)return json(401,{error:'device_signature_required',reason:auth.reason});const body=bodyText?JSON.parse(bodyText):{};if(req.method==='POST'&&path==='/v1/state')return json(202,{accepted:true,state:await upsertState(auth,body),authenticated_device_id:auth.device_id,authority_effect:false});if(req.method==='POST'&&path==='/v1/commands/bootstrap-next')return json(200,await lease(auth,true));if(req.method==='POST'&&path==='/v1/commands/next')return json(200,await lease(auth,false));const m=path.match(/^\/v1\/commands\/([^/]+)\/result$/);if(req.method==='POST'&&m)return result(auth,decodeURIComponent(m[1]),body);if(req.method==='GET'&&path==='/v1/status')return json(200,await status(auth));return json(404,{error:'not_found'})}catch(e){console.error('a2_browser_supervisor_v4_failure',String((e as Error)?.message||e));return json(502,{error:'supervisor_v4_failure'})}});
